// Package ringapimodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ringapimodels

// Defines values for LightState.
const (
	LightStateOff LightState = "off"
	LightStateOn  LightState = "on"
)

// Valid indicates whether the value is a known member of the LightState enum.
func (e LightState) Valid() bool {
	switch e {
	case LightStateOff:
		return true
	case LightStateOn:
		return true
	default:
		return false
	}
}

// Defines values for SoundKind.
const (
	SoundKindDing   SoundKind = "ding"
	SoundKindMotion SoundKind = "motion"
)

// Valid indicates whether the value is a known member of the SoundKind enum.
func (e SoundKind) Valid() bool {
	switch e {
	case SoundKindDing:
		return true
	case SoundKindMotion:
		return true
	default:
		return false
	}
}

// Defines values for VolumeKind.
const (
	VolumeKindChime    VolumeKind = "chime"
	VolumeKindDoorbell VolumeKind = "doorbell"
)

// Valid indicates whether the value is a known member of the VolumeKind enum.
func (e VolumeKind) Valid() bool {
	switch e {
	case VolumeKindChime:
		return true
	case VolumeKindDoorbell:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	ExpiresIn    int    `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`

	// TokenType Bearer is used by the implemented OAuth flow; unknown token types remain representable.
	TokenType string `json:"token_type"`
}

// Device One account device. An absent capability means support was not confirmed by inventory; it does not prove the operation is unsupported.
type Device struct {
	Address      string             `json:"address"`
	Capabilities []DeviceCapability `json:"capabilities"`

	// Family Open server family; absent on some v3 responses
	Family string        `json:"family"`
	Health *DeviceHealth `json:"health,omitempty"`
	ID     string        `json:"id"`

	// Kind Open hardware kind from the server
	Kind                   string  `json:"kind"`
	LightBrightness        *int    `json:"light_brightness,omitempty"`
	MotionDetectionEnabled *bool   `json:"motion_detection_enabled,omitempty"`
	Name                   string  `json:"name"`
	Timezone               string  `json:"timezone"`
	Volume                 *int    `json:"volume,omitempty"`
	WifiName               *string `json:"wifi_name,omitempty"`
	WifiSignalStrength     *int    `json:"wifi_signal_strength,omitempty"`
}

// DeviceCapability A supported operation confirmed by an explicit inventory field. Unknown server capabilities remain representable.
type DeviceCapability = string

// DeviceHealth defines model for DeviceHealth.
type DeviceHealth struct {
	BatteryLevel    *int    `json:"battery_level"`
	BatteryStatus   *string `json:"battery_status"`
	FirmwareVersion *string `json:"firmware_version"`
	LastUpdate      *string `json:"last_update"`
	SignalStrength  *int    `json:"signal_strength"`
}

// DevicesResponse defines model for DevicesResponse.
type DevicesResponse struct {
	Devices []Device `json:"devices"`
}

// Event defines model for Event.
type Event struct {
	Data     map[string]interface{} `json:"data"`
	DeviceID int64                  `json:"device_id"`

	// Kind Known event kinds are motion, ding and on_demand. Preserve future values from the service.
	Kind      EventKind `json:"kind"`
	Timestamp string    `json:"timestamp"`
}

// EventKind Known event kinds are motion, ding and on_demand. Preserve future values from the service.
type EventKind = string

// InHomeChimeSettings Supply exactly one field per update. Enabled maps to the legacy enable query value.
type InHomeChimeSettings struct {
	Duration *int  `json:"duration,omitempty"`
	Enabled  *bool `json:"enabled,omitempty"`
	Type     *int  `json:"type,omitempty"`
}

// LightState Legacy floodlight action.
type LightState string

// Recording defines model for Recording.
type Recording struct {
	Answered  bool   `json:"answered"`
	CreatedAt string `json:"created_at"`
	DeviceID  int64  `json:"device_id"`
	ID        int64  `json:"id"`

	// Kind Known recording kinds are motion, ding and on_demand; future values remain valid.
	Kind string `json:"kind"`
}

// RecordingHistoryResponse defines model for RecordingHistoryResponse.
type RecordingHistoryResponse struct {
	Recordings []Recording `json:"recordings"`
}

// SoundKind Accepted legacy chime test sounds.
type SoundKind string

// VolumeKind Legacy volume control target; selects the chime or doorbell endpoint.
type VolumeKind string
