// Package ringapimodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ringapimodels

import (
	"time"

	ringtypes "github.com/portpowered/go-ring/pkg/ringtypes"
)

// Defines values for DeviceType.
const (
	DeviceTypeCamera   DeviceType = "CAMERA"
	DeviceTypeChime    DeviceType = "CHIME"
	DeviceTypeDoorbell DeviceType = "DOORBELL"
	DeviceTypeOther    DeviceType = "OTHER"
)

// Valid indicates whether the value is a known member of the DeviceType enum.
func (e DeviceType) Valid() bool {
	switch e {
	case DeviceTypeCamera:
		return true
	case DeviceTypeChime:
		return true
	case DeviceTypeDoorbell:
		return true
	case DeviceTypeOther:
		return true
	default:
		return false
	}
}

// Defines values for LightState.
const (
	LightStateOff LightState = "off"
	LightStateOn  LightState = "on"
)

// Valid indicates whether the value is a known member of the LightState enum.
func (e LightState) Valid() bool {
	switch e {
	case LightStateOff:
		return true
	case LightStateOn:
		return true
	default:
		return false
	}
}

// Defines values for SoundKind.
const (
	SoundKindDing   SoundKind = "ding"
	SoundKindMotion SoundKind = "motion"
)

// Valid indicates whether the value is a known member of the SoundKind enum.
func (e SoundKind) Valid() bool {
	switch e {
	case SoundKindDing:
		return true
	case SoundKindMotion:
		return true
	default:
		return false
	}
}

// Defines values for VolumeKind.
const (
	VolumeKindChime    VolumeKind = "chime"
	VolumeKindDoorbell VolumeKind = "doorbell"
)

// Valid indicates whether the value is a known member of the VolumeKind enum.
func (e VolumeKind) Valid() bool {
	switch e {
	case VolumeKindChime:
		return true
	case VolumeKindDoorbell:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	ExpiresIn    int    `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`

	// TokenType Bearer is used by the implemented OAuth flow; unknown token types remain representable.
	TokenType string `json:"token_type"`
}

// BatteryReading Battery percentage accepted as a JSON number or numeric text by the SDK adapter.
type BatteryReading = ringtypes.BatteryReading

// CapturedTickets defines model for CapturedTickets.
type CapturedTickets struct {
	Host               string   `json:"host"`
	SubscriptionTopics []string `json:"subscriptionTopics,omitempty"`
	Ticket             string   `json:"ticket"`
}

// ConnectionState Open connection state.
type ConnectionState = ringtypes.ConnectionState

// DetailDeviceFamily Open device family in detail and inventory responses.
type DetailDeviceFamily = ringtypes.DeviceFamily

// Device One account device. An absent capability means support was not confirmed by inventory; it does not prove the operation is unsupported.
type Device struct {
	Address      string             `json:"address"`
	Capabilities []DeviceCapability `json:"capabilities"`

	// Family Open server family; absent on some v3 responses
	Family string        `json:"family"`
	Health *DeviceHealth `json:"health,omitempty"`
	ID     string        `json:"id"`

	// Kind Open hardware kind from the server
	Kind                   string `json:"kind"`
	LightBrightness        *int   `json:"light_brightness,omitempty"`
	MotionDetectionEnabled *bool  `json:"motion_detection_enabled,omitempty"`
	Name                   string `json:"name"`
	Timezone               string `json:"timezone"`

	// Type Normalized device class derived from a known hardware kind or explicit family. Unknown kinds remain OTHER; live-view support alone does not classify hardware.
	Type               DeviceType `json:"type"`
	Volume             *int       `json:"volume,omitempty"`
	WifiName           *string    `json:"wifi_name,omitempty"`
	WifiSignalStrength *int       `json:"wifi_signal_strength,omitempty"`
}

// DeviceAlerts defines model for DeviceAlerts.
type DeviceAlerts struct {
	// Connection Open connection state.
	Connection *ConnectionState `json:"connection,omitempty"`
}

// DeviceCapability A supported operation confirmed by an explicit inventory field. Unknown server capabilities remain representable.
type DeviceCapability = string

// DeviceDetail SDK projection of the generated device-detail wire response; operation sets are derived separately.
type DeviceDetail struct {
	Device DeviceDetailDevice `json:"device"`
}

// DeviceDetailDevice defines model for DeviceDetailDevice.
type DeviceDetailDevice struct {
	Address *string       `json:"address,omitempty"`
	Alerts  *DeviceAlerts `json:"alerts,omitempty"`

	// BatteryLife Battery percentage accepted as a JSON number or numeric text by the SDK adapter.
	BatteryLife *BatteryReading `json:"battery_life,omitempty"`

	// BatteryLife2 Battery percentage accepted as a JSON number or numeric text by the SDK adapter.
	BatteryLife2       *BatteryReading `json:"battery_life_2,omitempty"`
	CreatedAt          *time.Time      `json:"created_at,omitempty"`
	DeactivatedAt      *time.Time      `json:"deactivated_at,omitempty"`
	Description        string          `json:"description"`
	DeviceID           *string         `json:"device_id,omitempty"`
	ExternalConnection *bool           `json:"external_connection,omitempty"`

	// Family Open device family in detail and inventory responses.
	Family   *DetailDeviceFamily `json:"family,omitempty"`
	Features *DeviceFeatures     `json:"features,omitempty"`
	HasLight *bool               `json:"has_light,omitempty"`
	Health   *DeviceDetailHealth `json:"health,omitempty"`
	ID       int64               `json:"id"`

	// Kind Open hardware kind in device detail.
	Kind                   DeviceKind            `json:"kind"`
	LightBrightness        *int                  `json:"light_brightness,omitempty"`
	LocationID             *string               `json:"location_id,omitempty"`
	MotionDetectionEnabled *bool                 `json:"motion_detection_enabled,omitempty"`
	Name                   *string               `json:"name,omitempty"`
	OperationSet           *string               `json:"operation_set,omitempty"`
	Owned                  *bool                 `json:"owned,omitempty"`
	Owner                  *DeviceOwner          `json:"owner,omitempty"`
	Settings               *DeviceLegacySettings `json:"settings,omitempty"`
	TimeZone               *string               `json:"time_zone,omitempty"`
	Timezone               *string               `json:"timezone,omitempty"`
	Volume                 *int                  `json:"volume,omitempty"`
	WifiName               *string               `json:"wifi_name,omitempty"`
	WifiSignalStrength     *int                  `json:"wifi_signal_strength,omitempty"`
}

// DeviceDetailHealth defines model for DeviceDetailHealth.
type DeviceDetailHealth struct {
	BatteryLevel              *int     `json:"battery_level,omitempty"`
	BatteryPercentage         *float64 `json:"battery_percentage,omitempty"`
	BatteryPercentageCategory *string  `json:"battery_percentage_category,omitempty"`
	BatteryPresent            *bool    `json:"battery_present,omitempty"`
	BatteryStatus             *string  `json:"battery_status,omitempty"`
	Connected                 *bool    `json:"connected,omitempty"`
	FirmwareVersion           *string  `json:"firmware_version,omitempty"`
	LastUpdate                *string  `json:"last_update,omitempty"`
	PTZConnected              *string  `json:"ptz_connected,omitempty"`
	RSSI                      *float32 `json:"rssi,omitempty"`
	SignalStrength            *int     `json:"signal_strength,omitempty"`
	SupportedRPCCommands      []string `json:"supported_rpc_commands,omitempty"`
}

// DeviceFeatures defines model for DeviceFeatures.
type DeviceFeatures struct {
	AutoTrack      *FeatureAvailability   `json:"auto_track,omitempty"`
	AutoZoomTrack  *FeatureAvailability   `json:"auto_zoom_track,omitempty"`
	MotionsEnabled *bool                  `json:"motions_enabled,omitempty"`
	VideoRendering *VideoRenderingFeature `json:"video_rendering,omitempty"`
}

// DeviceHealth defines model for DeviceHealth.
type DeviceHealth struct {
	BatteryLevel    *int    `json:"battery_level"`
	BatteryStatus   *string `json:"battery_status"`
	FirmwareVersion *string `json:"firmware_version"`
	LastUpdate      *string `json:"last_update"`
	SignalStrength  *int    `json:"signal_strength"`
}

// DeviceKind Open hardware kind in device detail.
type DeviceKind = ringtypes.DeviceKind

// DeviceLegacySettings defines model for DeviceLegacySettings.
type DeviceLegacySettings struct {
	DoorbellVolume         *int  `json:"doorbell_volume,omitempty"`
	LiveViewDisabled       *bool `json:"live_view_disabled,omitempty"`
	MotionDetectionEnabled *bool `json:"motion_detection_enabled,omitempty"`

	// PowerMode Open device power mode.
	PowerMode *PowerMode `json:"power_mode,omitempty"`
}

// DeviceOwner defines model for DeviceOwner.
type DeviceOwner struct {
	Email     *string `json:"email,omitempty"`
	FirstName *string `json:"first_name,omitempty"`

	// ID Numeric or text vendor owner identifier normalized to text by the SDK adapter.
	ID       *OwnerID `json:"id,omitempty"`
	LastName *string  `json:"last_name,omitempty"`
}

// DeviceStatus SDK-derived status from device detail, not an additional wire response.
type DeviceStatus struct {
	BatteryPercent *float64 `json:"battery_percent,omitempty"`

	// Connection Open connection state.
	Connection *ConnectionState `json:"connection,omitempty"`
	IsOffline  bool             `json:"is_offline"`

	// PowerMode Open device power mode.
	PowerMode *PowerMode `json:"power_mode,omitempty"`
}

// DeviceTimeline defines model for DeviceTimeline.
type DeviceTimeline struct {
	Items         []TimelineEvent `json:"items"`
	PaginationKey *string         `json:"pagination_key,omitempty"`
}

// DeviceType Normalized device class derived from a known hardware kind or explicit family. Unknown kinds remain OTHER; live-view support alone does not classify hardware.
type DeviceType string

// DevicesResponse defines model for DevicesResponse.
type DevicesResponse struct {
	Devices []Device `json:"devices"`
}

// Event defines model for Event.
type Event struct {
	Data     map[string]interface{} `json:"data"`
	DeviceID int64                  `json:"device_id"`

	// Kind Known event kinds are motion, ding and on_demand. Preserve future values from the service.
	Kind      EventKind `json:"kind"`
	Timestamp string    `json:"timestamp"`
}

// EventKind Known event kinds are motion, ding and on_demand. Preserve future values from the service.
type EventKind = string

// FeatureAvailability defines model for FeatureAvailability.
type FeatureAvailability struct {
	Eligibility *FeatureEligibility `json:"eligibility,omitempty"`
	Enablement  *FeatureEnablement  `json:"enablement,omitempty"`
}

// FeatureEligibility defines model for FeatureEligibility.
type FeatureEligibility struct {
	Eligible             *bool    `json:"eligible,omitempty"`
	IneligibilityReasons []string `json:"ineligibility_reasons,omitempty"`
}

// FeatureEnablement defines model for FeatureEnablement.
type FeatureEnablement struct {
	Allowed         *bool    `json:"allowed,omitempty"`
	DisallowReasons []string `json:"disallow_reasons,omitempty"`
	Enabled         *bool    `json:"enabled,omitempty"`
}

// GeoCoordinates defines model for GeoCoordinates.
type GeoCoordinates struct {
	Latitude  *float32 `json:"latitude,omitempty"`
	Longitude *float32 `json:"longitude,omitempty"`
}

// HistoryDevices defines model for HistoryDevices.
type HistoryDevices struct {
	Events        []TimelineEvent   `json:"events"`
	Feed          []HistoryFeedItem `json:"feed,omitempty"`
	PaginationKey *string           `json:"pagination_key,omitempty"`
	Schema        *string           `json:"schema,omitempty"`
}

// HistoryFeedItem defines model for HistoryFeedItem.
type HistoryFeedItem struct {
	ID   *string          `json:"id,omitempty"`
	Type *HistoryFeedType `json:"type,omitempty"`
}

// HistoryFeedType defines model for HistoryFeedType.
type HistoryFeedType = ringtypes.HistoryFeedType

// InHomeChimeSettings Supply exactly one field per update. Enabled maps to the legacy enable query value.
type InHomeChimeSettings struct {
	Duration *int  `json:"duration,omitempty"`
	Enabled  *bool `json:"enabled,omitempty"`
	Type     *int  `json:"type,omitempty"`
}

// LightState Legacy floodlight action.
type LightState string

// LocationAddress defines model for LocationAddress.
type LocationAddress struct {
	Address1 *string `json:"address1,omitempty"`
	Address2 *string `json:"address2,omitempty"`
	City     *string `json:"city,omitempty"`
	Country  *string `json:"country,omitempty"`
	State    *string `json:"state,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
	ZipCode  *string `json:"zip_code,omitempty"`
}

// LocationAttributes defines model for LocationAttributes.
type LocationAttributes struct {
	City      *string  `json:"city,omitempty"`
	Country   *string  `json:"country,omitempty"`
	Latitude  *float32 `json:"latitude,omitempty"`
	Longitude *float32 `json:"longitude,omitempty"`
	Name      *string  `json:"name,omitempty"`
	State     *string  `json:"state,omitempty"`
	TimeZone  *string  `json:"time_zone,omitempty"`
}

// LocationDetail defines model for LocationDetail.
type LocationDetail struct {
	Data     LocationResource   `json:"data"`
	Included []LocationResource `json:"included,omitempty"`
	Meta     *LocationMeta      `json:"meta,omitempty"`
}

// LocationGroup defines model for LocationGroup.
type LocationGroup struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// LocationGroupDevices defines model for LocationGroupDevices.
type LocationGroupDevices struct {
	Groups []LocationGroup `json:"groups"`
}

// LocationGroups defines model for LocationGroups.
type LocationGroups struct {
	DeviceGroups []LocationGroup `json:"device_groups,omitempty"`
	IsOwner      *bool           `json:"is_owner,omitempty"`
}

// LocationList SDK projection; OperationSets is derived outside JSON.
type LocationList struct {
	Locations []LocationSummary `json:"user_locations"`
}

// LocationMeta defines model for LocationMeta.
type LocationMeta struct {
	Time *time.Time `json:"time,omitempty"`
}

// LocationResource defines model for LocationResource.
type LocationResource struct {
	Attributes *LocationAttributes  `json:"attributes,omitempty"`
	ID         string               `json:"id"`
	Type       LocationResourceType `json:"type"`
}

// LocationResourceType defines model for LocationResourceType.
type LocationResourceType = ringtypes.LocationResourceType

// LocationSummary defines model for LocationSummary.
type LocationSummary struct {
	Address        *LocationAddress `json:"address,omitempty"`
	GeoCoordinates *GeoCoordinates  `json:"geo_coordinates,omitempty"`
	IsOwner        *bool            `json:"is_owner,omitempty"`
	ID             string           `json:"location_id"`
	LocationType   *string          `json:"location_type,omitempty"`
	Name           string           `json:"name"`
	OwnerID        *int64           `json:"owner_id,omitempty"`
}

// OwnerID Numeric or text vendor owner identifier normalized to text by the SDK adapter.
type OwnerID = ringtypes.OwnerID

// PowerMode Open device power mode.
type PowerMode = ringtypes.PowerMode

// Recording defines model for Recording.
type Recording struct {
	Answered  bool   `json:"answered"`
	CreatedAt string `json:"created_at"`
	DeviceID  int64  `json:"device_id"`
	ID        int64  `json:"id"`

	// Kind Known recording kinds are motion, ding and on_demand; future values remain valid.
	Kind string `json:"kind"`
}

// RecordingHistoryResponse defines model for RecordingHistoryResponse.
type RecordingHistoryResponse struct {
	Recordings []Recording `json:"recordings"`
}

// RecordingStatus defines model for RecordingStatus.
type RecordingStatus = ringtypes.RecordingStatus

// SoundKind Accepted legacy chime test sounds.
type SoundKind string

// TimelineDevice defines model for TimelineDevice.
type TimelineDevice struct {
	Description *string `json:"description,omitempty"`
	ID          *int64  `json:"id,omitempty"`
	Type        *string `json:"type,omitempty"`
}

// TimelineEvent defines model for TimelineEvent.
type TimelineEvent struct {
	Device          *TimelineDevice   `json:"device,omitempty"`
	DurationMS      *int              `json:"duration_ms,omitempty"`
	EndTime         *time.Time        `json:"end_time,omitempty"`
	ID              string            `json:"event_id"`
	Type            TimelineEventType `json:"event_type"`
	IsFavorite      *bool             `json:"is_favorite,omitempty"`
	RecordingStatus *RecordingStatus  `json:"recording_status,omitempty"`
	Schema          *string           `json:"schema,omitempty"`
	SourceID        *string           `json:"source_id,omitempty"`
	StartTime       time.Time         `json:"start_time"`
	State           *TimelineState    `json:"state,omitempty"`
}

// TimelineEventType defines model for TimelineEventType.
type TimelineEventType = ringtypes.TimelineEventType

// TimelineState defines model for TimelineState.
type TimelineState = ringtypes.TimelineState

// VideoRenderingFeature defines model for VideoRenderingFeature.
type VideoRenderingFeature struct {
	MaxDigitalZoomLevel *float32 `json:"max_digital_zoom_level,omitempty"`
}

// VolumeKind Legacy volume control target; selects the chime or doorbell endpoint.
type VolumeKind string
