// Package generatedfcm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package generatedfcm

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// RegisterFCMClientWithBody Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithBody(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterFCMClientWithFormdataBody Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithFormdataBody(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckInFCMClientWithBody Check in an Android or Chrome client
	//
	// Sends an Android check-in protobuf and receives assigned device credentials.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
	CheckInFCMClientWithBody(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFCMInstallationWithBody Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallationWithBody(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFCMInstallation Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallation(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterFCMInstallationWithBody Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallationWithBody(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterFCMInstallation Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallation(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// RegisterFCMClientWithBody Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *Client) RegisterFCMClientWithBody(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMClientRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterFCMClientWithFormdataBody Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes a body of the `application/x-www-form-urlencoded` content type.
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *Client) RegisterFCMClientWithFormdataBody(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMClientRequestWithFormdataBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CheckInFCMClientWithBody Check in an Android or Chrome client
//
// Sends an Android check-in protobuf and receives assigned device credentials.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
func (c *Client) CheckInFCMClientWithBody(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckInFCMClientRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateFCMInstallationWithBody Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *Client) CreateFCMInstallationWithBody(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFCMInstallationRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateFCMInstallation Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *Client) CreateFCMInstallation(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFCMInstallationRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterFCMInstallationWithBody Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *Client) RegisterFCMInstallationWithBody(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMInstallationRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterFCMInstallation Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *Client) RegisterFCMInstallation(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMInstallationRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRegisterFCMClientRequestWithFormdataBody calls the generic RegisterFCMClient builder with application/x-www-form-urlencoded body
func NewRegisterFCMClientRequestWithFormdataBody(server string, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewRegisterFCMClientRequestWithBody(server, params, "application/x-www-form-urlencoded", bodyReader)
}

// NewRegisterFCMClientRequestWithBody constructs an http.Request for the RegisterFCMClient method, with any body, and a specified content type
func NewRegisterFCMClientRequestWithBody(server string, params *RegisterFCMClientParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/c2dm/register3")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("User-Agent", headerParam2)

	}

	return req, nil
}

// NewCheckInFCMClientRequestWithBody constructs an http.Request for the CheckInFCMClient method, with any body, and a specified content type
func NewCheckInFCMClientRequestWithBody(server string, params *CheckInFCMClientParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/checkin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam0)

	}

	return req, nil
}

// NewCreateFCMInstallationRequest calls the generic CreateFCMInstallation builder with application/json body
func NewCreateFCMInstallationRequest(server string, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateFCMInstallationRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateFCMInstallationRequestWithBody constructs an http.Request for the CreateFCMInstallation method, with any body, and a specified content type
func NewCreateFCMInstallationRequestWithBody(server string, params *CreateFCMInstallationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/ring-17770/installations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Accept", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "X-Goog-Api-Key", params.XGoogApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Goog-Api-Key", headerParam2)

	}

	return req, nil
}

// NewRegisterFCMInstallationRequest calls the generic RegisterFCMInstallation builder with application/json body
func NewRegisterFCMInstallationRequest(server string, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterFCMInstallationRequestWithBody(server, params, "application/json", bodyReader)
}

// NewRegisterFCMInstallationRequestWithBody constructs an http.Request for the RegisterFCMInstallation method, with any body, and a specified content type
func NewRegisterFCMInstallationRequestWithBody(server string, params *RegisterFCMInstallationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/ring-17770/registrations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Goog-Api-Key", params.XGoogApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Goog-Api-Key", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "X-Goog-Firebase-Installations-Auth", params.XGoogFirebaseInstallationsAuth, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Goog-Firebase-Installations-Auth", headerParam2)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// RegisterFCMClientWithBodyWithResponse Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error)

	// RegisterFCMClientWithFormdataBodyWithResponse Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithFormdataBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error)

	// CheckInFCMClientWithBodyWithResponse Check in an Android or Chrome client
	//
	// Sends an Android check-in protobuf and receives assigned device credentials.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
	CheckInFCMClientWithBodyWithResponse(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckInFCMClientResponse, error)

	// CreateFCMInstallationWithBodyWithResponse Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallationWithBodyWithResponse(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error)

	// CreateFCMInstallationWithResponse Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallationWithResponse(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error)

	// RegisterFCMInstallationWithBodyWithResponse Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallationWithBodyWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error)

	// RegisterFCMInstallationWithResponse Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallationWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error)
}

type RegisterFCMClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r RegisterFCMClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RegisterFCMClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterFCMClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterFCMClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CheckInFCMClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CheckInFCMClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CheckInFCMClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckInFCMClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CheckInFCMClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateFCMInstallationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *InstallationResponse
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *InstallationResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateFCMInstallationResponse) GetJSON200() *InstallationResponse {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateFCMInstallationResponse) GetJSON201() *InstallationResponse {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r CreateFCMInstallationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateFCMInstallationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateFCMInstallationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateFCMInstallationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RegisterFCMInstallationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FCMRegistrationResponse
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *FCMRegistrationResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RegisterFCMInstallationResponse) GetJSON200() *FCMRegistrationResponse {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r RegisterFCMInstallationResponse) GetJSON201() *FCMRegistrationResponse {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r RegisterFCMInstallationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RegisterFCMInstallationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterFCMInstallationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterFCMInstallationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// RegisterFCMClientWithBodyWithResponse Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *ClientWithResponses) RegisterFCMClientWithBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error) {
	rsp, err := c.RegisterFCMClientWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMClientResponse(rsp)
}

// RegisterFCMClientWithFormdataBodyWithResponse Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *ClientWithResponses) RegisterFCMClientWithFormdataBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error) {
	rsp, err := c.RegisterFCMClientWithFormdataBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMClientResponse(rsp)
}

// CheckInFCMClientWithBodyWithResponse Check in an Android or Chrome client
//
// Sends an Android check-in protobuf and receives assigned device credentials.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
func (c *ClientWithResponses) CheckInFCMClientWithBodyWithResponse(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckInFCMClientResponse, error) {
	rsp, err := c.CheckInFCMClientWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckInFCMClientResponse(rsp)
}

// CreateFCMInstallationWithBodyWithResponse Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *ClientWithResponses) CreateFCMInstallationWithBodyWithResponse(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error) {
	rsp, err := c.CreateFCMInstallationWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFCMInstallationResponse(rsp)
}

// CreateFCMInstallationWithResponse Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *ClientWithResponses) CreateFCMInstallationWithResponse(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error) {
	rsp, err := c.CreateFCMInstallation(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFCMInstallationResponse(rsp)
}

// RegisterFCMInstallationWithBodyWithResponse Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *ClientWithResponses) RegisterFCMInstallationWithBodyWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error) {
	rsp, err := c.RegisterFCMInstallationWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMInstallationResponse(rsp)
}

// RegisterFCMInstallationWithResponse Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *ClientWithResponses) RegisterFCMInstallationWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error) {
	rsp, err := c.RegisterFCMInstallation(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMInstallationResponse(rsp)
}

// ParseRegisterFCMClientResponse parses an HTTP response from a RegisterFCMClientWithResponse call
func ParseRegisterFCMClientResponse(rsp *http.Response) (*RegisterFCMClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterFCMClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCheckInFCMClientResponse parses an HTTP response from a CheckInFCMClientWithResponse call
func ParseCheckInFCMClientResponse(rsp *http.Response) (*CheckInFCMClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckInFCMClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCreateFCMInstallationResponse parses an HTTP response from a CreateFCMInstallationWithResponse call
func ParseCreateFCMInstallationResponse(rsp *http.Response) (*CreateFCMInstallationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateFCMInstallationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InstallationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest InstallationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseRegisterFCMInstallationResponse parses an HTTP response from a RegisterFCMInstallationWithResponse call
func ParseRegisterFCMInstallationResponse(rsp *http.Response) (*RegisterFCMInstallationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterFCMInstallationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FCMRegistrationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FCMRegistrationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}
