// Package generatedfcm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package generatedfcm

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InstallationRequestAppId.
const (
	InstallationRequestAppIdN1876313859327AndroidE10ec6ddb3c81f39 InstallationRequestAppId = "1:876313859327:android:e10ec6ddb3c81f39"
)

// Valid indicates whether the value is a known member of the InstallationRequestAppId enum.
func (e InstallationRequestAppId) Valid() bool {
	switch e {
	case InstallationRequestAppIdN1876313859327AndroidE10ec6ddb3c81f39:
		return true
	default:
		return false
	}
}

// Defines values for InstallationRequestAuthVersion.
const (
	FISV2 InstallationRequestAuthVersion = "FIS_v2"
)

// Valid indicates whether the value is a known member of the InstallationRequestAuthVersion enum.
func (e InstallationRequestAuthVersion) Valid() bool {
	switch e {
	case FISV2:
		return true
	default:
		return false
	}
}

// Defines values for InstallationRequestSdkVersion.
const (
	W0617 InstallationRequestSdkVersion = "w:0.6.17"
)

// Valid indicates whether the value is a known member of the InstallationRequestSdkVersion enum.
func (e InstallationRequestSdkVersion) Valid() bool {
	switch e {
	case W0617:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRegistrationRequestXSubtype.
const (
	LegacyRegistrationRequestXSubtypeN1876313859327AndroidE10ec6ddb3c81f39 LegacyRegistrationRequestXSubtype = "1:876313859327:android:e10ec6ddb3c81f39"
)

// Valid indicates whether the value is a known member of the LegacyRegistrationRequestXSubtype enum.
func (e LegacyRegistrationRequestXSubtype) Valid() bool {
	switch e {
	case LegacyRegistrationRequestXSubtypeN1876313859327AndroidE10ec6ddb3c81f39:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRegistrationRequestApp.
const (
	OrgChromiumLinux LegacyRegistrationRequestApp = "org.chromium.linux"
)

// Valid indicates whether the value is a known member of the LegacyRegistrationRequestApp enum.
func (e LegacyRegistrationRequestApp) Valid() bool {
	switch e {
	case OrgChromiumLinux:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRegistrationRequestSender.
const (
	BDOU99H67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv4L2LxQcYwhqby2xGpWwzjfAnG4 LegacyRegistrationRequestSender = "BDOU99-h67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv-4_l2LxQcYwhqby2xGpWwzjfAnG4"
)

// Valid indicates whether the value is a known member of the LegacyRegistrationRequestSender enum.
func (e LegacyRegistrationRequestSender) Valid() bool {
	switch e {
	case BDOU99H67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv4L2LxQcYwhqby2xGpWwzjfAnG4:
		return true
	default:
		return false
	}
}

// Defines values for GoogleAPIKey.
const (
	GoogleAPIKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8 GoogleAPIKey = "AIzaSyCv-hdFBmmdBBJadNy-TFwB-xN_H5m3Bk8"
)

// Valid indicates whether the value is a known member of the GoogleAPIKey enum.
func (e GoogleAPIKey) Valid() bool {
	switch e {
	case GoogleAPIKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8:
		return true
	default:
		return false
	}
}

// Defines values for JSONAccept.
const (
	JSONAcceptApplicationjson JSONAccept = "application/json"
)

// Valid indicates whether the value is a known member of the JSONAccept enum.
func (e JSONAccept) Valid() bool {
	switch e {
	case JSONAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for JSONContentType.
const (
	JSONContentTypeApplicationjson JSONContentType = "application/json"
)

// Valid indicates whether the value is a known member of the JSONContentType enum.
func (e JSONContentType) Valid() bool {
	switch e {
	case JSONContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for ProtobufContentType.
const (
	ProtobufContentTypeApplicationxProtobuf ProtobufContentType = "application/x-protobuf"
)

// Valid indicates whether the value is a known member of the ProtobufContentType enum.
func (e ProtobufContentType) Valid() bool {
	switch e {
	case ProtobufContentTypeApplicationxProtobuf:
		return true
	default:
		return false
	}
}

// Defines values for RegisterFCMClientParamsContentType.
const (
	ApplicationxWwwFormUrlencoded RegisterFCMClientParamsContentType = "application/x-www-form-urlencoded"
)

// Valid indicates whether the value is a known member of the RegisterFCMClientParamsContentType enum.
func (e RegisterFCMClientParamsContentType) Valid() bool {
	switch e {
	case ApplicationxWwwFormUrlencoded:
		return true
	default:
		return false
	}
}

// Defines values for CheckInFCMClientParamsContentType.
const (
	CheckInFCMClientParamsContentTypeApplicationxProtobuf CheckInFCMClientParamsContentType = "application/x-protobuf"
)

// Valid indicates whether the value is a known member of the CheckInFCMClientParamsContentType enum.
func (e CheckInFCMClientParamsContentType) Valid() bool {
	switch e {
	case CheckInFCMClientParamsContentTypeApplicationxProtobuf:
		return true
	default:
		return false
	}
}

// Defines values for CreateFCMInstallationParamsAccept.
const (
	CreateFCMInstallationParamsAcceptApplicationjson CreateFCMInstallationParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the CreateFCMInstallationParamsAccept enum.
func (e CreateFCMInstallationParamsAccept) Valid() bool {
	switch e {
	case CreateFCMInstallationParamsAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for CreateFCMInstallationParamsContentType.
const (
	CreateFCMInstallationParamsContentTypeApplicationjson CreateFCMInstallationParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the CreateFCMInstallationParamsContentType enum.
func (e CreateFCMInstallationParamsContentType) Valid() bool {
	switch e {
	case CreateFCMInstallationParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for CreateFCMInstallationParamsXGoogApiKey.
const (
	CreateFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8 CreateFCMInstallationParamsXGoogApiKey = "AIzaSyCv-hdFBmmdBBJadNy-TFwB-xN_H5m3Bk8"
)

// Valid indicates whether the value is a known member of the CreateFCMInstallationParamsXGoogApiKey enum.
func (e CreateFCMInstallationParamsXGoogApiKey) Valid() bool {
	switch e {
	case CreateFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8:
		return true
	default:
		return false
	}
}

// Defines values for RegisterFCMInstallationParamsContentType.
const (
	RegisterFCMInstallationParamsContentTypeApplicationjson RegisterFCMInstallationParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the RegisterFCMInstallationParamsContentType enum.
func (e RegisterFCMInstallationParamsContentType) Valid() bool {
	switch e {
	case RegisterFCMInstallationParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for RegisterFCMInstallationParamsXGoogApiKey.
const (
	RegisterFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8 RegisterFCMInstallationParamsXGoogApiKey = "AIzaSyCv-hdFBmmdBBJadNy-TFwB-xN_H5m3Bk8"
)

// Valid indicates whether the value is a known member of the RegisterFCMInstallationParamsXGoogApiKey enum.
func (e RegisterFCMInstallationParamsXGoogApiKey) Valid() bool {
	switch e {
	case RegisterFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8:
		return true
	default:
		return false
	}
}

// AndroidCheckinRequestWire Protobuf wire encoding of checkin_proto.AndroidCheckinRequest in the pinned checkin.proto files.
type AndroidCheckinRequestWire = openapi_types.File

// AndroidCheckinResponseWire Protobuf wire encoding of checkin_proto.AndroidCheckinResponse in the pinned checkin.proto files.
type AndroidCheckinResponseWire = openapi_types.File

// FCMRegistrationRequest defines model for FCMRegistrationRequest.
type FCMRegistrationRequest struct {
	Web FCMWebRegistration `json:"web"`
}

// FCMRegistrationResponse defines model for FCMRegistrationResponse.
type FCMRegistrationResponse struct {
	PushSet              *string                `json:"pushSet,omitempty"`
	Token                string                 `json:"token"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FCMWebRegistration defines model for FCMWebRegistration.
type FCMWebRegistration struct {
	// Auth URL-safe base64 encoding of a 16-byte Web Push authentication secret.
	Auth     string `json:"auth"`
	Endpoint string `json:"endpoint"`

	// P256dh URL-safe base64 encoding of a 65-byte uncompressed P-256 public key.
	P256dh string `json:"p256dh"`
}

// InstallationAuthToken defines model for InstallationAuthToken.
type InstallationAuthToken struct {
	ExpiresIn            *string                `json:"expiresIn,omitempty"`
	Token                string                 `json:"token"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// InstallationRequest defines model for InstallationRequest.
type InstallationRequest struct {
	AppId       InstallationRequestAppId       `json:"appId"`
	AuthVersion InstallationRequestAuthVersion `json:"authVersion"`

	// Fid Base64-encoded 17-byte FID from the pinned receiver implementation.
	Fid        string                        `json:"fid"`
	SdkVersion InstallationRequestSdkVersion `json:"sdkVersion"`
}

// InstallationRequestAppId defines model for InstallationRequest.AppId.
type InstallationRequestAppId string

// InstallationRequestAuthVersion defines model for InstallationRequest.AuthVersion.
type InstallationRequestAuthVersion string

// InstallationRequestSdkVersion defines model for InstallationRequest.SdkVersion.
type InstallationRequestSdkVersion string

// InstallationResponse defines model for InstallationResponse.
type InstallationResponse struct {
	AuthToken            InstallationAuthToken  `json:"authToken"`
	Fid                  string                 `json:"fid"`
	Name                 string                 `json:"name"`
	RefreshToken         string                 `json:"refreshToken"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LegacyRegistrationRequest Form fields are URL encoded as UTF-8.
type LegacyRegistrationRequest struct {
	XSubtype LegacyRegistrationRequestXSubtype `json:"X-subtype"`
	App      LegacyRegistrationRequestApp      `json:"app"`
	Device   string                            `json:"device"`
	Sender   LegacyRegistrationRequestSender   `json:"sender"`
}

// LegacyRegistrationRequestXSubtype defines model for LegacyRegistrationRequest.XSubtype.
type LegacyRegistrationRequestXSubtype string

// LegacyRegistrationRequestApp defines model for LegacyRegistrationRequest.App.
type LegacyRegistrationRequestApp string

// LegacyRegistrationRequestSender defines model for LegacyRegistrationRequest.Sender.
type LegacyRegistrationRequestSender string

// LegacyRegistrationResponse Form-encoded response containing the registration token.
type LegacyRegistrationResponse = string

// RingPushNotificationConfig Optional Ring category in an MCS notification's android_config JSON string.
type RingPushNotificationConfig struct {
	// Category Open Ring action category, such as ding or motion.
	Category             *string                `json:"category,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingPushNotificationDevice defines model for RingPushNotificationDevice.
type RingPushNotificationDevice struct {
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingPushNotificationGCMData defines model for RingPushNotificationGCMData.
type RingPushNotificationGCMData struct {
	// Action Open Ring action name, including intercom_unlock.
	Action               *string                `json:"action,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingPushNotificationPayload Optional Ring data object carried as a JSON string in an MCS notification.
type RingPushNotificationPayload struct {
	Device               *RingPushNotificationDevice  `json:"device,omitempty"`
	GcmData              *RingPushNotificationGCMData `json:"gcmData,omitempty"`
	AdditionalProperties map[string]interface{}       `json:"-"`
}

// GoogleAPIKey defines model for GoogleAPIKey.
type GoogleAPIKey string

// JSONAccept defines model for JSONAccept.
type JSONAccept string

// JSONContentType defines model for JSONContentType.
type JSONContentType string

// ProtobufContentType defines model for ProtobufContentType.
type ProtobufContentType string

// RegisterFCMClientParams defines parameters for RegisterFCMClient.
type RegisterFCMClientParams struct {
	ContentType RegisterFCMClientParamsContentType `json:"Content-Type"`

	// Authorization Android ID and security token from the check-in response.
	Authorization string `json:"Authorization"`

	// UserAgent The pinned receiver sends an empty User-Agent value.
	UserAgent string `json:"User-Agent"`
}

// RegisterFCMClientParamsContentType defines parameters for RegisterFCMClient.
type RegisterFCMClientParamsContentType string

// CheckInFCMClientParams defines parameters for CheckInFCMClient.
type CheckInFCMClientParams struct {
	ContentType CheckInFCMClientParamsContentType `json:"Content-Type"`
}

// CheckInFCMClientParamsContentType defines parameters for CheckInFCMClient.
type CheckInFCMClientParamsContentType string

// CreateFCMInstallationParams defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParams struct {
	Accept      CreateFCMInstallationParamsAccept      `json:"Accept"`
	ContentType CreateFCMInstallationParamsContentType `json:"Content-Type"`

	// XGoogApiKey Public API key configured by the pinned Ring Android client.
	XGoogApiKey CreateFCMInstallationParamsXGoogApiKey `json:"X-Goog-Api-Key"`
}

// CreateFCMInstallationParamsAccept defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParamsAccept string

// CreateFCMInstallationParamsContentType defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParamsContentType string

// CreateFCMInstallationParamsXGoogApiKey defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParamsXGoogApiKey string

// RegisterFCMInstallationParams defines parameters for RegisterFCMInstallation.
type RegisterFCMInstallationParams struct {
	ContentType RegisterFCMInstallationParamsContentType `json:"Content-Type"`

	// XGoogApiKey Public API key configured by the pinned Ring Android client.
	XGoogApiKey RegisterFCMInstallationParamsXGoogApiKey `json:"X-Goog-Api-Key"`

	// XGoogFirebaseInstallationsAuth The local compatibility adapter removes the upstream FIS prefix before forwarding.
	XGoogFirebaseInstallationsAuth string `json:"X-Goog-Firebase-Installations-Auth"`
}

// RegisterFCMInstallationParamsContentType defines parameters for RegisterFCMInstallation.
type RegisterFCMInstallationParamsContentType string

// RegisterFCMInstallationParamsXGoogApiKey defines parameters for RegisterFCMInstallation.
type RegisterFCMInstallationParamsXGoogApiKey string

// RegisterFCMClientFormdataRequestBody defines body for RegisterFCMClient for application/x-www-form-urlencoded ContentType.
type RegisterFCMClientFormdataRequestBody = LegacyRegistrationRequest

// CreateFCMInstallationJSONRequestBody defines body for CreateFCMInstallation for application/json ContentType.
type CreateFCMInstallationJSONRequestBody = InstallationRequest

// RegisterFCMInstallationJSONRequestBody defines body for RegisterFCMInstallation for application/json ContentType.
type RegisterFCMInstallationJSONRequestBody = FCMRegistrationRequest

// Getter for additional properties for FCMRegistrationResponse. Returns the specified
// element and whether it was found
func (a FCMRegistrationResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FCMRegistrationResponse
func (a *FCMRegistrationResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FCMRegistrationResponse to handle AdditionalProperties
func (a *FCMRegistrationResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["pushSet"]; found {
		err = json.Unmarshal(raw, &a.PushSet)
		if err != nil {
			return fmt.Errorf("error reading 'pushSet': %w", err)
		}
		delete(object, "pushSet")
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &a.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
		delete(object, "token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FCMRegistrationResponse to handle AdditionalProperties
func (a FCMRegistrationResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.PushSet != nil {
		object["pushSet"], err = json.Marshal(a.PushSet)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pushSet': %w", err)
		}
	}

	object["token"], err = json.Marshal(a.Token)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for InstallationAuthToken. Returns the specified
// element and whether it was found
func (a InstallationAuthToken) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for InstallationAuthToken
func (a *InstallationAuthToken) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for InstallationAuthToken to handle AdditionalProperties
func (a *InstallationAuthToken) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["expiresIn"]; found {
		err = json.Unmarshal(raw, &a.ExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'expiresIn': %w", err)
		}
		delete(object, "expiresIn")
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &a.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
		delete(object, "token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for InstallationAuthToken to handle AdditionalProperties
func (a InstallationAuthToken) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ExpiresIn != nil {
		object["expiresIn"], err = json.Marshal(a.ExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expiresIn': %w", err)
		}
	}

	object["token"], err = json.Marshal(a.Token)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for InstallationResponse. Returns the specified
// element and whether it was found
func (a InstallationResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for InstallationResponse
func (a *InstallationResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for InstallationResponse to handle AdditionalProperties
func (a *InstallationResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["authToken"]; found {
		err = json.Unmarshal(raw, &a.AuthToken)
		if err != nil {
			return fmt.Errorf("error reading 'authToken': %w", err)
		}
		delete(object, "authToken")
	}

	if raw, found := object["fid"]; found {
		err = json.Unmarshal(raw, &a.Fid)
		if err != nil {
			return fmt.Errorf("error reading 'fid': %w", err)
		}
		delete(object, "fid")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["refreshToken"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refreshToken': %w", err)
		}
		delete(object, "refreshToken")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for InstallationResponse to handle AdditionalProperties
func (a InstallationResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["authToken"], err = json.Marshal(a.AuthToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'authToken': %w", err)
	}

	object["fid"], err = json.Marshal(a.Fid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'fid': %w", err)
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["refreshToken"], err = json.Marshal(a.RefreshToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'refreshToken': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationConfig. Returns the specified
// element and whether it was found
func (a RingPushNotificationConfig) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationConfig
func (a *RingPushNotificationConfig) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationConfig to handle AdditionalProperties
func (a *RingPushNotificationConfig) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["category"]; found {
		err = json.Unmarshal(raw, &a.Category)
		if err != nil {
			return fmt.Errorf("error reading 'category': %w", err)
		}
		delete(object, "category")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationConfig to handle AdditionalProperties
func (a RingPushNotificationConfig) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Category != nil {
		object["category"], err = json.Marshal(a.Category)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'category': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationDevice. Returns the specified
// element and whether it was found
func (a RingPushNotificationDevice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationDevice
func (a *RingPushNotificationDevice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationDevice to handle AdditionalProperties
func (a *RingPushNotificationDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationDevice to handle AdditionalProperties
func (a RingPushNotificationDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationGCMData. Returns the specified
// element and whether it was found
func (a RingPushNotificationGCMData) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationGCMData
func (a *RingPushNotificationGCMData) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationGCMData to handle AdditionalProperties
func (a *RingPushNotificationGCMData) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationGCMData to handle AdditionalProperties
func (a RingPushNotificationGCMData) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Action != nil {
		object["action"], err = json.Marshal(a.Action)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'action': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationPayload. Returns the specified
// element and whether it was found
func (a RingPushNotificationPayload) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationPayload
func (a *RingPushNotificationPayload) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationPayload to handle AdditionalProperties
func (a *RingPushNotificationPayload) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["device"]; found {
		err = json.Unmarshal(raw, &a.Device)
		if err != nil {
			return fmt.Errorf("error reading 'device': %w", err)
		}
		delete(object, "device")
	}

	if raw, found := object["gcmData"]; found {
		err = json.Unmarshal(raw, &a.GcmData)
		if err != nil {
			return fmt.Errorf("error reading 'gcmData': %w", err)
		}
		delete(object, "gcmData")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationPayload to handle AdditionalProperties
func (a RingPushNotificationPayload) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Device != nil {
		object["device"], err = json.Marshal(a.Device)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'device': %w", err)
		}
	}

	if a.GcmData != nil {
		object["gcmData"], err = json.Marshal(a.GcmData)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gcmData': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// RegisterFCMClientWithBody Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithBody(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterFCMClientWithFormdataBody Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type.
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithFormdataBody(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckInFCMClientWithBody Check in an Android or Chrome client
	//
	// Sends an Android check-in protobuf and receives assigned device credentials.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
	CheckInFCMClientWithBody(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFCMInstallationWithBody Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallationWithBody(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFCMInstallation Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallation(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterFCMInstallationWithBody Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallationWithBody(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterFCMInstallation Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallation(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// RegisterFCMClientWithBody Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *Client) RegisterFCMClientWithBody(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMClientRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterFCMClientWithFormdataBody Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes a body of the `application/x-www-form-urlencoded` content type.
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *Client) RegisterFCMClientWithFormdataBody(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMClientRequestWithFormdataBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CheckInFCMClientWithBody Check in an Android or Chrome client
//
// Sends an Android check-in protobuf and receives assigned device credentials.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
func (c *Client) CheckInFCMClientWithBody(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckInFCMClientRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateFCMInstallationWithBody Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *Client) CreateFCMInstallationWithBody(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFCMInstallationRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateFCMInstallation Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *Client) CreateFCMInstallation(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFCMInstallationRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterFCMInstallationWithBody Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *Client) RegisterFCMInstallationWithBody(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMInstallationRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RegisterFCMInstallation Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *Client) RegisterFCMInstallation(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterFCMInstallationRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRegisterFCMClientRequestWithFormdataBody calls the generic RegisterFCMClient builder with application/x-www-form-urlencoded body
func NewRegisterFCMClientRequestWithFormdataBody(server string, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewRegisterFCMClientRequestWithBody(server, params, "application/x-www-form-urlencoded", bodyReader)
}

// NewRegisterFCMClientRequestWithBody constructs an http.Request for the RegisterFCMClient method, with any body, and a specified content type
func NewRegisterFCMClientRequestWithBody(server string, params *RegisterFCMClientParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/c2dm/register3")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "User-Agent", params.UserAgent, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("User-Agent", headerParam2)

	}

	return req, nil
}

// NewCheckInFCMClientRequestWithBody constructs an http.Request for the CheckInFCMClient method, with any body, and a specified content type
func NewCheckInFCMClientRequestWithBody(server string, params *CheckInFCMClientParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/checkin")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam0)

	}

	return req, nil
}

// NewCreateFCMInstallationRequest calls the generic CreateFCMInstallation builder with application/json body
func NewCreateFCMInstallationRequest(server string, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateFCMInstallationRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateFCMInstallationRequestWithBody constructs an http.Request for the CreateFCMInstallation method, with any body, and a specified content type
func NewCreateFCMInstallationRequestWithBody(server string, params *CreateFCMInstallationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/ring-17770/installations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Accept", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "X-Goog-Api-Key", params.XGoogApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Goog-Api-Key", headerParam2)

	}

	return req, nil
}

// NewRegisterFCMInstallationRequest calls the generic RegisterFCMInstallation builder with application/json body
func NewRegisterFCMInstallationRequest(server string, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterFCMInstallationRequestWithBody(server, params, "application/json", bodyReader)
}

// NewRegisterFCMInstallationRequestWithBody constructs an http.Request for the RegisterFCMInstallation method, with any body, and a specified content type
func NewRegisterFCMInstallationRequestWithBody(server string, params *RegisterFCMInstallationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/ring-17770/registrations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Content-Type", params.ContentType, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Content-Type", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Goog-Api-Key", params.XGoogApiKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Goog-Api-Key", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "X-Goog-Firebase-Installations-Auth", params.XGoogFirebaseInstallationsAuth, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Goog-Firebase-Installations-Auth", headerParam2)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// RegisterFCMClientWithBodyWithResponse Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error)

	// RegisterFCMClientWithFormdataBodyWithResponse Register a client with legacy C2DM
	//
	// Exchanges the check-in device ID and security token for a registration token.
	//
	// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
	RegisterFCMClientWithFormdataBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error)

	// CheckInFCMClientWithBodyWithResponse Check in an Android or Chrome client
	//
	// Sends an Android check-in protobuf and receives assigned device credentials.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
	CheckInFCMClientWithBodyWithResponse(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckInFCMClientResponse, error)

	// CreateFCMInstallationWithBodyWithResponse Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallationWithBodyWithResponse(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error)

	// CreateFCMInstallationWithResponse Create a Firebase installation
	//
	// Creates an installation identity used to authorize FCM registration.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
	CreateFCMInstallationWithResponse(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error)

	// RegisterFCMInstallationWithBodyWithResponse Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallationWithBodyWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error)

	// RegisterFCMInstallationWithResponse Register a Firebase installation for FCM
	//
	// Registers Web Push encryption material and returns an FCM token.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
	RegisterFCMInstallationWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error)
}

type RegisterFCMClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r RegisterFCMClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RegisterFCMClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterFCMClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterFCMClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CheckInFCMClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CheckInFCMClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CheckInFCMClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckInFCMClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CheckInFCMClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateFCMInstallationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *InstallationResponse
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *InstallationResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateFCMInstallationResponse) GetJSON200() *InstallationResponse {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateFCMInstallationResponse) GetJSON201() *InstallationResponse {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r CreateFCMInstallationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateFCMInstallationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateFCMInstallationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateFCMInstallationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RegisterFCMInstallationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FCMRegistrationResponse
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *FCMRegistrationResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RegisterFCMInstallationResponse) GetJSON200() *FCMRegistrationResponse {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r RegisterFCMInstallationResponse) GetJSON201() *FCMRegistrationResponse {
	return r.JSON201
}

// GetBody returns the raw response body bytes
func (r RegisterFCMInstallationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RegisterFCMInstallationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterFCMInstallationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RegisterFCMInstallationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// RegisterFCMClientWithBodyWithResponse Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *ClientWithResponses) RegisterFCMClientWithBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error) {
	rsp, err := c.RegisterFCMClientWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMClientResponse(rsp)
}

// RegisterFCMClientWithFormdataBodyWithResponse Register a client with legacy C2DM
//
// Exchanges the check-in device ID and security token for a registration token.
//
// Takes a body of the `application/x-www-form-urlencoded` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /c2dm/register3 (the `RegisterFCMClient` operationId).
func (c *ClientWithResponses) RegisterFCMClientWithFormdataBodyWithResponse(ctx context.Context, params *RegisterFCMClientParams, body RegisterFCMClientFormdataRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMClientResponse, error) {
	rsp, err := c.RegisterFCMClientWithFormdataBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMClientResponse(rsp)
}

// CheckInFCMClientWithBodyWithResponse Check in an Android or Chrome client
//
// Sends an Android check-in protobuf and receives assigned device credentials.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /checkin (the `CheckInFCMClient` operationId).
func (c *ClientWithResponses) CheckInFCMClientWithBodyWithResponse(ctx context.Context, params *CheckInFCMClientParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckInFCMClientResponse, error) {
	rsp, err := c.CheckInFCMClientWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckInFCMClientResponse(rsp)
}

// CreateFCMInstallationWithBodyWithResponse Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *ClientWithResponses) CreateFCMInstallationWithBodyWithResponse(ctx context.Context, params *CreateFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error) {
	rsp, err := c.CreateFCMInstallationWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFCMInstallationResponse(rsp)
}

// CreateFCMInstallationWithResponse Create a Firebase installation
//
// Creates an installation identity used to authorize FCM registration.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/installations (the `CreateFCMInstallation` operationId).
func (c *ClientWithResponses) CreateFCMInstallationWithResponse(ctx context.Context, params *CreateFCMInstallationParams, body CreateFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFCMInstallationResponse, error) {
	rsp, err := c.CreateFCMInstallation(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFCMInstallationResponse(rsp)
}

// RegisterFCMInstallationWithBodyWithResponse Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *ClientWithResponses) RegisterFCMInstallationWithBodyWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error) {
	rsp, err := c.RegisterFCMInstallationWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMInstallationResponse(rsp)
}

// RegisterFCMInstallationWithResponse Register a Firebase installation for FCM
//
// Registers Web Push encryption material and returns an FCM token.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/projects/ring-17770/registrations (the `RegisterFCMInstallation` operationId).
func (c *ClientWithResponses) RegisterFCMInstallationWithResponse(ctx context.Context, params *RegisterFCMInstallationParams, body RegisterFCMInstallationJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterFCMInstallationResponse, error) {
	rsp, err := c.RegisterFCMInstallation(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterFCMInstallationResponse(rsp)
}

// ParseRegisterFCMClientResponse parses an HTTP response from a RegisterFCMClientWithResponse call
func ParseRegisterFCMClientResponse(rsp *http.Response) (*RegisterFCMClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterFCMClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCheckInFCMClientResponse parses an HTTP response from a CheckInFCMClientWithResponse call
func ParseCheckInFCMClientResponse(rsp *http.Response) (*CheckInFCMClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckInFCMClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCreateFCMInstallationResponse parses an HTTP response from a CreateFCMInstallationWithResponse call
func ParseCreateFCMInstallationResponse(rsp *http.Response) (*CreateFCMInstallationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateFCMInstallationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InstallationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest InstallationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseRegisterFCMInstallationResponse parses an HTTP response from a RegisterFCMInstallationWithResponse call
func ParseRegisterFCMInstallationResponse(rsp *http.Response) (*RegisterFCMInstallationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterFCMInstallationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FCMRegistrationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FCMRegistrationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}
