// Code generated by tools/protocols/generate_oapi_compat.mjs. DO NOT EDIT.

package generatedfcm

import fcmmodels "github.com/portpowered/go-ring/pkg/dependencymodels/fcm"

type AndroidCheckinRequestWire = fcmmodels.AndroidCheckinRequestWire
type AndroidCheckinResponseWire = fcmmodels.AndroidCheckinResponseWire
type CheckInFCMClientParams = fcmmodels.CheckInFCMClientParams
type CheckInFCMClientParamsContentType = fcmmodels.CheckInFCMClientParamsContentType
type CreateFCMInstallationJSONRequestBody = fcmmodels.CreateFCMInstallationJSONRequestBody
type CreateFCMInstallationParams = fcmmodels.CreateFCMInstallationParams
type CreateFCMInstallationParamsAccept = fcmmodels.CreateFCMInstallationParamsAccept
type CreateFCMInstallationParamsContentType = fcmmodels.CreateFCMInstallationParamsContentType
type CreateFCMInstallationParamsXGoogApiKey = fcmmodels.CreateFCMInstallationParamsXGoogApiKey
type FCMRegistrationRequest = fcmmodels.FCMRegistrationRequest
type FCMRegistrationResponse = fcmmodels.FCMRegistrationResponse
type FCMWebRegistration = fcmmodels.FCMWebRegistration
type GoogleAPIKey = fcmmodels.GoogleAPIKey
type InstallationAuthToken = fcmmodels.InstallationAuthToken
type InstallationRequest = fcmmodels.InstallationRequest
type InstallationRequestAppId = fcmmodels.InstallationRequestAppId
type InstallationRequestAuthVersion = fcmmodels.InstallationRequestAuthVersion
type InstallationRequestSdkVersion = fcmmodels.InstallationRequestSdkVersion
type InstallationResponse = fcmmodels.InstallationResponse
type JSONAccept = fcmmodels.JSONAccept
type JSONContentType = fcmmodels.JSONContentType
type LegacyRegistrationRequest = fcmmodels.LegacyRegistrationRequest
type LegacyRegistrationRequestApp = fcmmodels.LegacyRegistrationRequestApp
type LegacyRegistrationRequestSender = fcmmodels.LegacyRegistrationRequestSender
type LegacyRegistrationRequestXSubtype = fcmmodels.LegacyRegistrationRequestXSubtype
type LegacyRegistrationResponse = fcmmodels.LegacyRegistrationResponse
type ProtobufContentType = fcmmodels.ProtobufContentType
type RegisterFCMClientFormdataRequestBody = fcmmodels.RegisterFCMClientFormdataRequestBody
type RegisterFCMClientParams = fcmmodels.RegisterFCMClientParams
type RegisterFCMClientParamsContentType = fcmmodels.RegisterFCMClientParamsContentType
type RegisterFCMInstallationJSONRequestBody = fcmmodels.RegisterFCMInstallationJSONRequestBody
type RegisterFCMInstallationParams = fcmmodels.RegisterFCMInstallationParams
type RegisterFCMInstallationParamsContentType = fcmmodels.RegisterFCMInstallationParamsContentType
type RegisterFCMInstallationParamsXGoogApiKey = fcmmodels.RegisterFCMInstallationParamsXGoogApiKey
type RingPushNotificationConfig = fcmmodels.RingPushNotificationConfig
type RingPushNotificationDevice = fcmmodels.RingPushNotificationDevice
type RingPushNotificationEnvelope = fcmmodels.RingPushNotificationEnvelope
type RingPushNotificationEnvelopeAndroidConfig0 = fcmmodels.RingPushNotificationEnvelopeAndroidConfig0
type RingPushNotificationEnvelopeData0 = fcmmodels.RingPushNotificationEnvelopeData0
type RingPushNotificationEnvelope_AndroidConfig = fcmmodels.RingPushNotificationEnvelope_AndroidConfig
type RingPushNotificationEnvelope_Data = fcmmodels.RingPushNotificationEnvelope_Data
type RingPushNotificationGCMData = fcmmodels.RingPushNotificationGCMData
type RingPushNotificationPayload = fcmmodels.RingPushNotificationPayload

const (
	ApplicationxWwwFormUrlencoded                                                        = fcmmodels.ApplicationxWwwFormUrlencoded
	BDOU99H67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv4L2LxQcYwhqby2xGpWwzjfAnG4 = fcmmodels.BDOU99H67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv4L2LxQcYwhqby2xGpWwzjfAnG4
	CheckInFCMClientParamsContentTypeApplicationxProtobuf                                = fcmmodels.CheckInFCMClientParamsContentTypeApplicationxProtobuf
	CreateFCMInstallationParamsAcceptApplicationjson                                     = fcmmodels.CreateFCMInstallationParamsAcceptApplicationjson
	CreateFCMInstallationParamsContentTypeApplicationjson                                = fcmmodels.CreateFCMInstallationParamsContentTypeApplicationjson
	CreateFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8            = fcmmodels.CreateFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8
	FISV2                                                                                = fcmmodels.FISV2
	GoogleAPIKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8                                      = fcmmodels.GoogleAPIKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8
	InstallationRequestAppIdN1876313859327AndroidE10ec6ddb3c81f39                        = fcmmodels.InstallationRequestAppIdN1876313859327AndroidE10ec6ddb3c81f39
	JSONAcceptApplicationjson                                                            = fcmmodels.JSONAcceptApplicationjson
	JSONContentTypeApplicationjson                                                       = fcmmodels.JSONContentTypeApplicationjson
	LegacyRegistrationRequestXSubtypeN1876313859327AndroidE10ec6ddb3c81f39               = fcmmodels.LegacyRegistrationRequestXSubtypeN1876313859327AndroidE10ec6ddb3c81f39
	OrgChromiumLinux                                                                     = fcmmodels.OrgChromiumLinux
	ProtobufContentTypeApplicationxProtobuf                                              = fcmmodels.ProtobufContentTypeApplicationxProtobuf
	RegisterFCMInstallationParamsContentTypeApplicationjson                              = fcmmodels.RegisterFCMInstallationParamsContentTypeApplicationjson
	RegisterFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8          = fcmmodels.RegisterFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8
	W0617                                                                                = fcmmodels.W0617
)
