package routegate_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/portpowered/go-ring/tools/routegate"
)

func TestMCSAppDataInventoryGateRejectsMutations(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		path        string
		old         string
		replacement string
		rule        string
	}{
		{
			name:        "inventory key",
			path:        "api/external/push-protocol-inventory.yaml",
			old:         "ContentEncoding: content-encoding",
			replacement: "ContentEncoding: content-type",
			rule:        "invalid-mcs-socket-contract",
		},
		{
			name:        "inventory value",
			path:        "api/external/push-protocol-inventory.yaml",
			old:         "ContentEncodingAES128GCM: aes128gcm",
			replacement: "ContentEncodingAES128GCM: other",
			rule:        "invalid-mcs-socket-contract",
		},
		{
			name:        "generated key constant",
			path:        "internal/protocol/mcs.gen.go",
			old:         `MCSAppDataContentEncodingKey       = "content-encoding"`,
			replacement: `MCSAppDataContentEncodingKey       = "content-type"`,
			rule:        "unbound-mcs-protocol-constants",
		},
		{
			name:        "generated value constant",
			path:        "internal/protocol/mcs.gen.go",
			old:         `MCSAppDataContentEncodingAES128GCM = "aes128gcm"`,
			replacement: `MCSAppDataContentEncodingAES128GCM = "other"`,
			rule:        "unbound-mcs-protocol-constants",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			root := mcsInventoryFixture(t)
			mutateMCSInventoryFile(t, root, test.path, test.old, test.replacement)

			findings, err := routegate.Audit(root)
			if err != nil {
				t.Fatal(err)
			}

			for _, finding := range findings {
				if finding.Rule == test.rule {
					return
				}
			}

			t.Fatalf("expected %s finding, got: %+v", test.rule, findings)
		})
	}
}

func mcsInventoryFixture(t *testing.T) string {
	t.Helper()

	root := t.TempDir()
	writeMCSInventoryFile(t, root, "go.mod", "module example.com/routegatefixture\n\ngo 1.24.0\n")
	writeMCSInventoryFile(t, root, "api/openapi.yaml", `openapi: 3.1.0
info: {title: routegate fixture, version: 0.1.0}
servers: [{url: https://api.example.test}]
paths:
  /widgets/{widget_id}:
    get:
      operationId: getWidget
      parameters:
        - {name: widget_id, in: path, required: true, schema: {type: string}}
      responses: {'200': {description: ok}}
`)
	writeMCSInventoryFile(t, root, "generatedhttp/client.gen.go", `// Code generated by fixture. DO NOT EDIT.
package generatedhttp

import "net/http"

func NewGetWidgetRequest(server string, widgetID string) (*http.Request, error) {
	return http.NewRequest(http.MethodGet, server+"/widgets/"+widgetID, nil)
}

// Corresponds with GET /widgets/{widget_id} (the getWidget operationId)
func (c *Client) GetWidget() {}

type Client struct{}
`)
	writeMCSInventoryFile(t, root, "api/asyncapi.yaml", `asyncapi: 2.6.0
info: {title: routegate fixture, version: 0.1.0}
servers: {}
channels: {}
operations: {}
components:
  messages: {}
  schemas: {}
`)
	writeMCSInventoryFile(t, root, "internal/protocol/endpoints.go", "package protocol\n")
	writeMCSInventoryFile(t, root, "client.go", "package client\n")

	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}

	repositoryRoot := filepath.Clean(filepath.Join(workingDirectory, "..", ".."))

	for _, relative := range []string{
		"api/external/push-protocol-inventory.yaml",
		"internal/protocol/mcs.gen.go",
		"third_party/go-push-receiver/fcm.go",
		"third_party/go-push-receiver/constants.go",
		"third_party/go-push-receiver/tag.go",
	} {
		// #nosec G304 -- relative is selected from this fixed source-file list.
		contents, readErr := os.ReadFile(filepath.Join(repositoryRoot, filepath.FromSlash(relative)))
		if readErr != nil {
			t.Fatal(readErr)
		}

		writeMCSInventoryFile(t, root, relative, string(contents))
	}

	return root
}

func mutateMCSInventoryFile(t *testing.T, root, relative, old, replacement string) {
	t.Helper()

	path := filepath.Join(root, filepath.FromSlash(relative))
	// #nosec G304 -- paths are fixed test cases rooted under t.TempDir.
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	updated := strings.Replace(string(contents), old, replacement, 1)
	if updated == string(contents) {
		t.Fatalf("fixture mutation target %q was not found in %s", old, relative)
	}

	writeMCSInventoryFile(t, root, relative, updated)
}

func writeMCSInventoryFile(t *testing.T, root, relative, contents string) {
	t.Helper()

	path := filepath.Join(root, filepath.FromSlash(relative))

	err := os.MkdirAll(filepath.Dir(path), 0o700)
	if err != nil {
		t.Fatal(err)
	}

	err = os.WriteFile(path, []byte(contents), 0o600)
	if err != nil {
		t.Fatal(err)
	}
}
