package routegate

import (
	"go/ast"
	"go/token"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
)

const unregisteredWireModelRule = "unregistered-wire-model"
const generatedSignalingExtraNameCount = 6
const wireModelInventoryDiagnostic = "JSON wire structs in schema-owned packages must come from the canonical " +
	"schema model or a schema-checked adapter"

// auditWireModelSource checks schema-owned Go packages even when a declaration
// is unused. Generated status is accepted only for the repository's declared
// generator output paths; a copied header cannot exempt a handwritten model.
func auditWireModelSource(root string, files []*parsedGoFile) []Finding {
	var findings []Finding

	asyncModelNames, err := asyncSchemaModelNames(root)
	if err != nil {
		return []Finding{{Path: "api/asyncapi.yaml", Line: 0, Rule: "wire-model-inventory", Message: err.Error()}}
	}

	for _, file := range files {
		if !wireModelSourcePackage(file.path) {
			continue
		}

		if generatedRESTModelOutput(root, file.path, file.file.Comments) {
			findings = append(findings, auditGeneratedRESTModelNames(root, file)...)

			continue
		}

		if generatedOpenAPIModelOutput(root, file.path, file.file.Comments) {
			findings = append(findings, auditGeneratedOpenAPIModelNames(root, file)...)

			continue
		}

		if generatedWireModelOutput(root, file.path, file.file.Comments) {
			if signalingModelOutput(root, file.path) {
				findings = append(findings, auditGeneratedSignalingModelNames(root, file, asyncModelNames)...)
			}

			continue
		}

		findings = append(findings, auditHandwrittenWireModelFile(root, file)...)
	}

	return findings
}

func generatedRESTModelOutput(root, path string, comments []*ast.CommentGroup) bool {
	relative := "/" + filepath.ToSlash(relativePath(root, path))
	if !strings.HasPrefix(relative, "/pkg/dependencymodels/rest/") || !strings.HasSuffix(relative, ".gen.go") {
		return false
	}

	group := strings.TrimSuffix(filepath.Base(relative), ".gen.go")
	if !schemaResponsibilityGroupExists(root, group) {
		return false
	}

	var marker strings.Builder
	for _, comment := range comments {
		marker.WriteString(comment.Text())
	}

	text := marker.String()

	return strings.Contains(text, "Code generated by github.com/oapi-codegen/oapi-codegen") &&
		strings.Contains(text, "Responsibility group: "+group+".")
}

func auditGeneratedRESTModelNames(root string, file *parsedGoFile) []Finding {
	schemaOwners, operationOwners, err := restGeneratedModelOwners(root)
	if err != nil {
		return []Finding{{
			Path: "api/openapi.yaml", Line: 0, Rule: "wire-model-inventory", Message: err.Error(),
		}}
	}

	group := strings.TrimSuffix(filepath.Base(file.path), ".gen.go")

	var findings []Finding

	for _, declaration := range file.file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}

		for _, specification := range general.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structure, ok := typeSpec.Type.(*ast.StructType)
			if !ok || !hasJSONWireFields(structure) {
				continue
			}

			comment := declarationCommentText(typeSpec.Doc, general.Doc)
			if !restGeneratedTypeOwned(typeSpec.Name.Name, group, comment, schemaOwners, operationOwners) {
				findings = append(findings, Finding{
					Path: relativePath(root, file.path), Line: file.fileSet.Position(typeSpec.Pos()).Line,
					Rule:    unregisteredWireModelRule,
					Message: "generated REST JSON model has no matching responsibility component or operation owner",
				})
			}

			ast.Inspect(structure, func(node ast.Node) bool {
				nested, ok := node.(*ast.StructType)
				if !ok || nested == structure || !hasJSONWireFields(nested) {
					return true
				}

				findings = append(findings, Finding{
					Path: relativePath(root, file.path), Line: file.fileSet.Position(nested.Pos()).Line,
					Rule:    unregisteredWireModelRule,
					Message: "anonymous generated REST JSON object has no named schema component owner",
				})

				return true
			})
		}
	}

	return findings
}

func restGeneratedModelOwners(root string) (map[string]string, map[string]string, error) {
	schemaOwners := make(map[string]string)

	groups, err := filepath.Glob(filepath.Join(root, "api", "schemas", "*.yaml"))
	if err != nil {
		return nil, nil, wrapRouteGateError(err, "list REST responsibility schemas")
	}

	for _, path := range groups {
		group := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))

		var document map[string]any

		err = readYAML(path, &document)
		if err != nil {
			return nil, nil, wrapRouteGateError(err, "read REST responsibility schema %s", path)
		}

		for name := range stringMap(stringMap(document["components"])["schemas"]) {
			schemaOwners[name] = group
		}
	}

	var document map[string]any

	err = readYAML(filepath.Join(root, "api", "openapi.yaml"), &document)
	if err != nil {
		return nil, nil, err
	}

	operationOwners := make(map[string]string)

	for _, pathItem := range stringMap(document["paths"]) {
		for method, operationValue := range stringMap(pathItem) {
			if !isHTTPMethod(method) {
				continue
			}

			operation := stringMap(operationValue)
			tags, _ := operation["tags"].([]any)

			operationID := stringValue(operation["operationId"])

			if operationID != "" && len(tags) == 1 {
				operationOwners[exportedOperationName(operationID)] = responsibilityTagSlug(stringValue(tags[0]))
			}
		}
	}

	return schemaOwners, operationOwners, nil
}

func restGeneratedTypeOwned(
	name, fileGroup, comment string,
	schemaOwners, operationOwners map[string]string,
) bool {
	if schemaOwners[name] == fileGroup {
		return true
	}

	for _, ownerKind := range []string{"model for", "parameters for", "body for"} {
		prefix := "defines " + ownerKind + " "

		index := strings.Index(comment, prefix)
		if index < 0 {
			continue
		}

		owner := strings.Fields(comment[index+len(prefix):])
		if len(owner) == 0 {
			return false
		}

		ownerPath := strings.TrimSuffix(owner[0], ".")

		target, _, _ := strings.Cut(ownerPath, ".")
		if ownerKind == "model for" {
			ownerGroup, exists := schemaOwners[target]
			expectedType := strings.ReplaceAll(ownerPath, ".", "_")

			if !exists || name != expectedType {
				return false
			}

			return ownerGroup == fileGroup
		}

		ownerGroup, exists := operationOwners[target]
		if !exists || ownerGroup != fileGroup {
			return false
		}

		operationType := exportedOperationName(target)
		if ownerKind == "parameters for" {
			return name == operationType+"Params"
		}

		return name == operationType+"JSONRequestBody" || name == operationType+"FormdataRequestBody"
	}

	return false
}

func declarationCommentText(specDoc, declDoc *ast.CommentGroup) string {
	if specDoc != nil {
		return specDoc.Text()
	}

	if declDoc != nil {
		return declDoc.Text()
	}

	return ""
}

func schemaResponsibilityGroupExists(root, group string) bool {
	if group == "" {
		return false
	}

	groups, err := filepath.Glob(filepath.Join(root, "api", "schemas", group+".yaml"))

	return err == nil && len(groups) == 1
}

func responsibilityTagSlug(tag string) string {
	return strings.ReplaceAll(strings.ToLower(tag), " ", "-")
}

func exportedOperationName(name string) string {
	if name == "" {
		return ""
	}

	return strings.ToUpper(name[:1]) + name[1:]
}

func auditHandwrittenWireModelFile(root string, file *parsedGoFile) []Finding {
	var findings []Finding

	for _, declaration := range file.file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}

		for _, specification := range general.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structure, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			ast.Inspect(structure, func(node ast.Node) bool {
				nested, ok := node.(*ast.StructType)
				if !ok || !hasJSONWireFields(nested) {
					return true
				}

				findings = append(findings, Finding{
					Path: relativePath(root, file.path), Line: file.fileSet.Position(nested.Pos()).Line,
					Rule: unregisteredWireModelRule, Message: wireModelInventoryDiagnostic,
				})

				return true
			})
		}
	}

	return findings
}

func auditGeneratedSignalingModelNames(
	root string,
	file *parsedGoFile,
	expected map[string]bool,
) []Finding {
	var findings []Finding

	for _, declaration := range file.file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}

		for _, specification := range general.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structure, ok := typeSpec.Type.(*ast.StructType)
			if !ok || !hasJSONWireFields(structure) || expected[typeSpec.Name.Name] {
				continue
			}

			findings = append(findings, Finding{
				Path: relativePath(root, file.path), Line: file.fileSet.Position(typeSpec.Pos()).Line,
				Rule:    unregisteredWireModelRule,
				Message: "generated signaling JSON model has no component or anonymous schema owner",
			})
		}
	}

	return findings
}

func asyncSchemaModelNames(root string) (map[string]bool, error) {
	var document map[string]any

	err := readYAML(filepath.Join(root, "api", "asyncapi.yaml"), &document)
	if err != nil {
		return nil, err
	}

	components := stringMap(stringMap(document["components"])["schemas"])

	names := make(map[string]bool, len(components)+generatedSignalingExtraNameCount)

	for component := range components {
		names[modelinaGoName(component)] = true
	}

	for _, name := range []string{
		"AnonymousSchema_1", "AnonymousSchema_82", "AnonymousSchema_91", "AnonymousSchema_199",
		"PTzCommand", "SessionStreamOptions",
	} {
		names[name] = true
	}

	return names, nil
}

func signalingModelOutput(root, path string) bool {
	return filepath.ToSlash(relativePath(root, path)) != "" &&
		strings.HasPrefix("/"+filepath.ToSlash(relativePath(root, path)), "/pkg/dependencymodels/signaling/")
}

func wireModelSourcePackage(path string) bool {
	path = "/" + filepath.ToSlash(path)

	for _, prefix := range []string{
		"/pkg/dependencies/",
		"/pkg/dependencymodels/",
		"/pkg/ringapimodels/",
		"/internal/signaling/",
	} {
		if strings.Contains(path, prefix) {
			return true
		}
	}

	return false
}

func generatedWireModelOutput(root, path string, comments []*ast.CommentGroup) bool {
	relative := "/" + filepath.ToSlash(relativePath(root, path))

	var marker strings.Builder

	for _, comment := range comments {
		marker.WriteString(comment.Text())
	}

	markerText := marker.String()

	if strings.HasPrefix(relative, "/pkg/dependencymodels/signaling/") &&
		strings.HasSuffix(relative, ".go") {
		return strings.Contains(markerText, "Code generated by @asyncapi/modelina.")
	}

	for _, generatedDirectory := range []string{
		"/internal/generatedhttp/",
		"/pkg/generatedhttp/",
		"/internal/generatedfcm/",
		"/pkg/generatedfcm/",
	} {
		if strings.Contains(relative, generatedDirectory) &&
			strings.HasSuffix(relative, "client.gen.go") {
			return strings.Contains(markerText, "Code generated by github.com/oapi-codegen/oapi-codegen")
		}
	}

	return false
}

func generatedOpenAPIModelOutput(root, path string, comments []*ast.CommentGroup) bool {
	relative := "/" + filepath.ToSlash(relativePath(root, path))
	modelPaths := []string{
		"/pkg/dependencymodels/fcm/models.gen.go",
		"/pkg/ringapimodels/models.gen.go",
	}

	if !slices.Contains(modelPaths, relative) {
		return false
	}

	var marker strings.Builder

	for _, comment := range comments {
		marker.WriteString(comment.Text())
	}

	return strings.Contains(marker.String(), "Code generated by github.com/oapi-codegen/oapi-codegen")
}

func auditGeneratedOpenAPIModelNames(root string, file *parsedGoFile) []Finding {
	relative := filepath.ToSlash(relativePath(root, file.path))
	schemaPath := "api/external/fcm.openapi.yaml"

	if relative == "pkg/ringapimodels/models.gen.go" {
		schemaPath = "api/client-models.openapi.yaml"
	}

	var document map[string]any

	err := readYAML(filepath.Join(root, schemaPath), &document)
	if err != nil {
		return []Finding{{
			Path: schemaPath, Line: 0, Rule: "wire-model-inventory",
			Message: wrapRouteGateError(err, "read generated OpenAPI model schema").Error(),
		}}
	}

	components := stringMap(stringMap(document["components"])["schemas"])
	operationIDs := openAPIGeneratedOperationIDs(document)

	var findings []Finding

	for _, declaration := range file.file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}

		for _, specification := range general.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structure, ok := typeSpec.Type.(*ast.StructType)
			if !ok || !hasJSONWireFields(structure) {
				continue
			}

			comment := declarationCommentText(typeSpec.Doc, general.Doc)
			if !openAPIGeneratedTypeOwned(typeSpec.Name.Name, comment, components, operationIDs) {
				findings = append(findings, Finding{
					Path: relativePath(root, file.path), Line: file.fileSet.Position(typeSpec.Pos()).Line,
					Rule:    unregisteredWireModelRule,
					Message: "generated OpenAPI JSON model has no matching schema component owner",
				})
			}

			ast.Inspect(structure, func(node ast.Node) bool {
				nested, ok := node.(*ast.StructType)
				if !ok || nested == structure || !hasJSONWireFields(nested) {
					return true
				}

				findings = append(findings, Finding{
					Path: relativePath(root, file.path), Line: file.fileSet.Position(nested.Pos()).Line,
					Rule:    unregisteredWireModelRule,
					Message: "anonymous generated OpenAPI JSON object has no named schema component owner",
				})

				return true
			})
		}
	}

	return findings
}

func openAPIGeneratedOperationIDs(document map[string]any) map[string]bool {
	operationIDs := make(map[string]bool)

	for _, pathItem := range stringMap(document["paths"]) {
		for method, operationValue := range stringMap(pathItem) {
			if !isHTTPMethod(method) {
				continue
			}

			operationID := exportedOperationName(stringValue(stringMap(operationValue)["operationId"]))
			if operationID != "" {
				operationIDs[operationID] = true
			}
		}
	}

	return operationIDs
}

func openAPIGeneratedTypeOwned(
	name, comment string,
	components map[string]any,
	operationIDs map[string]bool,
) bool {
	if _, registered := components[name]; registered {
		return true
	}

	for _, kind := range []string{"model", "parameters", "body"} {
		prefix := "defines " + kind + " for "

		index := strings.Index(comment, prefix)
		if index < 0 {
			continue
		}

		ownerParts := strings.Fields(comment[index+len(prefix):])
		if len(ownerParts) == 0 {
			return false
		}

		owner := strings.TrimSuffix(ownerParts[0], ".")

		switch kind {
		case "model":
			component, _, _ := strings.Cut(owner, ".")
			if _, registered := components[component]; !registered {
				return false
			}

			return name == generatedNestedOpenAPITypeName(owner)
		case "parameters":
			operation := exportedOperationName(owner)

			return operationIDs[operation] &&
				(name == operation+"Params" || strings.HasPrefix(name, operation+"Params"))
		case "body":
			operation := exportedOperationName(owner)

			return operationIDs[operation] &&
				(name == operation+"JSONRequestBody" || name == operation+"FormdataRequestBody")
		}
	}

	return false
}

func generatedNestedOpenAPITypeName(owner string) string {
	name := strings.ReplaceAll(owner, ".", "_")
	for _, digit := range []string{"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"} {
		name = strings.ReplaceAll(name, "_"+digit, digit)
	}

	return name
}

func hasJSONWireFields(structure *ast.StructType) bool {
	for _, field := range structure.Fields.List {
		if field.Tag == nil {
			continue
		}

		tag, ok := stringConstant(field.Tag)
		if !ok {
			continue
		}

		name, tagged := reflect.StructTag(tag).Lookup("json")

		name, _, _ = strings.Cut(name, ",")
		if tagged && name != "-" {
			return true
		}
	}

	return false
}
