package routegate_test

import (
	"context"
	"os/exec"
	"strings"
	"testing"

	"github.com/portpowered/go-ring/tools/routegate"
)

const requestBodyBackingRule = "generated-request-body-backing-mutation"

//nolint:paralleltest // t.Chdir reproduces the routegate command's default root (GO-15).
func TestDefaultRoutegateRejectsForgedModelAndRequestBodyBackingMutation(t *testing.T) {
	root := requestBodyFixtureWithReader(
		t, "bodyAlias := body", "body[2] = 'x'", "bytes.NewReader(bodyAlias)",
	)
	writeFixtureFile(t, root, "pkg/dependencies/rest/blind_probe.gen.go",
		`// Code generated by github.com/oapi-codegen/oapi-codegen. DO NOT EDIT.
package rest
type BlindProbeWire struct {
	Payload struct {
		Value string `+"`json:\"value\"`"+`
	} `+"`json:\"payload\"`"+`
}
`)
	writeFixtureFile(t, root, "api/schemas/authentication.yaml", `components:
  schemas:
    OAuthTokenGrant: {type: object}
`)
	writeFixtureFile(t, root, "pkg/dependencymodels/rest/authentication.gen.go",
		`// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: authentication.
package rest
type BlindGeneratedProbe struct {
	Payload struct { Value string `+"`json:\"value\"`"+` } `+"`json:\"payload\"`"+`
}
`)
	writeFixtureFile(t, root, "api/external/fcm.openapi.yaml", `components:
  schemas:
    RegisteredFCM: {type: object}
`)
	writeFixtureFile(t, root, "pkg/dependencymodels/fcm/models.gen.go",
		`// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fcm
type CounterfeitGeneratedFCM struct {
	Value string `+"`json:\"value\"`"+`
}
`)
	assertRequestFixtureCompiles(t, root)
	t.Chdir(root)

	output, err := exec.CommandContext(context.Background(), "go", "run", "./tools/routegate/cmd").CombinedOutput()
	if err == nil {
		t.Fatalf("default routegate command accepted unregistered model and mutated request backing bytes:\n%s", output)
	}

	for _, rule := range []string{unregisteredWireModelRuleForTest, requestBodyBackingRule} {
		if !strings.Contains(string(output), rule) {
			t.Errorf("default routegate command omitted %s finding: %v\n%s", rule, err, output)
		}
	}

	if !strings.Contains(string(output), "pkg/dependencymodels/fcm/models.gen.go") {
		t.Errorf("default routegate command omitted forged FCM model location:\n%s", output)
	}
}

//nolint:paralleltest // t.Chdir verifies the default root argument (GO-15).
func TestCallerBodyAndOriginalBytesReaderRemainSafe(t *testing.T) {
	root := requestBodyFixture(t, "", `if len(body) > 0 { _ = body[0] }`)
	assertRequestFixtureCompiles(t, root)

	t.Chdir(root)

	findings, err := routegate.Audit(".")
	if err != nil {
		t.Fatal(err)
	}

	for _, finding := range findings {
		if finding.Rule == requestBodyBackingRule {
			t.Fatalf("read-only bytes.Reader use was rejected: %s", finding)
		}
	}
}

func TestBodyMutationBeforeRequestConstructionRemainsSafe(t *testing.T) {
	t.Parallel()

	root := requestBodyFixture(t, `body[2] = 'x'`, "")
	assertRequestFixtureCompiles(t, root)

	findings, err := routegate.Audit(root)
	if err != nil {
		t.Fatal(err)
	}

	for _, finding := range findings {
		if finding.Rule == requestBodyBackingRule {
			t.Fatalf("body finalized before construction was rejected: %s", finding)
		}
	}
}

func TestRequestBodyFromUnresolvedFactoryIsRejected(t *testing.T) {
	t.Parallel()

	root := requestBodyFixtureWithReader(t, "", "", "makeBodyReader(body)")
	assertRequestFixtureCompiles(t, root)

	findings, err := routegate.Audit(root)
	if err != nil {
		t.Fatal(err)
	}

	for _, finding := range findings {
		if finding.Rule == requestBodyBackingRule {
			return
		}
	}

	t.Fatal("generated request accepted a body reader whose helper provenance is unresolved")
}

const unregisteredWireModelRuleForTest = "unregistered-wire-model"

func requestBodyFixture(t *testing.T, beforeConstruction, afterConstruction string) string {
	t.Helper()

	return requestBodyFixtureWithReader(t, beforeConstruction, afterConstruction, "bytes.NewReader(body)")
}

func requestBodyFixtureWithReader(
	t *testing.T,
	beforeConstruction, afterConstruction, bodyExpression string,
) string {
	t.Helper()

	root := fixtureRoot(t, strings.ReplaceAll(generatedRequestSource,
		`routes "example.com/routegatefixture/generatedhttp"`,
		`routes "github.com/portpowered/go-ring/generatedhttp"`,
	))
	writeFixtureFile(t, root, "go.mod", `module github.com/portpowered/go-ring

go 1.24.0

require gopkg.in/yaml.v3 v3.0.1
`)

	writeFixtureFile(t, root, "api/openapi.yaml", `openapi: 3.1.0
info: {title: routegate body fixture, version: 0.1.0}
servers: [{url: https://api.example.test}]
paths:
  /widgets/{widget_id}:
    get:
      operationId: getWidget
      parameters:
        - {name: widget_id, in: path, required: true, schema: {type: string}}
      responses: {'200': {description: ok}}
  /unlock:
    put:
      operationId: unlockIntercom
      requestBody:
        required: true
        content:
          application/json:
            schema: {type: string}
      responses: {'200': {description: ok}}
`)
	writeFixtureFile(t, root, "generatedhttp/client.gen.go", `// Code generated by fixture. DO NOT EDIT.
package generatedhttp

import (
	"io"
	"net/http"
)

type Client struct{}

func NewGetWidgetRequest(server string, widgetID string) (*http.Request, error) {
	return http.NewRequest(http.MethodGet, server+"/widgets/"+widgetID, nil)
}

func NewUnlockIntercomRequestWithBody(server string, body io.Reader) (*http.Request, error) {
	return http.NewRequest(http.MethodPut, server+"/unlock", body)
}

// Corresponds with GET /widgets/{widget_id} (the `+"`getWidget`"+` operationId)
func (c *Client) GetWidget() {}

// Corresponds with PUT /unlock (the `+"`unlockIntercom`"+` operationId)
func (c *Client) UnlockIntercom() {}
`)

	source := strings.ReplaceAll(generatedRequestSource,
		`routes "example.com/routegatefixture/generatedhttp"`,
		`routes "github.com/portpowered/go-ring/generatedhttp"`,
	)
	source = strings.Replace(source, `"context"`, `"bytes"
	"context"`, 1)
	before := ""

	if beforeConstruction != "" {
		before = beforeConstruction + "\n\t"
	}

	after := ""

	if afterConstruction != "" {
		after = afterConstruction + "\n\t"
	}

	source += `
func (c *API) UnlockIntercomBody(ctx context.Context, body []byte) error {
	` + before + `reader := bytes.NewReader(body)
	req, err := routes.NewUnlockIntercomRequestWithBody("https://api.example.test", reader)
	if err != nil { return err }
	` + after + `return c.doGeneratedJSON(ctx, req)
}
`
	source = strings.Replace(source, "reader := bytes.NewReader(body)", "reader := "+bodyExpression, 1)
	source += `
func makeBodyReader(body []byte) *bytes.Reader { return bytes.NewReader(body) }
`

	writeFixtureFile(t, root, "client.go", source)
	copyRoutegateCommand(t, root)

	return root
}
