package routegate_test

import (
	"strings"
	"testing"

	"github.com/portpowered/go-ring/tools/routegate"
)

//nolint:paralleltest // t.Chdir must run serially to reproduce the CLI's default relative root (GO-15).
func TestSignalingSourceInventoryAuditsDefaultRelativeRoot(t *testing.T) {
	root := fixtureRoot(t, "package sample\n")
	writeFixtureFile(t, root, "pkg/dependencies/websocket/sibling.go", "package websocket\n"+
		"type UnregisteredSiblingFrame struct { Payload string `json:\"unregistered_payload\"` }\n"+
		"func siblingProperties() map[string]any { return map[string]any{\"unregistered_key\": true} }\n")
	assertRequestFixtureCompiles(t, root)
	t.Chdir(root)

	findings, err := routegate.Audit(".")
	if err != nil {
		t.Fatal(err)
	}

	rules := make([]string, 0, len(findings))

	for _, finding := range findings {
		rules = append(rules, finding.Rule)
	}

	for _, required := range []string{"handwritten-signaling-wire-key", "handwritten-signaling-wire-model"} {
		if !strings.Contains(strings.Join(rules, "\n"), required) {
			t.Fatalf("default relative root missed %s: %v", required, findings)
		}
	}
}

func TestSignalingSourceInventoryIncludesEverySiblingFile(t *testing.T) {
	t.Parallel()

	root := fixtureRoot(t, "package sample\n")
	writeFixtureFile(t, root, "pkg/dependencies/websocket/client.go", `package websocket
import "encoding/json"
func encodeCallerPayload(key string, value any) ([]byte, error) {
	return json.Marshal(siblingProperties(key, value))
}
`)

	helper := `package websocket
func siblingProperties(key string, value any) (result map[string]any) {
	result = map[string]any{key: value}
	return
}
`
	writeFixtureFile(t, root, "pkg/dependencies/websocket/sibling.go", helper)
	assertRequestFixtureCompiles(t, root)

	if findings := audit(t, root); len(findings) != 0 {
		t.Fatalf("caller-defined open keys rejected:\n%s", strings.Join(findings, "\n"))
	}

	mutated := strings.Replace(helper, "map[string]any{key: value}",
		`map[string]any{key: value, "unregistered_sibling_key": "library-value"}`, 1)
	mutated = "// Code generated by forged marker. DO NOT EDIT.\n" + mutated +
		"\ntype UnregisteredSiblingFrame struct { Payload string `json:\"unregistered_payload\"` }\n"
	writeFixtureFile(t, root, "pkg/dependencies/websocket/sibling.go", mutated)
	assertRequestFixtureCompiles(t, root)

	findings := audit(t, root)
	for _, rule := range []string{"handwritten-signaling-wire-key", "handwritten-signaling-wire-model"} {
		if !hasRule(findings, rule) {
			t.Fatalf("sibling file was not diagnosed by %s:\n%s", rule, strings.Join(findings, "\n"))
		}
	}
}
