package routegate_test

import (
	"strings"
	"testing"

	"github.com/portpowered/go-ring/tools/routegate"
)

//nolint:paralleltest // t.Chdir must run serially to reproduce the CLI's default relative root (GO-15).
func TestSignalingSourceInventoryAuditsDefaultRelativeRoot(t *testing.T) {
	root := fixtureRoot(t, "package sample\n")
	writeFixtureFile(t, root, "pkg/dependencies/websocket/sibling.go", "package websocket\n"+
		"type UnregisteredSiblingFrame struct { Payload string `json:\"unregistered_payload\"` }\n"+
		"func siblingProperties() map[string]any { return map[string]any{\"unregistered_key\": true} }\n")
	assertRequestFixtureCompiles(t, root)
	t.Chdir(root)

	findings, err := routegate.Audit(".")
	if err != nil {
		t.Fatal(err)
	}

	rules := make([]string, 0, len(findings))

	for _, finding := range findings {
		rules = append(rules, finding.Rule)
	}

	for _, required := range []string{"handwritten-signaling-wire-key", "handwritten-signaling-wire-model"} {
		if !strings.Contains(strings.Join(rules, "\n"), required) {
			t.Fatalf("default relative root missed %s: %v", required, findings)
		}
	}
}

func TestSignalingSourceInventoryIncludesEverySiblingFile(t *testing.T) {
	t.Parallel()

	root := fixtureRoot(t, "package sample\n")
	writeFixtureFile(t, root, "pkg/dependencies/websocket/client.go", `package websocket
import "encoding/json"
func EncodeCallerPayload(key string, value any) ([]byte, error) {
	return json.Marshal(siblingProperties(key, value))
}
`)

	helper := `package websocket
func siblingProperties(key string, value any) (result map[string]any) {
	result = map[string]any{key: value}
	return
}
`
	writeFixtureFile(t, root, "pkg/dependencies/websocket/sibling.go", helper)
	assertRequestFixtureCompiles(t, root)

	if findings := audit(t, root); len(findings) != 0 {
		t.Fatalf("caller-defined open keys rejected:\n%s", strings.Join(findings, "\n"))
	}

	mutated := strings.Replace(helper, "package websocket\n", `package websocket
const siblingKeyAlias = "unregistered_sibling_key"
func siblingFixedKey() (result string) {
	local := siblingKeyAlias
	result = siblingKeyValue(local)
	return
}
func siblingKeyValue(value string) (key string) {
	key = value
	return
}
`, 1)
	mutated = strings.Replace(mutated, "map[string]any{key: value}",
		"map[string]any{key: value, siblingFixedKey(): \"library-value\"}", 1)
	mutated = "// Code generated by forged marker. DO NOT EDIT.\n" + mutated +
		"\ntype UnregisteredSiblingFrame struct { Payload string `json:\"unregistered_payload\"` }\n"
	writeFixtureFile(t, root, "pkg/dependencies/websocket/sibling.go", mutated)
	assertRequestFixtureCompiles(t, root)

	findings := audit(t, root)
	for _, rule := range []string{"handwritten-signaling-wire-key", "handwritten-signaling-wire-model"} {
		if !hasRule(findings, rule) {
			t.Fatalf("sibling file was not diagnosed by %s:\n%s", rule, strings.Join(findings, "\n"))
		}
	}
}

func TestSignalingMapHelperUsesActualCallsiteProvenance(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name            string
		includeFixedKey bool
		wantFinding     bool
	}{
		{
			name:            "exported caller forwarding",
			includeFixedKey: false,
			wantFinding:     false,
		},
		{
			name:            "library fixed key",
			includeFixedKey: true,
			wantFinding:     true,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			root := fixtureRoot(t, "package sample\n")

			client := `package websocket
import "encoding/json"
func EncodePayload(key string, value any) ([]byte, error) {
	return json.Marshal(siblingProperties(key, value))
}
`
			if test.includeFixedKey {
				client += `func encodeLibraryPayload(value any) ([]byte, error) {
	return json.Marshal(siblingProperties("unregistered_library_key", value))
}
`
			}

			writeFixtureFile(t, root, "pkg/dependencies/websocket/client.go", client)
			writeFixtureFile(t, root, "pkg/dependencies/websocket/sibling.go", `package websocket
func siblingProperties(key string, value any) map[string]any {
	return map[string]any{key: value}
}
`)
			assertRequestFixtureCompiles(t, root)

			findings := audit(t, root)

			found := hasRule(findings, "handwritten-signaling-wire-key")

			if found != test.wantFinding {
				t.Fatalf(
					"map-helper callsite finding = %t, want %t:\n%s",
					found,
					test.wantFinding,
					strings.Join(findings, "\n"),
				)
			}
		})
	}
}
