// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
)

// RingDevice defines model for RingDevice.
type RingDevice struct {
	Address     string `json:"address,omitempty"`
	Description string `json:"description,omitempty"`

	// Family Known legacy device families; unknown families remain valid.
	Family   string `json:"family,omitempty"`
	HasLight bool   `json:"has_light,omitempty"`

	// Health Known legacy health fields; unrecognized hardware fields stay extensible.
	Health *RingDeviceHealth `json:"health,omitempty"`
	ID     int64             `json:"id"`

	// Kind Known hardware kinds include these captured and Python legacy examples; unknown kinds remain valid.
	Kind                   string `json:"kind,omitempty"`
	LightBrightness        *int   `json:"light_brightness,omitempty"`
	MotionDetectionEnabled bool   `json:"motion_detection_enabled,omitempty"`
	Name                   string `json:"name,omitempty"`
	Owned                  *bool  `json:"owned,omitempty"`
	TimeZone               string `json:"time_zone,omitempty"`
	Timezone               string `json:"timezone,omitempty"`

	// Volume Legacy device volume range accepted by the Go client.
	Volume             int    `json:"volume,omitempty"`
	WifiName           string `json:"wifi_name,omitempty"`
	WifiSignalStrength int    `json:"wifi_signal_strength,omitempty"`
}

// RingDeviceHealth Known legacy health fields; unrecognized hardware fields stay extensible.
type RingDeviceHealth struct {
	BatteryLevel         *int                   `json:"battery_level,omitempty"`
	BatteryStatus        *string                `json:"battery_status,omitempty"`
	FirmwareVersion      *string                `json:"firmware_version,omitempty"`
	LastUpdate           *string                `json:"last_update,omitempty"`
	SignalStrength       *int                   `json:"signal_strength,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingDevicesResponse Devices grouped by the adapter after decoding the raw list.
type RingDevicesResponse struct {
	AuthorizedDoorbots []RingDevice `json:"authorized_doorbots"`
	Chimes             []RingDevice `json:"chimes"`
	Doorbots           []RingDevice `json:"doorbots"`
	Other              []RingDevice `json:"other"`
	StickupCams        []RingDevice `json:"stickup_cams"`
}

// RingDoorbot defines model for RingDoorbot.
type RingDoorbot struct {
	Description string `json:"description,omitempty"`
	ID          int64  `json:"id"`
	Type        string `json:"type,omitempty"`
}

// RingRecording defines model for RingRecording.
type RingRecording struct {
	Answered  bool        `json:"answered,omitempty"`
	CreatedAt string      `json:"created_at,omitempty"`
	DeviceID  int64       `json:"-"`
	Doorbot   RingDoorbot `json:"doorbot"`
	ID        int64       `json:"id"`

	// Kind Known recording kinds are ding, motion and on_demand; unknown kinds remain valid.
	Kind string `json:"kind,omitempty"`
}

// RingRecordingHistoryResponse Adapter result; the HTTP response itself is an array.
type RingRecordingHistoryResponse struct {
	Recordings []RingRecording `json:"recordings"`
}

// RingRecordingURLResponse defines model for RingRecordingURLResponse.
type RingRecordingURLResponse struct {
	URL string `json:"url"`
}

// Getter for additional properties for RingDeviceHealth. Returns the specified
// element and whether it was found
func (a RingDeviceHealth) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingDeviceHealth
func (a *RingDeviceHealth) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingDeviceHealth to handle AdditionalProperties
func (a *RingDeviceHealth) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["battery_level"]; found {
		err = json.Unmarshal(raw, &a.BatteryLevel)
		if err != nil {
			return fmt.Errorf("error reading 'battery_level': %w", err)
		}
		delete(object, "battery_level")
	}

	if raw, found := object["battery_status"]; found {
		err = json.Unmarshal(raw, &a.BatteryStatus)
		if err != nil {
			return fmt.Errorf("error reading 'battery_status': %w", err)
		}
		delete(object, "battery_status")
	}

	if raw, found := object["firmware_version"]; found {
		err = json.Unmarshal(raw, &a.FirmwareVersion)
		if err != nil {
			return fmt.Errorf("error reading 'firmware_version': %w", err)
		}
		delete(object, "firmware_version")
	}

	if raw, found := object["last_update"]; found {
		err = json.Unmarshal(raw, &a.LastUpdate)
		if err != nil {
			return fmt.Errorf("error reading 'last_update': %w", err)
		}
		delete(object, "last_update")
	}

	if raw, found := object["signal_strength"]; found {
		err = json.Unmarshal(raw, &a.SignalStrength)
		if err != nil {
			return fmt.Errorf("error reading 'signal_strength': %w", err)
		}
		delete(object, "signal_strength")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingDeviceHealth to handle AdditionalProperties
func (a RingDeviceHealth) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BatteryLevel != nil {
		object["battery_level"], err = json.Marshal(a.BatteryLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'battery_level': %w", err)
		}
	}

	if a.BatteryStatus != nil {
		object["battery_status"], err = json.Marshal(a.BatteryStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'battery_status': %w", err)
		}
	}

	if a.FirmwareVersion != nil {
		object["firmware_version"], err = json.Marshal(a.FirmwareVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'firmware_version': %w", err)
		}
	}

	if a.LastUpdate != nil {
		object["last_update"], err = json.Marshal(a.LastUpdate)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_update': %w", err)
		}
	}

	if a.SignalStrength != nil {
		object["signal_strength"], err = json.Marshal(a.SignalStrength)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'signal_strength': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
