package main

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBundleOpenAPI_MergesOwnedComponentsAndNormalizesSiblingRefs(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	basePath := filepath.Join(root, "openapi.base.yaml")
	fragmentsDir := filepath.Join(root, "schemas")
	outputPath := filepath.Join(root, "openapi.yaml")

	err := os.MkdirAll(fragmentsDir, 0o750)
	if err != nil {
		t.Fatal(err)
	}

	writeFixture(t, basePath, `openapi: 3.1.0
info: {title: Fixture, version: 1.0.0}
components:
  securitySchemes:
    bearer: {type: http, scheme: bearer}
paths:
  /items:
    get:
      operationId: listItems
      tags: [Items]
      requestBody:
        content:
          application/json:
            schema: {$ref: './schemas/items.yaml#/components/schemas/ItemList'}
      responses:
        '200': {description: OK}
`)
	writeFixture(t, filepath.Join(fragmentsDir, "common.yaml"), `components:
  schemas:
    JsonValue: {description: Open JSON value}
`)
	writeFixture(t, filepath.Join(fragmentsDir, "items.yaml"), `components:
  schemas:
    ItemList:
      type: object
      properties:
        metadata: {$ref: './common.yaml#/components/schemas/JsonValue'}
`)

	err = bundleOpenAPI(basePath, fragmentsDir, outputPath)
	if err != nil {
		t.Fatal(err)
	}

	assembled, err := readLocalFile(outputPath)
	if err != nil {
		t.Fatal(err)
	}

	text := string(assembled)
	if !strings.Contains(text, "metadata: {$ref: '#/components/schemas/JsonValue'}") {
		t.Fatalf("bundle did not normalize the sibling ref:\n%s", text)
	}

	if !strings.Contains(text, "schema: {$ref: '#/components/schemas/ItemList'}") {
		t.Fatalf("bundle did not normalize the base-to-fragment ref:\n%s", text)
	}

	if !strings.Contains(text, "securitySchemes:") || !strings.Contains(text, "operationId: listItems") {
		t.Fatalf("bundle did not preserve base security schemes and paths:\n%s", text)
	}
}

func TestBundleOpenAPI_RejectsDuplicateComponentOwners(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	basePath := filepath.Join(root, "openapi.base.yaml")

	fragmentsDir := filepath.Join(root, "schemas")

	err := os.MkdirAll(fragmentsDir, 0o750)
	if err != nil {
		t.Fatal(err)
	}

	writeFixture(t, basePath, `openapi: 3.1.0
info: {title: Fixture, version: 1.0.0}
components:
  securitySchemes: {bearer: {type: http, scheme: bearer}}
paths: {}
`)

	for _, group := range []string{"devices", "cameras"} {
		writeFixture(t, filepath.Join(fragmentsDir, group+".yaml"), `components:
  schemas:
    Shared: {type: object}
`)
	}

	err = bundleOpenAPI(basePath, fragmentsDir, filepath.Join(root, "openapi.yaml"))
	if err == nil || !strings.Contains(err.Error(), "is owned by both") {
		t.Fatalf("expected duplicate component owner error, got %v", err)
	}
}

func TestSplitModels_GroupsGeneratedTypesBySchemaAndOperation(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	apiDir := filepath.Join(root, "api")
	fragmentsDir := filepath.Join(apiDir, "schemas")
	outputDir := filepath.Join(root, "rest")
	modelPath := filepath.Join(outputDir, "models.gen.go")

	err := os.MkdirAll(fragmentsDir, 0o750)
	if err != nil {
		t.Fatal(err)
	}

	err = os.MkdirAll(outputDir, 0o750)
	if err != nil {
		t.Fatal(err)
	}

	writeFixture(t, filepath.Join(fragmentsDir, "common.yaml"), `components:
  schemas:
    Demo: {type: object}
`)
	writeFixture(t, filepath.Join(fragmentsDir, "devices.yaml"), `components:
  schemas:
    Device: {type: object}
`)

	openAPIPath := filepath.Join(apiDir, "openapi.yaml")
	writeFixture(t, openAPIPath, `openapi: 3.1.0
paths:
  /devices:
    get:
      operationId: getDevice
      tags: [Devices]
      responses: {'200': {description: OK}}
`)
	writeFixture(t, modelPath, `// Package rest provides generated models.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package rest

import "encoding/json"

type Demo struct { Name string }

func (d Demo) MarshalJSON() ([]byte, error) {
	type alias Demo
	return json.Marshal(alias(d))
}

type GetDeviceResponseObject struct { ID int64 }
`)

	err = splitModels(openAPIPath, modelPath, outputDir)
	if err != nil {
		t.Fatal(err)
	}

	common, err := readLocalFile(filepath.Join(outputDir, "common.gen.go"))
	if err != nil {
		t.Fatal(err)
	}

	devices, err := readLocalFile(filepath.Join(outputDir, "devices.gen.go"))
	if err != nil {
		t.Fatal(err)
	}

	packagePreserved := strings.Contains(string(common), "package rest")
	typePreserved := strings.Contains(string(common), "type Demo struct")
	importPreserved := strings.Contains(string(common), `"encoding/json"`)

	methodPreserved := strings.Contains(string(common), "func (d Demo) MarshalJSON")

	if !packagePreserved || !typePreserved || !importPreserved || !methodPreserved {
		t.Fatalf("common group did not preserve model identity, methods, and used imports:\n%s", common)
	}

	devicePackagePreserved := strings.Contains(string(devices), "package rest")
	responseTypePreserved := strings.Contains(string(devices), "type GetDeviceResponseObject struct")

	unusedImportRemoved := !strings.Contains(string(devices), `"encoding/json"`)

	if !devicePackagePreserved || !responseTypePreserved || !unusedImportRemoved {
		t.Fatalf("operation group has unexpected declarations or imports:\n%s", devices)
	}

	_, err = os.Stat(modelPath)
	if !os.IsNotExist(err) {
		t.Fatalf("superseded monolithic model file still exists (stat err: %v)", err)
	}
}

func TestErrorfPreservesCause(t *testing.T) {
	t.Parallel()

	cause := &contextualError{message: "sentinel", cause: nil}

	err := errorf("schema operation failed: %w", cause)

	if !errors.Is(err, cause) {
		t.Fatalf("error %v does not preserve its cause", err)
	}

	if got, want := err.Error(), "schema operation failed: sentinel"; got != want {
		t.Fatalf("error text = %q, want %q", got, want)
	}
}

func writeFixture(t *testing.T, path, content string) {
	t.Helper()

	err := os.WriteFile(path, []byte(content), 0o600)
	if err != nil {
		t.Fatal(err)
	}
}
