// Command generateapi emits the wire client and signaling contracts from the
// checked-in OpenAPI and AsyncAPI files. It has no handwritten operation list.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type operation struct {
	OperationID string `yaml:"operationId"`
	Servers     []struct {
		URL string `yaml:"url"`
	} `yaml:"servers"`
}
type openAPI struct {
	Paths map[string]map[string]operation `yaml:"paths"`
}
type asyncAPI struct {
	Components struct {
		Schemas map[string]struct {
			Properties map[string]struct {
				Enum []string `yaml:"enum"`
			} `yaml:"properties"`
		} `yaml:"schemas"`
	} `yaml:"components"`
}
type route struct{ Name, ID, Method, Path, Server string }

func main() {
	openPath := flag.String("openapi", "../../api/openapi.yaml", "OpenAPI source")
	asyncPath := flag.String("asyncapi", "../../api/asyncapi.yaml", "AsyncAPI source")
	outPath := flag.String("out", "contracts.gen.go", "generated Go file")
	flag.Parse()
	var httpSpec openAPI
	readYAML(*openPath, &httpSpec)
	var socketSpec asyncAPI
	readYAML(*asyncPath, &socketSpec)
	var routes []route
	seen := map[string]bool{}
	for path, methods := range httpSpec.Paths {
		for method, op := range methods {
			method = strings.ToUpper(method)
			if method != "GET" && method != "POST" && method != "PUT" && method != "PATCH" && method != "DELETE" && method != "HEAD" {
				continue
			}
			if op.OperationID == "" {
				panic("HTTP operation lacks operationId: " + method + " " + path)
			}
			if seen[op.OperationID] {
				panic("duplicate operationId: " + op.OperationID)
			}
			seen[op.OperationID] = true
			r := route{Name: exported(op.OperationID), ID: op.OperationID, Method: method, Path: path}
			if len(op.Servers) > 0 {
				r.Server = op.Servers[0].URL
			}
			routes = append(routes, r)
		}
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].ID < routes[j].ID })
	clientMethods := socketSpec.Components.Schemas["ClientEnvelope"].Properties["method"].Enum
	serverMethods := socketSpec.Components.Schemas["ServerEnvelope"].Properties["method"].Enum
	if len(routes) == 0 || len(clientMethods) == 0 || len(serverMethods) == 0 {
		panic("schema has no operations or message methods")
	}
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by go generate ./pkg/generatedapi; DO NOT EDIT.\npackage generatedapi")
	fmt.Fprintln(&b, `import ("context"; "encoding/json"; "fmt"; "io"; "net/http"; "net/url"; "regexp"; "strings")`)
	fmt.Fprintln(&b, "type HTTPOperation string\ntype HTTPRoute struct { Method, Path, Server string }")
	fmt.Fprintln(&b, "const (")
	for _, r := range routes {
		fmt.Fprintf(&b, "Operation%s HTTPOperation = %q\n", r.Name, r.ID)
	}
	fmt.Fprintln(&b, ")\nvar HTTPRoutes = map[HTTPOperation]HTTPRoute{")
	for _, r := range routes {
		fmt.Fprintf(&b, "Operation%s: {Method:%q,Path:%q,Server:%q},\n", r.Name, r.Method, r.Path, r.Server)
	}
	fmt.Fprintln(&b, "}\nvar pathParam = regexp.MustCompile(`\\{([^}]+)\\}`)")
	b.WriteString(`func BuildPath(op HTTPOperation, params map[string]string)(string,error){ route,ok:=HTTPRoutes[op]; if !ok{return "",fmt.Errorf("unknown HTTP operation %q",op)}; var missing string; path:=pathParam.ReplaceAllStringFunc(route.Path,func(part string)string{key:=strings.TrimSuffix(strings.TrimPrefix(part,"{"),"}");value,ok:=params[key];if !ok||value==""{missing=key;return part};return url.PathEscape(value)});if missing!=""{return "",fmt.Errorf("missing path parameter %s",missing)};return path,nil }` + "\n")
	fmt.Fprintln(&b, `type HTTPRequest struct { PathParams map[string]string; Query url.Values; Headers http.Header; Body io.Reader }`)
	fmt.Fprintln(&b, `type HTTPClient interface { CallHTTP(context.Context, HTTPOperation, HTTPRequest)(*http.Response,error) }`)
	fmt.Fprintln(&b, `type ClientMethod string; type ServerMethod string`)
	fmt.Fprintln(&b, "const (")
	for _, method := range clientMethods {
		fmt.Fprintf(&b, "Client%s ClientMethod = %q\n", exported(method), method)
	}
	for _, method := range serverMethods {
		fmt.Fprintf(&b, "Server%s ServerMethod = %q\n", exported(method), method)
	}
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b, `type ClientEnvelope struct { Method ClientMethod `+"`json:\"method\"`"+`; DialogID string `+"`json:\"dialog_id\"`"+`; RIID string `+"`json:\"riid,omitempty\"`"+`; Body json.RawMessage `+"`json:\"body\"`"+` }`)
	fmt.Fprintln(&b, `type ServerEnvelope struct { Method ServerMethod `+"`json:\"method\"`"+`; DialogID string `+"`json:\"dialog_id\"`"+`; RIID string `+"`json:\"riid,omitempty\"`"+`; Body json.RawMessage `+"`json:\"body\"`"+` }`)
	fmt.Fprintln(&b, `type WebSocketClient interface { SendMessage(context.Context, ClientEnvelope) error; ReceiveMessage(context.Context)(ServerEnvelope,error) }`)
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		panic(fmt.Sprintf("format generated code: %v\n%s", err, b.String()))
	}
	if err := os.WriteFile(*outPath, formatted, 0644); err != nil {
		panic(err)
	}
}
func readYAML(path string, out any) {
	b, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	if err := yaml.Unmarshal(b, out); err != nil {
		panic(err)
	}
}
func exported(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' || r == '-' || r == '.' || r == '/' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
