// Code generated by tools/protocols/generate_signaling.mjs. DO NOT EDIT.

package generatedsignaling

import signalingmodels "github.com/portpowered/go-ring/pkg/dependencymodels/signaling"

type AccountEventFrame = signalingmodels.AccountEventFrame

type AnonymousSchema_1 = signalingmodels.AnonymousSchema_1

type AnonymousSchema_199 = signalingmodels.AnonymousSchema_199

type AnonymousSchema_82 = signalingmodels.AnonymousSchema_82

type AnonymousSchema_91 = signalingmodels.AnonymousSchema_91

type IceCandidateBody = signalingmodels.IceCandidateBody

type IceCandidateFrame = signalingmodels.IceCandidateFrame

type LiveAnswerBody = signalingmodels.LiveAnswerBody

type LiveAnswerFrame = signalingmodels.LiveAnswerFrame

type LiveAnswerInfo = signalingmodels.LiveAnswerInfo

type LiveIceBody = signalingmodels.LiveIceBody

type LiveIceFrame = signalingmodels.LiveIceFrame

type LiveStreamOptions = signalingmodels.LiveStreamOptions

type LiveViewBody = signalingmodels.LiveViewBody

type LiveViewFrame = signalingmodels.LiveViewFrame

type PTzCommand = signalingmodels.PTzCommand

type PlaybackAnswerBody = signalingmodels.PlaybackAnswerBody

type PlaybackAnswerFrame = signalingmodels.PlaybackAnswerFrame

type PlaybackCloseBody = signalingmodels.PlaybackCloseBody

type PlaybackCloseFrame = signalingmodels.PlaybackCloseFrame

type PlaybackCloseReason = signalingmodels.PlaybackCloseReason

type PlaybackOfferBody = signalingmodels.PlaybackOfferBody

type PlaybackOfferFrame = signalingmodels.PlaybackOfferFrame

type PlaybackSessionInfo = signalingmodels.PlaybackSessionInfo

type PtzCommandBody = signalingmodels.PtzCommandBody

type PtzCommandFrame = signalingmodels.PtzCommandFrame

type PtzCommandMethod = signalingmodels.PtzCommandMethod

type PtzContinuousCommandBody = signalingmodels.PtzContinuousCommandBody

type PtzContinuousCommandFrame = signalingmodels.PtzContinuousCommandFrame

type PtzContinuousParams = signalingmodels.PtzContinuousParams

type PtzContinuousWireCommand = signalingmodels.PtzContinuousWireCommand

type PtzDirection = signalingmodels.PtzDirection

type PtzWireCommand = signalingmodels.PtzWireCommand

type PtzWireParams = signalingmodels.PtzWireParams

type PushEventBody = signalingmodels.PushEventBody

type PushEventFrame = signalingmodels.PushEventFrame

type PushEventPayload = signalingmodels.PushEventPayload

type PushFilter = signalingmodels.PushFilter

type PushFilters = signalingmodels.PushFilters

type PushHeartbeatFrame = signalingmodels.PushHeartbeatFrame

type PushSubscribeBody = signalingmodels.PushSubscribeBody

type PushSubscribeFrame = signalingmodels.PushSubscribeFrame

type PushSubscriptionAckBody = signalingmodels.PushSubscriptionAckBody

type PushSubscriptionAckFrame = signalingmodels.PushSubscriptionAckFrame

type PushSubscriptionBody = signalingmodels.PushSubscriptionBody

type PushUnsubscribeFrame = signalingmodels.PushUnsubscribeFrame

type RpcCommandWrapper = signalingmodels.RpcCommandWrapper

type RpcErrorValue = signalingmodels.RpcErrorValue

type RpcResultValue = signalingmodels.RpcResultValue

type ServerCameraStartedFrame = signalingmodels.ServerCameraStartedFrame

type ServerCloseBody = signalingmodels.ServerCloseBody

type ServerCloseFrame = signalingmodels.ServerCloseFrame

type ServerCloseReason = signalingmodels.ServerCloseReason

type ServerEnvelope = signalingmodels.ServerEnvelope

type ServerIceBody = signalingmodels.ServerIceBody

type ServerIceFrame = signalingmodels.ServerIceFrame

type ServerRpcBody = signalingmodels.ServerRpcBody

type ServerRpcCommand = signalingmodels.ServerRpcCommand

type ServerRpcFrame = signalingmodels.ServerRpcFrame

type SessionActivateFrame = signalingmodels.SessionActivateFrame

type SessionBody = signalingmodels.SessionBody

type SessionCloseFrame = signalingmodels.SessionCloseFrame

type SessionCreatedBody = signalingmodels.SessionCreatedBody

type SessionCreatedFrame = signalingmodels.SessionCreatedFrame

type SessionMicrophoneBody = signalingmodels.SessionMicrophoneBody

type SessionMicrophoneFrame = signalingmodels.SessionMicrophoneFrame

type SessionNotificationBody = signalingmodels.SessionNotificationBody

type SessionNotificationFrame = signalingmodels.SessionNotificationFrame

type SessionPingFrame = signalingmodels.SessionPingFrame

type SessionPongFrame = signalingmodels.SessionPongFrame

type SessionStreamAudioOptionsBody = signalingmodels.SessionStreamAudioOptionsBody

type SessionStreamAudioOptionsFrame = signalingmodels.SessionStreamAudioOptionsFrame

type SessionStreamAudioVideoOptionsBody = signalingmodels.SessionStreamAudioVideoOptionsBody

type SessionStreamAudioVideoOptionsFrame = signalingmodels.SessionStreamAudioVideoOptionsFrame

type SessionStreamOptions = signalingmodels.SessionStreamOptions

type SessionStreamVideoOptionsBody = signalingmodels.SessionStreamVideoOptionsBody

type SessionStreamVideoOptionsFrame = signalingmodels.SessionStreamVideoOptionsFrame

type SignalingInboundDiscriminator = signalingmodels.SignalingInboundDiscriminator

const (
	AnonymousSchema_199PtzDotPanDotContinuous  = signalingmodels.AnonymousSchema_199PtzDotPanDotContinuous
	AnonymousSchema_199PtzDotTiltDotContinuous = signalingmodels.AnonymousSchema_199PtzDotTiltDotContinuous
	AnonymousSchema_1ActivateSession           = signalingmodels.AnonymousSchema_1ActivateSession
	AnonymousSchema_1CameraOptions             = signalingmodels.AnonymousSchema_1CameraOptions
	AnonymousSchema_1CameraStarted             = signalingmodels.AnonymousSchema_1CameraStarted
	AnonymousSchema_1Close                     = signalingmodels.AnonymousSchema_1Close
	AnonymousSchema_1Ice                       = signalingmodels.AnonymousSchema_1Ice
	AnonymousSchema_1LiveView                  = signalingmodels.AnonymousSchema_1LiveView
	AnonymousSchema_1MicEnable                 = signalingmodels.AnonymousSchema_1MicEnable
	AnonymousSchema_1Notification              = signalingmodels.AnonymousSchema_1Notification
	AnonymousSchema_1Ping                      = signalingmodels.AnonymousSchema_1Ping
	AnonymousSchema_1Playback                  = signalingmodels.AnonymousSchema_1Playback
	AnonymousSchema_1Pong                      = signalingmodels.AnonymousSchema_1Pong
	AnonymousSchema_1PushEvent                 = signalingmodels.AnonymousSchema_1PushEvent
	AnonymousSchema_1PushHeartbeat             = signalingmodels.AnonymousSchema_1PushHeartbeat
	AnonymousSchema_1PushSubscribe             = signalingmodels.AnonymousSchema_1PushSubscribe
	AnonymousSchema_1PushSubscriptionAck       = signalingmodels.AnonymousSchema_1PushSubscriptionAck
	AnonymousSchema_1PushUnsubscribe           = signalingmodels.AnonymousSchema_1PushUnsubscribe
	AnonymousSchema_1Rpc                       = signalingmodels.AnonymousSchema_1Rpc
	AnonymousSchema_1Sdp                       = signalingmodels.AnonymousSchema_1Sdp
	AnonymousSchema_1SessionCreated            = signalingmodels.AnonymousSchema_1SessionCreated
	AnonymousSchema_1StreamOptions             = signalingmodels.AnonymousSchema_1StreamOptions
	PtzCommandMethodPtzDotPanDotContinuous     = signalingmodels.PtzCommandMethodPtzDotPanDotContinuous
	PtzCommandMethodPtzDotPanDotStep           = signalingmodels.PtzCommandMethodPtzDotPanDotStep
	PtzCommandMethodPtzDotTiltDotContinuous    = signalingmodels.PtzCommandMethodPtzDotTiltDotContinuous
	PtzCommandMethodPtzDotTiltDotStep          = signalingmodels.PtzCommandMethodPtzDotTiltDotStep
	PtzDirectionDown                           = signalingmodels.PtzDirectionDown
	PtzDirectionLeft                           = signalingmodels.PtzDirectionLeft
	PtzDirectionRight                          = signalingmodels.PtzDirectionRight
	PtzDirectionUp                             = signalingmodels.PtzDirectionUp
)

var (
	AnonymousSchema_199Values   = signalingmodels.AnonymousSchema_199Values
	AnonymousSchema_1Values     = signalingmodels.AnonymousSchema_1Values
	PtzCommandMethodValues      = signalingmodels.PtzCommandMethodValues
	PtzDirectionValues          = signalingmodels.PtzDirectionValues
	ValuesToAnonymousSchema_1   = signalingmodels.ValuesToAnonymousSchema_1
	ValuesToAnonymousSchema_199 = signalingmodels.ValuesToAnonymousSchema_199
	ValuesToPtzCommandMethod    = signalingmodels.ValuesToPtzCommandMethod
	ValuesToPtzDirection        = signalingmodels.ValuesToPtzDirection
)
