// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type PtzContinuousWireCommand struct {
	Jsonrpc              string                 `json:"jsonrpc" binding:"required"`
	Id                   string                 `json:"id" binding:"required"`
	Method               *AnonymousSchema_197   `json:"method" binding:"required"`
	Params               *PtzContinuousParams   `json:"params" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
