// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type PtzContinuousCommandFrame struct {
	Method               string                    `json:"method" binding:"required"`
	DialogId             string                    `json:"dialog_id" binding:"required"`
	Riid                 string                    `json:"riid,omitempty"`
	Body                 *PtzContinuousCommandBody `json:"body" binding:"required"`
	AdditionalProperties map[string]interface{}    `json:"-,omitempty"`
}
