// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type PushSubscribeBody struct {
	RequestedNotifications []PushFilter           `json:"requested_notifications" binding:"required"`
	AdditionalProperties   map[string]interface{} `json:"-,omitempty"`
}
