// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type ServerRpcCommand struct {
	Jsonrpc              string                 `json:"jsonrpc" binding:"required"`
	Id                   string                 `json:"id" binding:"required"`
	Result               *RpcResultValue        `json:"result,omitempty"`
	Error                *RpcErrorValue         `json:"error,omitempty"`
	Method               string                 `json:"method,omitempty"`
	Params               map[string]interface{} `json:"params,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
