// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type ServerRpcBody struct {
	DoorbotId            int                    `json:"doorbot_id,omitempty"`
	SessionId            string                 `json:"session_id,omitempty"`
	Command              *ServerRpcCommand      `json:"command" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
