// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type ServerIceBody struct {
	DoorbotId            int                    `json:"doorbot_id,omitempty"`
	SessionId            string                 `json:"session_id,omitempty"`
	UserId               int                    `json:"user_id,omitempty"`
	Ice                  string                 `json:"ice" binding:"required"`
	Mid                  string                 `json:"mid,omitempty"`
	Mlineindex           int                    `json:"mlineindex" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
