// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type SessionStreamOptions struct {
	SessionStreamAudioOptionsFrame      `json:"-"`
	SessionStreamVideoOptionsFrame      `json:"-"`
	SessionStreamAudioVideoOptionsFrame `json:"-"`
}
