// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type AccountEventFrame struct {
	Kind                 string                 `json:"kind,omitempty"`
	DeviceId             int                    `json:"device_id,omitempty"`
	Timestamp            string                 `json:"timestamp,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
