// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

import (
	"encoding/json"
)

type AnonymousSchema_1 uint

const (
	AnonymousSchema_1ActivateSession AnonymousSchema_1 = iota
	AnonymousSchema_1CameraOptions
	AnonymousSchema_1CameraStarted
	AnonymousSchema_1Close
	AnonymousSchema_1Ice
	AnonymousSchema_1LiveView
	AnonymousSchema_1MicEnable
	AnonymousSchema_1Notification
	AnonymousSchema_1Ping
	AnonymousSchema_1Playback
	AnonymousSchema_1Pong
	AnonymousSchema_1PushEvent
	AnonymousSchema_1PushHeartbeat
	AnonymousSchema_1PushSubscribe
	AnonymousSchema_1PushSubscriptionAck
	AnonymousSchema_1PushUnsubscribe
	AnonymousSchema_1Rpc
	AnonymousSchema_1Sdp
	AnonymousSchema_1SessionCreated
	AnonymousSchema_1StreamOptions
)

// Value returns the value of the enum.
func (op AnonymousSchema_1) Value() any {
	if op >= AnonymousSchema_1(len(AnonymousSchema_1Values)) {
		return nil
	}
	return AnonymousSchema_1Values[op]
}

var AnonymousSchema_1Values = []any{"activate_session", "camera_options", "camera_started", "close", "ice", "live_view", "mic_enable", "notification", "ping", "playback", "pong", "push_event", "push_heartbeat", "push_subscribe", "push_subscription_ack", "push_unsubscribe", "rpc", "sdp", "session_created", "stream_options"}
var ValuesToAnonymousSchema_1 = map[any]AnonymousSchema_1{
	AnonymousSchema_1Values[AnonymousSchema_1ActivateSession]:     AnonymousSchema_1ActivateSession,
	AnonymousSchema_1Values[AnonymousSchema_1CameraOptions]:       AnonymousSchema_1CameraOptions,
	AnonymousSchema_1Values[AnonymousSchema_1CameraStarted]:       AnonymousSchema_1CameraStarted,
	AnonymousSchema_1Values[AnonymousSchema_1Close]:               AnonymousSchema_1Close,
	AnonymousSchema_1Values[AnonymousSchema_1Ice]:                 AnonymousSchema_1Ice,
	AnonymousSchema_1Values[AnonymousSchema_1LiveView]:            AnonymousSchema_1LiveView,
	AnonymousSchema_1Values[AnonymousSchema_1MicEnable]:           AnonymousSchema_1MicEnable,
	AnonymousSchema_1Values[AnonymousSchema_1Notification]:        AnonymousSchema_1Notification,
	AnonymousSchema_1Values[AnonymousSchema_1Ping]:                AnonymousSchema_1Ping,
	AnonymousSchema_1Values[AnonymousSchema_1Playback]:            AnonymousSchema_1Playback,
	AnonymousSchema_1Values[AnonymousSchema_1Pong]:                AnonymousSchema_1Pong,
	AnonymousSchema_1Values[AnonymousSchema_1PushEvent]:           AnonymousSchema_1PushEvent,
	AnonymousSchema_1Values[AnonymousSchema_1PushHeartbeat]:       AnonymousSchema_1PushHeartbeat,
	AnonymousSchema_1Values[AnonymousSchema_1PushSubscribe]:       AnonymousSchema_1PushSubscribe,
	AnonymousSchema_1Values[AnonymousSchema_1PushSubscriptionAck]: AnonymousSchema_1PushSubscriptionAck,
	AnonymousSchema_1Values[AnonymousSchema_1PushUnsubscribe]:     AnonymousSchema_1PushUnsubscribe,
	AnonymousSchema_1Values[AnonymousSchema_1Rpc]:                 AnonymousSchema_1Rpc,
	AnonymousSchema_1Values[AnonymousSchema_1Sdp]:                 AnonymousSchema_1Sdp,
	AnonymousSchema_1Values[AnonymousSchema_1SessionCreated]:      AnonymousSchema_1SessionCreated,
	AnonymousSchema_1Values[AnonymousSchema_1StreamOptions]:       AnonymousSchema_1StreamOptions,
}

func (op *AnonymousSchema_1) UnmarshalJSON(raw []byte) error {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return err
	}
	*op = ValuesToAnonymousSchema_1[v]
	return nil
}

func (op AnonymousSchema_1) MarshalJSON() ([]byte, error) {
	return json.Marshal(op.Value())
}
