// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

import (
	"encoding/json"
)

type AnonymousSchema_199 uint

const (
	AnonymousSchema_199PtzDotPanDotContinuous AnonymousSchema_199 = iota
	AnonymousSchema_199PtzDotTiltDotContinuous
)

// Value returns the value of the enum.
func (op AnonymousSchema_199) Value() any {
	if op >= AnonymousSchema_199(len(AnonymousSchema_199Values)) {
		return nil
	}
	return AnonymousSchema_199Values[op]
}

var AnonymousSchema_199Values = []any{"PTZ.Pan.Continuous", "PTZ.Tilt.Continuous"}
var ValuesToAnonymousSchema_199 = map[any]AnonymousSchema_199{
	AnonymousSchema_199Values[AnonymousSchema_199PtzDotPanDotContinuous]:  AnonymousSchema_199PtzDotPanDotContinuous,
	AnonymousSchema_199Values[AnonymousSchema_199PtzDotTiltDotContinuous]: AnonymousSchema_199PtzDotTiltDotContinuous,
}

func (op *AnonymousSchema_199) UnmarshalJSON(raw []byte) error {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return err
	}
	*op = ValuesToAnonymousSchema_199[v]
	return nil
}

func (op AnonymousSchema_199) MarshalJSON() ([]byte, error) {
	return json.Marshal(op.Value())
}
