// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type LiveStreamOptions struct {
	AudioEnabled         bool                   `json:"audio_enabled,omitempty"`
	VideoEnabled         bool                   `json:"video_enabled,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
