// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type LiveAnswerInfo struct {
	SessionId            string                 `json:"session_id" binding:"required"`
	PingInterval         int                    `json:"ping_interval,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
