// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type PlaybackCloseBody struct {
	DoorbotId            int                    `json:"doorbot_id" binding:"required"`
	SessionId            string                 `json:"session_id" binding:"required"`
	Reason               *PlaybackCloseReason   `json:"reason" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
