// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type PlaybackSessionInfo struct {
	PingInterval         int                    `json:"ping_interval,omitempty"`
	Region               string                 `json:"region,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
