// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type PushFilters struct {
	DoorbotIds           []int                  `json:"doorbot_ids,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
