// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type RpcCommandWrapper struct {
	Message              map[string]interface{} `json:"message" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
