// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type RpcErrorValue struct {
	Code                 int                    `json:"code" binding:"required"`
	Message              string                 `json:"message" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
