// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type ServerCloseBody struct {
	DoorbotId            int                    `json:"doorbot_id,omitempty"`
	SessionId            string                 `json:"session_id,omitempty"`
	Reason               *ServerCloseReason     `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
