// Code generated by @asyncapi/modelina. DO NOT EDIT.

package signaling

type SessionStreamAudioVideoOptionsFrame struct {
	Method               string                              `json:"method" binding:"required"`
	DialogId             string                              `json:"dialog_id" binding:"required"`
	Riid                 string                              `json:"riid,omitempty"`
	Body                 *SessionStreamAudioVideoOptionsBody `json:"body" binding:"required"`
	AdditionalProperties map[string]interface{}              `json:"-,omitempty"`
}
