// Package fcm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fcm

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InstallationRequestAppId.
const (
	InstallationRequestAppIdN1876313859327AndroidE10ec6ddb3c81f39 InstallationRequestAppId = "1:876313859327:android:e10ec6ddb3c81f39"
)

// Valid indicates whether the value is a known member of the InstallationRequestAppId enum.
func (e InstallationRequestAppId) Valid() bool {
	switch e {
	case InstallationRequestAppIdN1876313859327AndroidE10ec6ddb3c81f39:
		return true
	default:
		return false
	}
}

// Defines values for InstallationRequestAuthVersion.
const (
	FISV2 InstallationRequestAuthVersion = "FIS_v2"
)

// Valid indicates whether the value is a known member of the InstallationRequestAuthVersion enum.
func (e InstallationRequestAuthVersion) Valid() bool {
	switch e {
	case FISV2:
		return true
	default:
		return false
	}
}

// Defines values for InstallationRequestSdkVersion.
const (
	W0617 InstallationRequestSdkVersion = "w:0.6.17"
)

// Valid indicates whether the value is a known member of the InstallationRequestSdkVersion enum.
func (e InstallationRequestSdkVersion) Valid() bool {
	switch e {
	case W0617:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRegistrationRequestXSubtype.
const (
	LegacyRegistrationRequestXSubtypeN1876313859327AndroidE10ec6ddb3c81f39 LegacyRegistrationRequestXSubtype = "1:876313859327:android:e10ec6ddb3c81f39"
)

// Valid indicates whether the value is a known member of the LegacyRegistrationRequestXSubtype enum.
func (e LegacyRegistrationRequestXSubtype) Valid() bool {
	switch e {
	case LegacyRegistrationRequestXSubtypeN1876313859327AndroidE10ec6ddb3c81f39:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRegistrationRequestApp.
const (
	OrgChromiumLinux LegacyRegistrationRequestApp = "org.chromium.linux"
)

// Valid indicates whether the value is a known member of the LegacyRegistrationRequestApp enum.
func (e LegacyRegistrationRequestApp) Valid() bool {
	switch e {
	case OrgChromiumLinux:
		return true
	default:
		return false
	}
}

// Defines values for LegacyRegistrationRequestSender.
const (
	BDOU99H67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv4L2LxQcYwhqby2xGpWwzjfAnG4 LegacyRegistrationRequestSender = "BDOU99-h67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv-4_l2LxQcYwhqby2xGpWwzjfAnG4"
)

// Valid indicates whether the value is a known member of the LegacyRegistrationRequestSender enum.
func (e LegacyRegistrationRequestSender) Valid() bool {
	switch e {
	case BDOU99H67HcA6JeFXHbSNMu7e2yNNu3RzoMj8TM4W88jITfq7ZmPvIM1Iv4L2LxQcYwhqby2xGpWwzjfAnG4:
		return true
	default:
		return false
	}
}

// Defines values for GoogleAPIKey.
const (
	GoogleAPIKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8 GoogleAPIKey = "AIzaSyCv-hdFBmmdBBJadNy-TFwB-xN_H5m3Bk8"
)

// Valid indicates whether the value is a known member of the GoogleAPIKey enum.
func (e GoogleAPIKey) Valid() bool {
	switch e {
	case GoogleAPIKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8:
		return true
	default:
		return false
	}
}

// Defines values for JSONAccept.
const (
	JSONAcceptApplicationjson JSONAccept = "application/json"
)

// Valid indicates whether the value is a known member of the JSONAccept enum.
func (e JSONAccept) Valid() bool {
	switch e {
	case JSONAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for JSONContentType.
const (
	JSONContentTypeApplicationjson JSONContentType = "application/json"
)

// Valid indicates whether the value is a known member of the JSONContentType enum.
func (e JSONContentType) Valid() bool {
	switch e {
	case JSONContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for ProtobufContentType.
const (
	ProtobufContentTypeApplicationxProtobuf ProtobufContentType = "application/x-protobuf"
)

// Valid indicates whether the value is a known member of the ProtobufContentType enum.
func (e ProtobufContentType) Valid() bool {
	switch e {
	case ProtobufContentTypeApplicationxProtobuf:
		return true
	default:
		return false
	}
}

// Defines values for RegisterFCMClientParamsContentType.
const (
	ApplicationxWwwFormUrlencoded RegisterFCMClientParamsContentType = "application/x-www-form-urlencoded"
)

// Valid indicates whether the value is a known member of the RegisterFCMClientParamsContentType enum.
func (e RegisterFCMClientParamsContentType) Valid() bool {
	switch e {
	case ApplicationxWwwFormUrlencoded:
		return true
	default:
		return false
	}
}

// Defines values for CheckInFCMClientParamsContentType.
const (
	CheckInFCMClientParamsContentTypeApplicationxProtobuf CheckInFCMClientParamsContentType = "application/x-protobuf"
)

// Valid indicates whether the value is a known member of the CheckInFCMClientParamsContentType enum.
func (e CheckInFCMClientParamsContentType) Valid() bool {
	switch e {
	case CheckInFCMClientParamsContentTypeApplicationxProtobuf:
		return true
	default:
		return false
	}
}

// Defines values for CreateFCMInstallationParamsAccept.
const (
	CreateFCMInstallationParamsAcceptApplicationjson CreateFCMInstallationParamsAccept = "application/json"
)

// Valid indicates whether the value is a known member of the CreateFCMInstallationParamsAccept enum.
func (e CreateFCMInstallationParamsAccept) Valid() bool {
	switch e {
	case CreateFCMInstallationParamsAcceptApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for CreateFCMInstallationParamsContentType.
const (
	CreateFCMInstallationParamsContentTypeApplicationjson CreateFCMInstallationParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the CreateFCMInstallationParamsContentType enum.
func (e CreateFCMInstallationParamsContentType) Valid() bool {
	switch e {
	case CreateFCMInstallationParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for CreateFCMInstallationParamsXGoogApiKey.
const (
	CreateFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8 CreateFCMInstallationParamsXGoogApiKey = "AIzaSyCv-hdFBmmdBBJadNy-TFwB-xN_H5m3Bk8"
)

// Valid indicates whether the value is a known member of the CreateFCMInstallationParamsXGoogApiKey enum.
func (e CreateFCMInstallationParamsXGoogApiKey) Valid() bool {
	switch e {
	case CreateFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8:
		return true
	default:
		return false
	}
}

// Defines values for RegisterFCMInstallationParamsContentType.
const (
	RegisterFCMInstallationParamsContentTypeApplicationjson RegisterFCMInstallationParamsContentType = "application/json"
)

// Valid indicates whether the value is a known member of the RegisterFCMInstallationParamsContentType enum.
func (e RegisterFCMInstallationParamsContentType) Valid() bool {
	switch e {
	case RegisterFCMInstallationParamsContentTypeApplicationjson:
		return true
	default:
		return false
	}
}

// Defines values for RegisterFCMInstallationParamsXGoogApiKey.
const (
	RegisterFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8 RegisterFCMInstallationParamsXGoogApiKey = "AIzaSyCv-hdFBmmdBBJadNy-TFwB-xN_H5m3Bk8"
)

// Valid indicates whether the value is a known member of the RegisterFCMInstallationParamsXGoogApiKey enum.
func (e RegisterFCMInstallationParamsXGoogApiKey) Valid() bool {
	switch e {
	case RegisterFCMInstallationParamsXGoogApiKeyAIzaSyCvHdFBmmdBBJadNyTFwBXNH5m3Bk8:
		return true
	default:
		return false
	}
}

// AndroidCheckinRequestWire Protobuf wire encoding of checkin_proto.AndroidCheckinRequest in the pinned checkin.proto files.
type AndroidCheckinRequestWire = openapi_types.File

// AndroidCheckinResponseWire Protobuf wire encoding of checkin_proto.AndroidCheckinResponse in the pinned checkin.proto files.
type AndroidCheckinResponseWire = openapi_types.File

// FCMRegistrationRequest defines model for FCMRegistrationRequest.
type FCMRegistrationRequest struct {
	Web FCMWebRegistration `json:"web"`
}

// FCMRegistrationResponse defines model for FCMRegistrationResponse.
type FCMRegistrationResponse struct {
	PushSet              *string                `json:"pushSet,omitempty"`
	Token                string                 `json:"token"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FCMWebRegistration defines model for FCMWebRegistration.
type FCMWebRegistration struct {
	// Auth URL-safe base64 encoding of a 16-byte Web Push authentication secret.
	Auth     string `json:"auth"`
	Endpoint string `json:"endpoint"`

	// P256dh URL-safe base64 encoding of a 65-byte uncompressed P-256 public key.
	P256dh string `json:"p256dh"`
}

// InstallationAuthToken defines model for InstallationAuthToken.
type InstallationAuthToken struct {
	ExpiresIn            *string                `json:"expiresIn,omitempty"`
	Token                string                 `json:"token"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// InstallationRequest defines model for InstallationRequest.
type InstallationRequest struct {
	AppId       InstallationRequestAppId       `json:"appId"`
	AuthVersion InstallationRequestAuthVersion `json:"authVersion"`

	// Fid Base64-encoded 17-byte FID from the pinned receiver implementation.
	Fid        string                        `json:"fid"`
	SdkVersion InstallationRequestSdkVersion `json:"sdkVersion"`
}

// InstallationRequestAppId defines model for InstallationRequest.AppId.
type InstallationRequestAppId string

// InstallationRequestAuthVersion defines model for InstallationRequest.AuthVersion.
type InstallationRequestAuthVersion string

// InstallationRequestSdkVersion defines model for InstallationRequest.SdkVersion.
type InstallationRequestSdkVersion string

// InstallationResponse defines model for InstallationResponse.
type InstallationResponse struct {
	AuthToken            InstallationAuthToken  `json:"authToken"`
	Fid                  string                 `json:"fid"`
	Name                 string                 `json:"name"`
	RefreshToken         string                 `json:"refreshToken"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LegacyRegistrationRequest Form fields are URL encoded as UTF-8.
type LegacyRegistrationRequest struct {
	XSubtype LegacyRegistrationRequestXSubtype `json:"X-subtype"`
	App      LegacyRegistrationRequestApp      `json:"app"`
	Device   string                            `json:"device"`
	Sender   LegacyRegistrationRequestSender   `json:"sender"`
}

// LegacyRegistrationRequestXSubtype defines model for LegacyRegistrationRequest.XSubtype.
type LegacyRegistrationRequestXSubtype string

// LegacyRegistrationRequestApp defines model for LegacyRegistrationRequest.App.
type LegacyRegistrationRequestApp string

// LegacyRegistrationRequestSender defines model for LegacyRegistrationRequest.Sender.
type LegacyRegistrationRequestSender string

// LegacyRegistrationResponse Form-encoded response containing the registration token.
type LegacyRegistrationResponse = string

// RingPushNotificationConfig Optional Ring category in an MCS notification's android_config JSON string.
type RingPushNotificationConfig struct {
	// Category Open Ring action category, such as ding or motion.
	Category             *string                `json:"category,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingPushNotificationDevice defines model for RingPushNotificationDevice.
type RingPushNotificationDevice struct {
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingPushNotificationEnvelope Synthetic decoded notification envelope used by the public push adapter. The captured encrypted MCS replay carries android_config and data as JSON-encoded strings; the adapter also accepts already-decoded objects.
type RingPushNotificationEnvelope struct {
	AndroidConfig *RingPushNotificationEnvelope_AndroidConfig `json:"android_config,omitempty"`
	Data          *RingPushNotificationEnvelope_Data          `json:"data,omitempty"`

	// DoorbotId Synthetic compatibility fallback when a nested device ID is absent.
	DoorbotId            *int64                 `json:"doorbot_id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingPushNotificationEnvelopeAndroidConfig0 defines model for RingPushNotificationEnvelope.AndroidConfig.0.
type RingPushNotificationEnvelopeAndroidConfig0 = string

// RingPushNotificationEnvelope_AndroidConfig defines model for RingPushNotificationEnvelope.AndroidConfig.
type RingPushNotificationEnvelope_AndroidConfig struct {
	union json.RawMessage
}

// RingPushNotificationEnvelopeData0 defines model for RingPushNotificationEnvelope.Data.0.
type RingPushNotificationEnvelopeData0 = string

// RingPushNotificationEnvelope_Data defines model for RingPushNotificationEnvelope.Data.
type RingPushNotificationEnvelope_Data struct {
	union json.RawMessage
}

// RingPushNotificationGCMData defines model for RingPushNotificationGCMData.
type RingPushNotificationGCMData struct {
	// Action Open Ring action name, including intercom_unlock.
	Action               *string                `json:"action,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RingPushNotificationPayload Optional Ring data object carried as a JSON string in an MCS notification.
type RingPushNotificationPayload struct {
	Device               *RingPushNotificationDevice  `json:"device,omitempty"`
	GcmData              *RingPushNotificationGCMData `json:"gcmData,omitempty"`
	AdditionalProperties map[string]interface{}       `json:"-"`
}

// GoogleAPIKey defines model for GoogleAPIKey.
type GoogleAPIKey string

// JSONAccept defines model for JSONAccept.
type JSONAccept string

// JSONContentType defines model for JSONContentType.
type JSONContentType string

// ProtobufContentType defines model for ProtobufContentType.
type ProtobufContentType string

// RegisterFCMClientParams defines parameters for RegisterFCMClient.
type RegisterFCMClientParams struct {
	ContentType RegisterFCMClientParamsContentType `json:"Content-Type"`

	// Authorization Android ID and security token from the check-in response.
	Authorization string `json:"Authorization"`

	// UserAgent The pinned receiver sends an empty User-Agent value.
	UserAgent string `json:"User-Agent"`
}

// RegisterFCMClientParamsContentType defines parameters for RegisterFCMClient.
type RegisterFCMClientParamsContentType string

// CheckInFCMClientParams defines parameters for CheckInFCMClient.
type CheckInFCMClientParams struct {
	ContentType CheckInFCMClientParamsContentType `json:"Content-Type"`
}

// CheckInFCMClientParamsContentType defines parameters for CheckInFCMClient.
type CheckInFCMClientParamsContentType string

// CreateFCMInstallationParams defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParams struct {
	Accept      CreateFCMInstallationParamsAccept      `json:"Accept"`
	ContentType CreateFCMInstallationParamsContentType `json:"Content-Type"`

	// XGoogApiKey Public API key configured by the pinned Ring Android client.
	XGoogApiKey CreateFCMInstallationParamsXGoogApiKey `json:"X-Goog-Api-Key"`
}

// CreateFCMInstallationParamsAccept defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParamsAccept string

// CreateFCMInstallationParamsContentType defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParamsContentType string

// CreateFCMInstallationParamsXGoogApiKey defines parameters for CreateFCMInstallation.
type CreateFCMInstallationParamsXGoogApiKey string

// RegisterFCMInstallationParams defines parameters for RegisterFCMInstallation.
type RegisterFCMInstallationParams struct {
	ContentType RegisterFCMInstallationParamsContentType `json:"Content-Type"`

	// XGoogApiKey Public API key configured by the pinned Ring Android client.
	XGoogApiKey RegisterFCMInstallationParamsXGoogApiKey `json:"X-Goog-Api-Key"`

	// XGoogFirebaseInstallationsAuth The local compatibility adapter removes the upstream FIS prefix before forwarding.
	XGoogFirebaseInstallationsAuth string `json:"X-Goog-Firebase-Installations-Auth"`
}

// RegisterFCMInstallationParamsContentType defines parameters for RegisterFCMInstallation.
type RegisterFCMInstallationParamsContentType string

// RegisterFCMInstallationParamsXGoogApiKey defines parameters for RegisterFCMInstallation.
type RegisterFCMInstallationParamsXGoogApiKey string

// RegisterFCMClientFormdataRequestBody defines body for RegisterFCMClient for application/x-www-form-urlencoded ContentType.
type RegisterFCMClientFormdataRequestBody = LegacyRegistrationRequest

// CreateFCMInstallationJSONRequestBody defines body for CreateFCMInstallation for application/json ContentType.
type CreateFCMInstallationJSONRequestBody = InstallationRequest

// RegisterFCMInstallationJSONRequestBody defines body for RegisterFCMInstallation for application/json ContentType.
type RegisterFCMInstallationJSONRequestBody = FCMRegistrationRequest

// Getter for additional properties for FCMRegistrationResponse. Returns the specified
// element and whether it was found
func (a FCMRegistrationResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FCMRegistrationResponse
func (a *FCMRegistrationResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FCMRegistrationResponse to handle AdditionalProperties
func (a *FCMRegistrationResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["pushSet"]; found {
		err = json.Unmarshal(raw, &a.PushSet)
		if err != nil {
			return fmt.Errorf("error reading 'pushSet': %w", err)
		}
		delete(object, "pushSet")
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &a.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
		delete(object, "token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FCMRegistrationResponse to handle AdditionalProperties
func (a FCMRegistrationResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.PushSet != nil {
		object["pushSet"], err = json.Marshal(a.PushSet)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pushSet': %w", err)
		}
	}

	object["token"], err = json.Marshal(a.Token)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for InstallationAuthToken. Returns the specified
// element and whether it was found
func (a InstallationAuthToken) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for InstallationAuthToken
func (a *InstallationAuthToken) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for InstallationAuthToken to handle AdditionalProperties
func (a *InstallationAuthToken) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["expiresIn"]; found {
		err = json.Unmarshal(raw, &a.ExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'expiresIn': %w", err)
		}
		delete(object, "expiresIn")
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &a.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
		delete(object, "token")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for InstallationAuthToken to handle AdditionalProperties
func (a InstallationAuthToken) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ExpiresIn != nil {
		object["expiresIn"], err = json.Marshal(a.ExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expiresIn': %w", err)
		}
	}

	object["token"], err = json.Marshal(a.Token)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for InstallationResponse. Returns the specified
// element and whether it was found
func (a InstallationResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for InstallationResponse
func (a *InstallationResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for InstallationResponse to handle AdditionalProperties
func (a *InstallationResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["authToken"]; found {
		err = json.Unmarshal(raw, &a.AuthToken)
		if err != nil {
			return fmt.Errorf("error reading 'authToken': %w", err)
		}
		delete(object, "authToken")
	}

	if raw, found := object["fid"]; found {
		err = json.Unmarshal(raw, &a.Fid)
		if err != nil {
			return fmt.Errorf("error reading 'fid': %w", err)
		}
		delete(object, "fid")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["refreshToken"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refreshToken': %w", err)
		}
		delete(object, "refreshToken")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for InstallationResponse to handle AdditionalProperties
func (a InstallationResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["authToken"], err = json.Marshal(a.AuthToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'authToken': %w", err)
	}

	object["fid"], err = json.Marshal(a.Fid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'fid': %w", err)
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["refreshToken"], err = json.Marshal(a.RefreshToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'refreshToken': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationConfig. Returns the specified
// element and whether it was found
func (a RingPushNotificationConfig) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationConfig
func (a *RingPushNotificationConfig) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationConfig to handle AdditionalProperties
func (a *RingPushNotificationConfig) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["category"]; found {
		err = json.Unmarshal(raw, &a.Category)
		if err != nil {
			return fmt.Errorf("error reading 'category': %w", err)
		}
		delete(object, "category")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationConfig to handle AdditionalProperties
func (a RingPushNotificationConfig) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Category != nil {
		object["category"], err = json.Marshal(a.Category)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'category': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationDevice. Returns the specified
// element and whether it was found
func (a RingPushNotificationDevice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationDevice
func (a *RingPushNotificationDevice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationDevice to handle AdditionalProperties
func (a *RingPushNotificationDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationDevice to handle AdditionalProperties
func (a RingPushNotificationDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationEnvelope. Returns the specified
// element and whether it was found
func (a RingPushNotificationEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationEnvelope
func (a *RingPushNotificationEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationEnvelope to handle AdditionalProperties
func (a *RingPushNotificationEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["android_config"]; found {
		err = json.Unmarshal(raw, &a.AndroidConfig)
		if err != nil {
			return fmt.Errorf("error reading 'android_config': %w", err)
		}
		delete(object, "android_config")
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["doorbot_id"]; found {
		err = json.Unmarshal(raw, &a.DoorbotId)
		if err != nil {
			return fmt.Errorf("error reading 'doorbot_id': %w", err)
		}
		delete(object, "doorbot_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationEnvelope to handle AdditionalProperties
func (a RingPushNotificationEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AndroidConfig != nil {
		object["android_config"], err = json.Marshal(a.AndroidConfig)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'android_config': %w", err)
		}
	}

	if a.Data != nil {
		object["data"], err = json.Marshal(a.Data)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'data': %w", err)
		}
	}

	if a.DoorbotId != nil {
		object["doorbot_id"], err = json.Marshal(a.DoorbotId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'doorbot_id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationGCMData. Returns the specified
// element and whether it was found
func (a RingPushNotificationGCMData) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationGCMData
func (a *RingPushNotificationGCMData) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationGCMData to handle AdditionalProperties
func (a *RingPushNotificationGCMData) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationGCMData to handle AdditionalProperties
func (a RingPushNotificationGCMData) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Action != nil {
		object["action"], err = json.Marshal(a.Action)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'action': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RingPushNotificationPayload. Returns the specified
// element and whether it was found
func (a RingPushNotificationPayload) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RingPushNotificationPayload
func (a *RingPushNotificationPayload) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RingPushNotificationPayload to handle AdditionalProperties
func (a *RingPushNotificationPayload) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["device"]; found {
		err = json.Unmarshal(raw, &a.Device)
		if err != nil {
			return fmt.Errorf("error reading 'device': %w", err)
		}
		delete(object, "device")
	}

	if raw, found := object["gcmData"]; found {
		err = json.Unmarshal(raw, &a.GcmData)
		if err != nil {
			return fmt.Errorf("error reading 'gcmData': %w", err)
		}
		delete(object, "gcmData")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RingPushNotificationPayload to handle AdditionalProperties
func (a RingPushNotificationPayload) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Device != nil {
		object["device"], err = json.Marshal(a.Device)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'device': %w", err)
		}
	}

	if a.GcmData != nil {
		object["gcmData"], err = json.Marshal(a.GcmData)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gcmData': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsRingPushNotificationEnvelopeAndroidConfig0 returns the union data inside the RingPushNotificationEnvelope_AndroidConfig as a RingPushNotificationEnvelopeAndroidConfig0
func (t RingPushNotificationEnvelope_AndroidConfig) AsRingPushNotificationEnvelopeAndroidConfig0() (RingPushNotificationEnvelopeAndroidConfig0, error) {
	var body RingPushNotificationEnvelopeAndroidConfig0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRingPushNotificationEnvelopeAndroidConfig0 overwrites any union data inside the RingPushNotificationEnvelope_AndroidConfig as the provided RingPushNotificationEnvelopeAndroidConfig0
func (t *RingPushNotificationEnvelope_AndroidConfig) FromRingPushNotificationEnvelopeAndroidConfig0(v RingPushNotificationEnvelopeAndroidConfig0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRingPushNotificationEnvelopeAndroidConfig0 performs a merge with any union data inside the RingPushNotificationEnvelope_AndroidConfig, using the provided RingPushNotificationEnvelopeAndroidConfig0
func (t *RingPushNotificationEnvelope_AndroidConfig) MergeRingPushNotificationEnvelopeAndroidConfig0(v RingPushNotificationEnvelopeAndroidConfig0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRingPushNotificationConfig returns the union data inside the RingPushNotificationEnvelope_AndroidConfig as a RingPushNotificationConfig
func (t RingPushNotificationEnvelope_AndroidConfig) AsRingPushNotificationConfig() (RingPushNotificationConfig, error) {
	var body RingPushNotificationConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRingPushNotificationConfig overwrites any union data inside the RingPushNotificationEnvelope_AndroidConfig as the provided RingPushNotificationConfig
func (t *RingPushNotificationEnvelope_AndroidConfig) FromRingPushNotificationConfig(v RingPushNotificationConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRingPushNotificationConfig performs a merge with any union data inside the RingPushNotificationEnvelope_AndroidConfig, using the provided RingPushNotificationConfig
func (t *RingPushNotificationEnvelope_AndroidConfig) MergeRingPushNotificationConfig(v RingPushNotificationConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RingPushNotificationEnvelope_AndroidConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RingPushNotificationEnvelope_AndroidConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRingPushNotificationEnvelopeData0 returns the union data inside the RingPushNotificationEnvelope_Data as a RingPushNotificationEnvelopeData0
func (t RingPushNotificationEnvelope_Data) AsRingPushNotificationEnvelopeData0() (RingPushNotificationEnvelopeData0, error) {
	var body RingPushNotificationEnvelopeData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRingPushNotificationEnvelopeData0 overwrites any union data inside the RingPushNotificationEnvelope_Data as the provided RingPushNotificationEnvelopeData0
func (t *RingPushNotificationEnvelope_Data) FromRingPushNotificationEnvelopeData0(v RingPushNotificationEnvelopeData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRingPushNotificationEnvelopeData0 performs a merge with any union data inside the RingPushNotificationEnvelope_Data, using the provided RingPushNotificationEnvelopeData0
func (t *RingPushNotificationEnvelope_Data) MergeRingPushNotificationEnvelopeData0(v RingPushNotificationEnvelopeData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRingPushNotificationPayload returns the union data inside the RingPushNotificationEnvelope_Data as a RingPushNotificationPayload
func (t RingPushNotificationEnvelope_Data) AsRingPushNotificationPayload() (RingPushNotificationPayload, error) {
	var body RingPushNotificationPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRingPushNotificationPayload overwrites any union data inside the RingPushNotificationEnvelope_Data as the provided RingPushNotificationPayload
func (t *RingPushNotificationEnvelope_Data) FromRingPushNotificationPayload(v RingPushNotificationPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRingPushNotificationPayload performs a merge with any union data inside the RingPushNotificationEnvelope_Data, using the provided RingPushNotificationPayload
func (t *RingPushNotificationEnvelope_Data) MergeRingPushNotificationPayload(v RingPushNotificationPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RingPushNotificationEnvelope_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RingPushNotificationEnvelope_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
