import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { GoFileGenerator, GO_COMMON_PRESET } from '@asyncapi/modelina';

const directories = ['../../internal/generatedsignaling', '../../pkg/generatedsignaling'];
const source = await readFile('../../api/asyncapi.yaml', 'utf8');
const generator = new GoFileGenerator({
  presets: [{ preset: GO_COMMON_PRESET, options: { addJsonTag: true } }],
});
for (const directory of directories) {
  await mkdir(directory, { recursive: true });
  for (const file of await readdir(directory)) {
    if (file.endsWith('.go')) await unlink(join(directory, file));
  }
  await generator.generateToFiles(source, directory, { packageName: 'generatedsignaling' });
  for (const file of await readdir(directory)) {
    if (!file.endsWith('.go')) continue;
    const path = join(directory, file);
    const output = await readFile(path, 'utf8');
    // Modelina emits an unterminated JSON tag for anonymous union fields.
    // Keep the schema-generated field while making its unused wrapper tag valid.
    const validOutput = output.replaceAll('`json:"-,omitempty`', '`json:"-"`');
    await writeFile(path, `// Code generated by @asyncapi/modelina. DO NOT EDIT.\n\n${validOutput}`);
  }
}
