import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { GoFileGenerator, GO_COMMON_PRESET } from '@asyncapi/modelina';

const generatedDirectory = '../../pkg/dependencymodels/signaling';
const compatibilityDirectories = ['../../internal/generatedsignaling', '../../pkg/generatedsignaling'];
const source = await readFile('../../api/asyncapi.yaml', 'utf8');
const generator = new GoFileGenerator({
  presets: [{ preset: GO_COMMON_PRESET, options: { addJsonTag: true } }],
});
await clearGoFiles(generatedDirectory);
await generator.generateToFiles(source, generatedDirectory, { packageName: 'signaling' });

for (const file of await readdir(generatedDirectory)) {
  if (!file.endsWith('.go')) continue;

  const path = join(generatedDirectory, file);
  const output = await readFile(path, 'utf8');
  // Modelina emits an unterminated JSON tag for anonymous union fields.
  // Keep the schema-generated field while making its unused wrapper tag valid.
  const validOutput = output.replaceAll('`json:"-,omitempty`', '`json:"-"`');
  await writeFile(path, `// Code generated by @asyncapi/modelina. DO NOT EDIT.\n\n${validOutput}`);
}

const compatibilitySource = await makeCompatibilityAliases(generatedDirectory);
for (const directory of compatibilityDirectories) {
  await clearGoFiles(directory);
  await mkdir(directory, { recursive: true });
  const packageName = directory.endsWith('/generatedsignaling')
    ? 'generatedsignaling'
    : 'generatedsignaling';
  const packageComment = directory.includes('/pkg/')
    ? '// Package generatedsignaling re-exports the schema-generated dependency models for source compatibility.\n'
    : '';
  await writeFile(
    join(directory, 'models_compat.gen.go'),
    `// Code generated by tools/protocols/generate_signaling.mjs. DO NOT EDIT.\n${packageComment}\npackage ${packageName}\n\n${compatibilitySource}`,
  );
}

async function clearGoFiles(directory) {
  await mkdir(directory, { recursive: true });
  for (const file of await readdir(directory)) {
    if (file.endsWith('.go')) await unlink(join(directory, file));
  }
}

async function makeCompatibilityAliases(directory) {
  const types = new Set();
  const constants = new Set();
  const variables = new Set();

  for (const file of await readdir(directory)) {
    if (!file.endsWith('.go')) continue;

    const content = await readFile(join(directory, file), 'utf8');
    for (const match of content.matchAll(/^type\s+([A-Z][A-Za-z0-9_]*)\s+/gm)) types.add(match[1]);
    for (const block of content.matchAll(/const\s*\(([\s\S]*?)\)/g)) {
      for (const line of block[1].split('\n')) {
        const name = /^\s*([A-Z][A-Za-z0-9_]*)\b/.exec(line)?.[1];
        if (name) constants.add(name);
      }
    }
    for (const match of content.matchAll(/^const\s+([A-Z][A-Za-z0-9_]*)\b/gm)) constants.add(match[1]);
    for (const match of content.matchAll(/^var\s+([A-Z][A-Za-z0-9_]*)\b/gm)) variables.add(match[1]);
  }

  const modelImport = 'signalingmodels "github.com/portpowered/go-ring/pkg/dependencymodels/signaling"';
  const sections = [`import ${modelImport}`, ...[...types].sort().map((name) => `type ${name} = signalingmodels.${name}`)];

  if (constants.size > 0) {
    sections.push(`const (\n${[...constants].sort().map((name) => `\t${name} = signalingmodels.${name}`).join('\n')}\n)`);
  }

  if (variables.size > 0) {
    sections.push(`var (\n${[...variables].sort().map((name) => `\t${name} = signalingmodels.${name}`).join('\n')}\n)`);
  }

  return sections.join('\n\n') + '\n';
}
