import { readFile, writeFile } from 'node:fs/promises';

const root = '../../';
const targets = [
  {
    source: 'pkg/dependencymodels/rest/models.gen.go',
    clients: [
      { path: 'internal/generatedhttp/client.gen.go', packageName: 'generatedhttp' },
      { path: 'pkg/generatedhttp/client.gen.go', packageName: 'generatedhttp' },
    ],
    importPath: 'github.com/portpowered/go-ring/pkg/dependencymodels/rest',
    importName: 'restmodels',
  },
  {
    source: 'pkg/dependencymodels/fcm/models.gen.go',
    clients: [{ path: 'internal/generatedfcm/client.gen.go', packageName: 'generatedfcm' }],
    importPath: 'github.com/portpowered/go-ring/pkg/dependencymodels/fcm',
    importName: 'fcmmodels',
  },
];

for (const target of targets) {
  const models = await readFile(root + target.source, 'utf8');
  const modelDeclarations = declarations(models);

  for (const client of target.clients) {
    const clientSource = await readFile(root + client.path, 'utf8');
    const clientDeclarations = declarations(clientSource);
    const sections = [`import ${target.importName} "${target.importPath}"`];

    const aliases = [...modelDeclarations.types]
      .filter((name) => !clientDeclarations.types.has(name))
      .sort()
      .map((name) => `type ${name} = ${target.importName}.${name}`);
    if (aliases.length > 0) sections.push(aliases.join('\n'));

    const constants = [...modelDeclarations.constants]
      .filter((name) => !clientDeclarations.constants.has(name))
      .sort()
      .map((name) => `\t${name} = ${target.importName}.${name}`);
    if (constants.length > 0) sections.push(`const (\n${constants.join('\n')}\n)`);

    const variables = [...modelDeclarations.variables]
      .filter((name) => !clientDeclarations.variables.has(name))
      .sort()
      .map((name) => `\t${name} = ${target.importName}.${name}`);
    if (variables.length > 0) sections.push(`var (\n${variables.join('\n')}\n)`);

    const outputPath = root + client.path.replace(/client\.gen\.go$/, 'models_compat.gen.go');
    const source = [
      '// Code generated by tools/protocols/generate_oapi_compat.mjs. DO NOT EDIT.',
      '',
      `package ${client.packageName}`,
      '',
      sections.join('\n\n'),
      '',
    ].join('\n');
    await writeFile(outputPath, source);
  }
}

function declarations(source) {
  const types = new Set([...source.matchAll(/^type\s+([A-Z][A-Za-z0-9_]*)\s+/gm)].map((match) => match[1]));
  const constants = new Set();
  const variables = new Set();

  for (const block of source.matchAll(/\bconst\s*\(([\s\S]*?)\)/g)) {
    for (const line of block[1].split('\n')) {
      const name = /^\s*([A-Z][A-Za-z0-9_]*)\b/.exec(line)?.[1];
      if (name) constants.add(name);
    }
  }

  for (const match of source.matchAll(/^const\s+([A-Z][A-Za-z0-9_]*)\b/gm)) constants.add(match[1]);
  for (const match of source.matchAll(/^var\s+([A-Z][A-Za-z0-9_]*)\b/gm)) variables.add(match[1]);

  return { types, constants, variables };
}
