package protocols_test

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
)

type parsedModelFile struct {
	relative string
	fileSet  *token.FileSet
	file     *ast.File
}

type modelComponentOrigin struct {
	group string
	path  string
}

type modelOperationOrigin struct {
	schemaFile string
	method     string
	path       string
}

func restWireModels(t *testing.T, root string) []documentedWireModel {
	t.Helper()

	groups, err := filepath.Glob(filepath.Join(root, "api", "schemas", "*.yaml"))
	if err != nil {
		t.Fatalf("list REST schema groups: %v", err)
	}

	componentOrigins := make(map[string][]modelComponentOrigin)

	for _, path := range groups {
		group := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
		addComponentOrigins(t, root, path, group, componentOrigins)
	}

	apiPath := filepath.Join(root, "api", "openapi.yaml")
	api := readYAMLObject(t, apiPath)
	operations := modelOperationOrigins(t, api, true, "api/openapi.yaml")
	modelFiles := parseModelFiles(t, root, filepath.Join(root, "pkg", "dependencymodels", "rest"), "*.gen.go")
	models := make([]documentedWireModel, 0, 330)

	for _, source := range modelFiles {
		group := strings.TrimSuffix(filepath.Base(source.relative), ".gen.go")
		if !fileHasRESTResponsibility(t, source.file, group) {
			continue
		}

		for _, declaration := range source.file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}

			for _, specification := range general.Specs {
				typeSpec, ok := specification.(*ast.TypeSpec)
				if !ok {
					continue
				}

				comment := generatedTypeComment(typeSpec, general)

				owner, found := openAPIModelOwner(comment, typeSpec.Name.Name, componentOrigins, operations)

				if !found {
					t.Fatalf(
						"REST generated type %s in %s has no canonical component or operation owner: %q",
						typeSpec.Name.Name, source.relative, comment,
					)
				}

				models = append(models, documentedWireModel{
					family: "Ring REST", packagePath: wireInventoryModulePath + "/pkg/dependencymodels/rest",
					goType: "rest." + typeSpec.Name.Name, schemaOwner: owner, sourceFile: source.relative,
					generator: "oapi-codegen v2.8.0; responsibility split by make generate-api", typeSpec: typeSpec,
				})
			}
		}
	}

	if len(models) == 0 {
		t.Fatal("REST model inventory found no generated declarations")
	}

	return models
}

func standaloneOpenAPIWireModels(
	t *testing.T,
	root, family, schemaRelative, modelDirectory, packageName, generator string,
) []documentedWireModel {
	t.Helper()

	schemaPath := filepath.Join(root, filepath.FromSlash(schemaRelative))
	schema := readYAMLObject(t, schemaPath)
	componentOrigins := make(map[string][]modelComponentOrigin)
	addComponentOrigins(t, root, schemaPath, "", componentOrigins)
	operations := modelOperationOrigins(t, schema, false, schemaRelative)
	modelFiles := parseModelFiles(t, root, filepath.Join(root, filepath.FromSlash(modelDirectory)), "*.gen.go")
	models := make([]documentedWireModel, 0)

	for _, source := range modelFiles {
		for _, declaration := range source.file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}

			for _, specification := range general.Specs {
				typeSpec, ok := specification.(*ast.TypeSpec)
				if !ok {
					continue
				}

				comment := generatedTypeComment(typeSpec, general)

				owner, found := openAPIModelOwner(comment, typeSpec.Name.Name, componentOrigins, operations)

				if !found {
					t.Fatalf("%s generated type %s has no canonical schema owner: %q", family, typeSpec.Name.Name, comment)
				}

				models = append(models, documentedWireModel{
					family: family, packagePath: wireInventoryModulePath + "/" + filepath.ToSlash(modelDirectory),
					goType: packageName + "." + typeSpec.Name.Name, schemaOwner: owner, sourceFile: source.relative,
					generator: generator, typeSpec: typeSpec,
				})
			}
		}
	}

	if len(models) == 0 {
		t.Fatalf("%s model inventory found no generated declarations", family)
	}

	return models
}

func signalingWireModels(t *testing.T, root string) []documentedWireModel {
	t.Helper()

	owners := signalingModelOwners(t, root)
	modelFiles := parseModelFiles(t, root, filepath.Join(root, "pkg", "dependencymodels", "signaling"), "*.go")
	models := make([]documentedWireModel, 0, 78)

	for _, source := range modelFiles {
		if !generatedFileHasMarker(source.file, "Code generated by @asyncapi/modelina.") {
			continue
		}

		models = append(models, signalingModelsInFile(t, source, owners)...)
	}

	if len(models) == 0 {
		t.Fatal("signaling model inventory found no generated declarations")
	}

	return models
}

func signalingModelOwners(t *testing.T, root string) map[string]string {
	t.Helper()

	const schemaPath = "api/asyncapi.yaml"

	components := nestedMap(readYAMLObject(t, filepath.Join(root, schemaPath)), "components", "schemas")
	owners := make(map[string]string, len(components)+4)
	componentNames := make(map[string]string, len(components))

	for name := range components {
		goType := normalizeModelinaAcronyms(name)
		owners[goType] = schemaPath + "#/components/schemas/" + name
		componentNames[goType] = name
	}

	for _, origin := range anonymousSignalingOrigins() {
		parent := componentNames[origin.owner.Name()]
		if parent == "" {
			t.Fatalf("signaling parent %s has no AsyncAPI schema component", origin.owner.Name())
		}

		owners[origin.goType] = schemaPath + "#/components/schemas/" + parent + "/properties/" + origin.property
	}

	owners["PTzCommand"] = schemaPath + "#/components/messages/PTZCommand"
	owners["SessionStreamOptions"] = schemaPath + "#/channels/sessionStreamOptions/messages"

	return owners
}

func signalingModelsInFile(
	t *testing.T,
	source parsedModelFile,
	owners map[string]string,
) []documentedWireModel {
	t.Helper()

	models := make([]documentedWireModel, 0)

	for _, declaration := range source.file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}

		for _, specification := range general.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if !ok {
				continue
			}

			name := typeSpec.Name.Name
			owner := owners[name]

			if owner == "" {
				t.Fatalf("signaling generated type %s in %s has no AsyncAPI owner", name, source.relative)
			}

			models = append(models, documentedWireModel{
				family: "Signaling and account events", packagePath: wireInventoryModulePath + "/pkg/dependencymodels/signaling",
				goType: "signaling." + name, schemaOwner: owner, sourceFile: source.relative,
				generator: "Modelina via tools/protocols/generate_signaling.mjs and make generate-api", typeSpec: typeSpec,
			})
		}
	}

	return models
}

func protobufWireModels(t *testing.T, root string) []documentedWireModel {
	t.Helper()

	const inventoryPath = "api/external/push-protocol-inventory.yaml"

	protobuf := mapValue(readYAMLObject(t, filepath.Join(root, inventoryPath))["protobuf"])
	generator := mapValue(protobuf["generator"])
	generatorName := "protoc " + stringValueForInventory(generator["protoc"]) +
		" and protoc-gen-go " + stringValueForInventory(generator["protoc_gen_go"]) +
		" (pinned by " + inventoryPath + ")"
	generatedPaths := protobufGeneratedPaths(protobuf)
	messagePattern := regexp.MustCompile(`(?m)^\s*message\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{`)
	models := make([]documentedWireModel, 0, 24)

	for _, sourceValue := range anySliceForInventory(protobuf["source_files"]) {
		source := mapValue(sourceValue)
		protoRelative := stringValueForInventory(source["path"])
		generatedRelative := generatedPaths[filepath.Base(protoRelative)]

		if generatedRelative == "" {
			t.Fatalf("protobuf source %s has no generated Go file in %s", protoRelative, inventoryPath)
		}

		models = append(models, protobufSourceModels(
			t, root, inventoryPath, protoRelative, generatedRelative, generatorName, messagePattern,
		)...)
	}

	return models
}

func protobufGeneratedPaths(protobuf map[string]any) map[string]string {
	paths := make(map[string]string)

	for _, generatedValue := range anySliceForInventory(protobuf["generated_go_files"]) {
		generated := mapValue(generatedValue)
		paths[stringValueForInventory(generated["source"])] = stringValueForInventory(generated["path"])
	}

	return paths
}

func protobufSourceModels(
	t *testing.T,
	root, inventoryPath, protoRelative, generatedRelative, generatorName string,
	messagePattern *regexp.Regexp,
) []documentedWireModel {
	t.Helper()

	protoPath := filepath.Join(root, filepath.FromSlash(protoRelative))

	protoSource, err := os.ReadFile(protoPath) // #nosec G304 -- source is pinned in the checked-in protocol inventory.
	if err != nil {
		t.Fatal(err)
	}

	generatedFile := filepath.Join(root, filepath.FromSlash(generatedRelative))
	generatedFiles := parseModelFiles(t, root, filepath.Dir(generatedFile), filepath.Base(generatedFile))
	declarations := protobufGeneratedDeclarations(generatedFiles)
	messages := messagePattern.FindAllSubmatch(protoSource, -1)
	expected := make(map[string]bool, len(messages))
	models := make([]documentedWireModel, 0, len(messages))

	for _, message := range messages {
		name := string(message[1])
		expected[name] = true
		model := protobufMessageModel(
			t, generatedFiles, declarations, inventoryPath, protoRelative, generatedRelative, generatorName, name,
		)
		models = append(models, model)
	}

	if len(expected) != len(declarations) {
		t.Fatalf(
			"protobuf generated message set in %s has %d structs; source declares %d messages",
			generatedRelative, len(declarations), len(expected),
		)
	}

	return models
}

func protobufGeneratedDeclarations(generatedFiles []parsedModelFile) map[string]*ast.TypeSpec {
	declarations := make(map[string]*ast.TypeSpec)

	for _, sourceFile := range generatedFiles {
		for _, declaration := range sourceFile.file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}

			for _, specification := range general.Specs {
				typeSpec, ok := specification.(*ast.TypeSpec)
				if !ok || !ast.IsExported(typeSpec.Name.Name) {
					continue
				}

				if _, ok := typeSpec.Type.(*ast.StructType); ok {
					declarations[typeSpec.Name.Name] = typeSpec
				}
			}
		}
	}

	return declarations
}

func protobufMessageModel(
	t *testing.T,
	generatedFiles []parsedModelFile,
	declarations map[string]*ast.TypeSpec,
	inventoryPath, protoRelative, generatedRelative, generatorName, name string,
) documentedWireModel {
	t.Helper()

	typeSpec := declarations[name]
	if typeSpec == nil {
		t.Fatalf("protobuf message %s in %s has no generated type in %s", name, protoRelative, generatedRelative)
	}

	packagePath := wireInventoryModulePath + "/" + filepath.ToSlash(filepath.Dir(generatedRelative))
	packageName := generatedFiles[0].file.Name.Name

	return documentedWireModel{
		family: "MCS and check-in protobuf", packagePath: packagePath,
		goType:      packageName + "." + name,
		schemaOwner: protoRelative + "#message/" + name + " (source pinned by " + inventoryPath + ")",
		sourceFile:  generatedRelative, generator: generatorName, typeSpec: typeSpec,
	}
}

func addComponentOrigins(
	t *testing.T,
	root, schemaPath, group string,
	origins map[string][]modelComponentOrigin,
) {
	t.Helper()

	document := readYAMLObject(t, schemaPath)

	components := mapValue(document["components"])
	for category, value := range components {
		for name := range mapValue(value) {
			relative, err := filepath.Rel(root, schemaPath)
			if err != nil {
				t.Fatal(err)
			}

			path := filepath.ToSlash(relative) + "#/components/" + category + "/" + name
			origins[name] = append(origins[name], modelComponentOrigin{group: group, path: path})
		}
	}
}

func modelOperationOrigins(
	t *testing.T,
	document map[string]any,
	grouped bool,
	schemaRelative string,
) map[string]modelOperationOrigin {
	t.Helper()

	operations := make(map[string]modelOperationOrigin)

	for apiPath, pathItemValue := range mapValue(document["paths"]) {
		for method, operationValue := range mapValue(pathItemValue) {
			methods := []string{"get", "put", "post", "delete", "options", "head", "patch", "trace"}
			if !slices.Contains(methods, strings.ToLower(method)) {
				continue
			}

			operation := mapValue(operationValue)

			operationID, _ := operation["operationId"].(string)
			if operationID == "" {
				continue
			}

			schemaFile := schemaRelative

			if grouped {
				tags, _ := operation["tags"].([]any)
				if len(tags) != 1 {
					continue
				}

				tag, _ := tags[0].(string)
				group := strings.ReplaceAll(strings.ToLower(tag), " ", "-")
				schemaFile = "api/schemas/" + group + ".yaml"
			}

			operations[exportedModelOperationName(operationID)] = modelOperationOrigin{
				schemaFile: schemaFile, method: strings.ToLower(method), path: apiPath,
			}
		}
	}

	return operations
}

func openAPIModelOwner(
	comment, goType string,
	componentOrigins map[string][]modelComponentOrigin,
	operations map[string]modelOperationOrigin,
) (string, bool) {
	for _, kind := range []string{"model", "parameters", "body"} {
		prefix := "defines " + kind + " for "

		index := strings.Index(comment, prefix)
		if index < 0 {
			continue
		}

		parts := strings.Fields(comment[index+len(prefix):])
		if len(parts) == 0 {
			return "", false
		}

		owner := strings.TrimSuffix(parts[0], ".")
		if kind == "model" {
			component, _, _ := strings.Cut(owner, ".")

			origin, found := chooseModelComponentOrigin(componentOrigins[component])
			if !found {
				return "", false
			}

			if owner != component {
				origin.path += " (generated nested path " + owner + ")"
			}

			return origin.path, true
		}

		operation, found := operations[owner]
		if !found {
			return "", false
		}

		return operation.schemaFile + " (operation " + strings.ToUpper(operation.method) + " " + operation.path +
			", " + kind + " for operationId " + owner + ")", true
	}

	origin, found := chooseModelComponentOrigin(componentOrigins[goType])
	if found {
		return origin.path, true
	}

	owner := ""
	for component := range componentOrigins {
		if strings.HasPrefix(goType, component+"_") && len(component) > len(owner) {
			owner = component
		}
	}

	if owner == "" {
		return "", false
	}

	origin, found = chooseModelComponentOrigin(componentOrigins[owner])
	if !found {
		return "", false
	}

	return origin.path + " (generated nested type " + goType + ")", true
}

func chooseModelComponentOrigin(origins []modelComponentOrigin) (modelComponentOrigin, bool) {
	if len(origins) == 0 {
		return modelComponentOrigin{group: "", path: ""}, false
	}

	slices.SortFunc(origins, func(left, right modelComponentOrigin) int {
		return strings.Compare(left.path, right.path)
	})

	return origins[0], true
}

func parseModelFiles(t *testing.T, root, directory, pattern string) []parsedModelFile {
	t.Helper()

	paths, err := filepath.Glob(filepath.Join(directory, pattern))
	if err != nil {
		t.Fatalf("list generated model files in %s: %v", directory, err)
	}

	slices.Sort(paths)

	files := make([]parsedModelFile, 0, len(paths))

	for _, path := range paths {
		contents, err := os.ReadFile(path) // #nosec G304 -- checked-in model source under repositoryRoot.
		if err != nil {
			t.Fatal(err)
		}

		fileSet := token.NewFileSet()

		file, err := parser.ParseFile(fileSet, path, contents, parser.ParseComments)
		if err != nil {
			t.Fatalf("parse generated model file %s: %v", path, err)
		}

		relative, err := filepath.Rel(root, path)
		if err != nil {
			t.Fatal(err)
		}

		files = append(files, parsedModelFile{
			relative: filepath.ToSlash(relative), fileSet: fileSet, file: file,
		})
	}

	if len(files) == 0 {
		t.Fatalf("no generated model files in %s", directory)
	}

	return files
}

func generatedTypeComment(typeSpec *ast.TypeSpec, general *ast.GenDecl) string {
	if typeSpec.Doc != nil {
		return strings.TrimSpace(typeSpec.Doc.Text())
	}

	if general.Doc != nil {
		return strings.TrimSpace(general.Doc.Text())
	}

	return ""
}

func fileHasRESTResponsibility(t *testing.T, file *ast.File, group string) bool {
	t.Helper()

	generated := generatedFileHasMarker(file, "Code generated by github.com/oapi-codegen/oapi-codegen")
	responsibility := false

	for _, comment := range file.Comments {
		if strings.Contains(comment.Text(), "Responsibility group: "+group+".") {
			responsibility = true
		}
	}

	if !generated || !responsibility {
		t.Fatalf("REST output group %s lacks its pinned generator or responsibility marker", group)
	}

	return true
}

func generatedFileHasMarker(file *ast.File, marker string) bool {
	for _, comment := range file.Comments {
		if strings.Contains(comment.Text(), marker) {
			return true
		}
	}

	return false
}

func exportedModelOperationName(operation string) string {
	if operation == "" {
		return ""
	}

	return strings.ToUpper(operation[:1]) + operation[1:]
}
