// Code generated by tools/protocols/generate_protocol_constants.mjs. DO NOT EDIT.

package protocol

const (
	DeviceKindStickUpMiniPTZ  = "stickup_cam_mini_ptz_v1"
	ConnectionOnline          = "online"
	ConnectionOffline         = "offline"
	PowerModeWired            = "wired"
	LocationResourceLocations = "locations"
	TimelineEventOnDemand     = "on_demand"
	TimelineEventDing         = "ding"
	TimelineEventMotion       = "motion"
	RecordingStatusReady      = "ready"
	TimelineStateCompleted    = "completed"
	HistoryFeedEvent          = "EVENT"
)
