// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

import (
	"encoding/json"
)

type AnonymousSchema_1 uint

const (
	AnonymousSchema_1CameraStarted AnonymousSchema_1 = iota
	AnonymousSchema_1Close
	AnonymousSchema_1Ice
	AnonymousSchema_1Notification
	AnonymousSchema_1Pong
	AnonymousSchema_1PushEvent
	AnonymousSchema_1PushSubscriptionAck
	AnonymousSchema_1Rpc
	AnonymousSchema_1Sdp
	AnonymousSchema_1SessionCreated
)

// Value returns the value of the enum.
func (op AnonymousSchema_1) Value() any {
	if op >= AnonymousSchema_1(len(AnonymousSchema_1Values)) {
		return nil
	}
	return AnonymousSchema_1Values[op]
}

var AnonymousSchema_1Values = []any{"camera_started", "close", "ice", "notification", "pong", "push_event", "push_subscription_ack", "rpc", "sdp", "session_created"}
var ValuesToAnonymousSchema_1 = map[any]AnonymousSchema_1{
	AnonymousSchema_1Values[AnonymousSchema_1CameraStarted]:       AnonymousSchema_1CameraStarted,
	AnonymousSchema_1Values[AnonymousSchema_1Close]:               AnonymousSchema_1Close,
	AnonymousSchema_1Values[AnonymousSchema_1Ice]:                 AnonymousSchema_1Ice,
	AnonymousSchema_1Values[AnonymousSchema_1Notification]:        AnonymousSchema_1Notification,
	AnonymousSchema_1Values[AnonymousSchema_1Pong]:                AnonymousSchema_1Pong,
	AnonymousSchema_1Values[AnonymousSchema_1PushEvent]:           AnonymousSchema_1PushEvent,
	AnonymousSchema_1Values[AnonymousSchema_1PushSubscriptionAck]: AnonymousSchema_1PushSubscriptionAck,
	AnonymousSchema_1Values[AnonymousSchema_1Rpc]:                 AnonymousSchema_1Rpc,
	AnonymousSchema_1Values[AnonymousSchema_1Sdp]:                 AnonymousSchema_1Sdp,
	AnonymousSchema_1Values[AnonymousSchema_1SessionCreated]:      AnonymousSchema_1SessionCreated,
}

func (op *AnonymousSchema_1) UnmarshalJSON(raw []byte) error {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return err
	}
	*op = ValuesToAnonymousSchema_1[v]
	return nil
}

func (op AnonymousSchema_1) MarshalJSON() ([]byte, error) {
	return json.Marshal(op.Value())
}
