// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type PtzContinuousParams struct {
	SessionId            string                 `json:"sessionId" binding:"required"`
	Timestamp            int                    `json:"timestamp" binding:"required"`
	Version              int                    `json:"version" binding:"required"`
	Direction            *PtzDirection          `json:"direction" binding:"required"`
	Speed                float64                `json:"speed" binding:"required"`
	Reason               string                 `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
