// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type PtzContinuousCommandBody struct {
	DoorbotId            int                       `json:"doorbot_id" binding:"required"`
	SessionId            string                    `json:"session_id" binding:"required"`
	Command              *PtzContinuousWireCommand `json:"command" binding:"required"`
	AdditionalProperties map[string]interface{}    `json:"-,omitempty"`
}
