// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type ServerEnvelope struct {
	SignalingInboundDiscriminator `json:"-"`
	PushEventFrame                `json:"-"`
	PushSubscriptionAckFrame      `json:"-"`
	PlaybackAnswerFrame           `json:"-"`
	LiveAnswerFrame               `json:"-"`
	LiveIceFrame                  `json:"-"`
	ServerIceFrame                `json:"-"`
	SessionNotificationFrame      `json:"-"`
	SessionPongFrame              `json:"-"`
	SessionCreatedFrame           `json:"-"`
	ServerCameraStartedFrame      `json:"-"`
	ServerCloseFrame              `json:"-"`
	ServerRpcFrame                `json:"-"`
}
