// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type ServerCloseReason struct {
	Code                 *AnonymousSchema_82    `json:"code,omitempty"`
	Text                 string                 `json:"text,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
