// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type SessionMicrophoneBody struct {
	DoorbotId            int                    `json:"doorbot_id" binding:"required"`
	SessionId            string                 `json:"session_id" binding:"required"`
	Enabled              bool                   `json:"enabled" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
