// Code generated by @asyncapi/modelina. DO NOT EDIT.

package generatedsignaling

type SessionStreamAudioOptionsBody struct {
	DoorbotId    int    `json:"doorbot_id" binding:"required"`
	SessionId    string `json:"session_id" binding:"required"`
	AudioEnabled bool   `json:"audio_enabled" binding:"required"`
}
