// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: authentication.

package rest

import (
	"encoding/json"
	"fmt"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AuthorizationCodeGrantGrantType.
const (
	AuthorizationCode AuthorizationCodeGrantGrantType = "authorization_code"
)

// Valid indicates whether the value is a known member of the AuthorizationCodeGrantGrantType enum.
func (e AuthorizationCodeGrantGrantType) Valid() bool {
	switch e {
	case AuthorizationCode:
		return true
	default:
		return false
	}
}

// Defines values for ClientDeviceModel.
const (
	GoRing ClientDeviceModel = "go-ring"
)

// Valid indicates whether the value is a known member of the ClientDeviceModel enum.
func (e ClientDeviceModel) Valid() bool {
	switch e {
	case GoRing:
		return true
	default:
		return false
	}
}

// Defines values for LegacyPasswordGrantGrantType.
const (
	Password LegacyPasswordGrantGrantType = "password"
)

// Valid indicates whether the value is a known member of the LegacyPasswordGrantGrantType enum.
func (e LegacyPasswordGrantGrantType) Valid() bool {
	switch e {
	case Password:
		return true
	default:
		return false
	}
}

// Defines values for RefreshTokenGrantGrantType.
const (
	RefreshToken RefreshTokenGrantGrantType = "refresh_token"
)

// Valid indicates whether the value is a known member of the RefreshTokenGrantGrantType enum.
func (e RefreshTokenGrantGrantType) Valid() bool {
	switch e {
	case RefreshToken:
		return true
	default:
		return false
	}
}

// Defines values for TwoFactorFormRememberMe.
const (
	False TwoFactorFormRememberMe = "false"
)

// Valid indicates whether the value is a known member of the TwoFactorFormRememberMe enum.
func (e TwoFactorFormRememberMe) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for BeginOrContinueOAuthAuthorizationParamsResponseType.
const (
	Code BeginOrContinueOAuthAuthorizationParamsResponseType = "code"
)

// Valid indicates whether the value is a known member of the BeginOrContinueOAuthAuthorizationParamsResponseType enum.
func (e BeginOrContinueOAuthAuthorizationParamsResponseType) Valid() bool {
	switch e {
	case Code:
		return true
	default:
		return false
	}
}

// Defines values for BeginOrContinueOAuthAuthorizationParamsCodeChallengeMethod.
const (
	S256 BeginOrContinueOAuthAuthorizationParamsCodeChallengeMethod = "S256"
)

// Valid indicates whether the value is a known member of the BeginOrContinueOAuthAuthorizationParamsCodeChallengeMethod enum.
func (e BeginOrContinueOAuthAuthorizationParamsCodeChallengeMethod) Valid() bool {
	switch e {
	case S256:
		return true
	default:
		return false
	}
}

// AuthorizationCodeGrant defines model for AuthorizationCodeGrant.
type AuthorizationCodeGrant struct {
	ClientId     string                          `json:"client_id"`
	Code         string                          `json:"code"`
	CodeVerifier string                          `json:"code_verifier"`
	GrantType    AuthorizationCodeGrantGrantType `json:"grant_type"`
	RedirectUri  string                          `json:"redirect_uri"`
}

// AuthorizationCodeGrantGrantType defines model for AuthorizationCodeGrant.GrantType.
type AuthorizationCodeGrantGrantType string

// ClientDeviceModel defines model for ClientDeviceModel.
type ClientDeviceModel string

// LegacyPasswordGrant defines model for LegacyPasswordGrant.
type LegacyPasswordGrant struct {
	ClientId  string                       `json:"client_id"`
	GrantType LegacyPasswordGrantGrantType `json:"grant_type"`
	Password  string                       `json:"password"`
	Scope     string                       `json:"scope"`
	Username  string                       `json:"username"`
}

// LegacyPasswordGrantGrantType defines model for LegacyPasswordGrant.GrantType.
type LegacyPasswordGrantGrantType string

// OAuthToken defines model for OAuthToken.
type OAuthToken struct {
	AccessToken          string                 `json:"access_token"`
	ExpiresIn            *int                   `json:"expires_in,omitempty"`
	RefreshToken         *string                `json:"refresh_token,omitempty"`
	Scope                *string                `json:"scope,omitempty"`
	TokenType            string                 `json:"token_type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// OAuthTokenGrant Supports authorization-code PKCE, refresh, and a compatibility password grant.
type OAuthTokenGrant struct {
	union json.RawMessage
}

// RefreshTokenGrant defines model for RefreshTokenGrant.
type RefreshTokenGrant struct {
	ClientId     string                     `json:"client_id"`
	GrantType    RefreshTokenGrantGrantType `json:"grant_type"`
	RefreshToken string                     `json:"refresh_token"`
	Scope        string                     `json:"scope"`
}

// RefreshTokenGrantGrantType defines model for RefreshTokenGrant.GrantType.
type RefreshTokenGrantGrantType string

// SignInForm defines model for SignInForm.
type SignInForm struct {
	CsrfToken string `json:"csrf-token"`
	Password  string `json:"password"`
	Username  string `json:"username"`
}

// SignInState defines model for SignInState.
type SignInState struct {
	NextTimeInSecs *int `json:"next_time_in_secs,omitempty"`

	// TsvState Presence indicates two-factor verification is required.
	TsvState             *string                `json:"tsv_state,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// TwoFactorForm defines model for TwoFactorForm.
type TwoFactorForm struct {
	N2faCode   string                  `json:"2fa_code"`
	CsrfToken  string                  `json:"csrf-token"`
	RememberMe TwoFactorFormRememberMe `json:"remember_me"`
}

// TwoFactorFormRememberMe defines model for TwoFactorForm.RememberMe.
type TwoFactorFormRememberMe string

// AuthFailure Explicit escape hatch for fields without observed structure or typed error responses.
type AuthFailure = JsonValue

// RateLimited Explicit escape hatch for fields without observed structure or typed error responses.
type RateLimited = JsonValue

// TwoFactorRequired Explicit escape hatch for fields without observed structure or typed error responses.
type TwoFactorRequired = JsonValue

// BeginOrContinueOAuthAuthorizationParams defines parameters for BeginOrContinueOAuthAuthorization.
type BeginOrContinueOAuthAuthorizationParams struct {
	RedirectUri  *string                                              `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
	ClientId     *string                                              `form:"client_id,omitempty" json:"client_id,omitempty"`
	ResponseType *BeginOrContinueOAuthAuthorizationParamsResponseType `form:"response_type,omitempty" json:"response_type,omitempty"`

	// Prompt The implemented PKCE flow sends login; other OAuth prompts may exist.
	Prompt *string `form:"prompt,omitempty" json:"prompt,omitempty"`
	State  *string `form:"state,omitempty" json:"state,omitempty"`

	// Scope The implemented client requests the client scope.
	Scope               *string                                                     `form:"scope,omitempty" json:"scope,omitempty"`
	CodeChallenge       *string                                                     `form:"code_challenge,omitempty" json:"code_challenge,omitempty"`
	CodeChallengeMethod *BeginOrContinueOAuthAuthorizationParamsCodeChallengeMethod `form:"code_challenge_method,omitempty" json:"code_challenge_method,omitempty"`
	DeviceModel         *ClientDeviceModel                                          `form:"device_model,omitempty" json:"device_model,omitempty"`
	AppVersion          *string                                                     `form:"app_version,omitempty" json:"app_version,omitempty"`

	// DarkMode Boolean serialized as a query string.
	DarkMode        *bool   `form:"dark_mode,omitempty" json:"dark_mode,omitempty"`
	DeviceBrand     *string `form:"device_brand,omitempty" json:"device_brand,omitempty"`
	DeviceOsVersion *string `form:"device_os_version,omitempty" json:"device_os_version,omitempty"`
	AppBrand        *string `form:"app_brand,omitempty" json:"app_brand,omitempty"`
	HardwareId      *string `form:"hardware_id,omitempty" json:"hardware_id,omitempty"`
}

// BeginOrContinueOAuthAuthorizationParamsResponseType defines parameters for BeginOrContinueOAuthAuthorization.
type BeginOrContinueOAuthAuthorizationParamsResponseType string

// BeginOrContinueOAuthAuthorizationParamsCodeChallengeMethod defines parameters for BeginOrContinueOAuthAuthorization.
type BeginOrContinueOAuthAuthorizationParamsCodeChallengeMethod string

// ExchangeOrRefreshOAuthTokenFormdataRequestBody defines body for ExchangeOrRefreshOAuthToken for application/x-www-form-urlencoded ContentType.
type ExchangeOrRefreshOAuthTokenFormdataRequestBody = OAuthTokenGrant

// VerifyOAuthTwoFactorCodeFormdataRequestBody defines body for VerifyOAuthTwoFactorCode for application/x-www-form-urlencoded ContentType.
type VerifyOAuthTwoFactorCodeFormdataRequestBody = TwoFactorForm

// SubmitOAuthCredentialsFormdataRequestBody defines body for SubmitOAuthCredentials for application/x-www-form-urlencoded ContentType.
type SubmitOAuthCredentialsFormdataRequestBody = SignInForm

// Getter for additional properties for OAuthToken. Returns the specified
// element and whether it was found
func (a OAuthToken) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OAuthToken
func (a *OAuthToken) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OAuthToken to handle AdditionalProperties
func (a *OAuthToken) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["expires_in"]; found {
		err = json.Unmarshal(raw, &a.ExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'expires_in': %w", err)
		}
		delete(object, "expires_in")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if raw, found := object["scope"]; found {
		err = json.Unmarshal(raw, &a.Scope)
		if err != nil {
			return fmt.Errorf("error reading 'scope': %w", err)
		}
		delete(object, "scope")
	}

	if raw, found := object["token_type"]; found {
		err = json.Unmarshal(raw, &a.TokenType)
		if err != nil {
			return fmt.Errorf("error reading 'token_type': %w", err)
		}
		delete(object, "token_type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OAuthToken to handle AdditionalProperties
func (a OAuthToken) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["access_token"], err = json.Marshal(a.AccessToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
	}

	if a.ExpiresIn != nil {
		object["expires_in"], err = json.Marshal(a.ExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expires_in': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refresh_token"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
		}
	}

	if a.Scope != nil {
		object["scope"], err = json.Marshal(a.Scope)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scope': %w", err)
		}
	}

	object["token_type"], err = json.Marshal(a.TokenType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token_type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SignInState. Returns the specified
// element and whether it was found
func (a SignInState) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SignInState
func (a *SignInState) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SignInState to handle AdditionalProperties
func (a *SignInState) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["next_time_in_secs"]; found {
		err = json.Unmarshal(raw, &a.NextTimeInSecs)
		if err != nil {
			return fmt.Errorf("error reading 'next_time_in_secs': %w", err)
		}
		delete(object, "next_time_in_secs")
	}

	if raw, found := object["tsv_state"]; found {
		err = json.Unmarshal(raw, &a.TsvState)
		if err != nil {
			return fmt.Errorf("error reading 'tsv_state': %w", err)
		}
		delete(object, "tsv_state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SignInState to handle AdditionalProperties
func (a SignInState) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.NextTimeInSecs != nil {
		object["next_time_in_secs"], err = json.Marshal(a.NextTimeInSecs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'next_time_in_secs': %w", err)
		}
	}

	if a.TsvState != nil {
		object["tsv_state"], err = json.Marshal(a.TsvState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tsv_state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsAuthorizationCodeGrant returns the union data inside the OAuthTokenGrant as a AuthorizationCodeGrant
func (t OAuthTokenGrant) AsAuthorizationCodeGrant() (AuthorizationCodeGrant, error) {
	var body AuthorizationCodeGrant
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAuthorizationCodeGrant overwrites any union data inside the OAuthTokenGrant as the provided AuthorizationCodeGrant
func (t *OAuthTokenGrant) FromAuthorizationCodeGrant(v AuthorizationCodeGrant) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAuthorizationCodeGrant performs a merge with any union data inside the OAuthTokenGrant, using the provided AuthorizationCodeGrant
func (t *OAuthTokenGrant) MergeAuthorizationCodeGrant(v AuthorizationCodeGrant) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRefreshTokenGrant returns the union data inside the OAuthTokenGrant as a RefreshTokenGrant
func (t OAuthTokenGrant) AsRefreshTokenGrant() (RefreshTokenGrant, error) {
	var body RefreshTokenGrant
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRefreshTokenGrant overwrites any union data inside the OAuthTokenGrant as the provided RefreshTokenGrant
func (t *OAuthTokenGrant) FromRefreshTokenGrant(v RefreshTokenGrant) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRefreshTokenGrant performs a merge with any union data inside the OAuthTokenGrant, using the provided RefreshTokenGrant
func (t *OAuthTokenGrant) MergeRefreshTokenGrant(v RefreshTokenGrant) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLegacyPasswordGrant returns the union data inside the OAuthTokenGrant as a LegacyPasswordGrant
func (t OAuthTokenGrant) AsLegacyPasswordGrant() (LegacyPasswordGrant, error) {
	var body LegacyPasswordGrant
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLegacyPasswordGrant overwrites any union data inside the OAuthTokenGrant as the provided LegacyPasswordGrant
func (t *OAuthTokenGrant) FromLegacyPasswordGrant(v LegacyPasswordGrant) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLegacyPasswordGrant performs a merge with any union data inside the OAuthTokenGrant, using the provided LegacyPasswordGrant
func (t *OAuthTokenGrant) MergeLegacyPasswordGrant(v LegacyPasswordGrant) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OAuthTokenGrant) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OAuthTokenGrant) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
