// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: common.

package rest

// Defines values for RingHeaderName.
const (
	Accept        RingHeaderName = "Accept"
	Authorization RingHeaderName = "Authorization"
	ContentType   RingHeaderName = "Content-Type"
	HardwareId    RingHeaderName = "Hardware_id"
	N2faCode      RingHeaderName = "2fa-Code"
	N2faSupport   RingHeaderName = "2fa-Support"
	UserAgent     RingHeaderName = "User-Agent"
)

// Valid indicates whether the value is a known member of the RingHeaderName enum.
func (e RingHeaderName) Valid() bool {
	switch e {
	case Accept:
		return true
	case Authorization:
		return true
	case ContentType:
		return true
	case HardwareId:
		return true
	case N2faCode:
		return true
	case N2faSupport:
		return true
	case UserAgent:
		return true
	default:
		return false
	}
}

// ExtensibleObject defines model for ExtensibleObject.
type ExtensibleObject map[string]JsonValue

// JsonValue Explicit escape hatch for fields without observed structure or typed error responses.
type JsonValue = interface{}

// RingHeaderName Named outbound Ring request headers used by the handwritten adapters.
type RingHeaderName string

// Limit defines model for limit.
type Limit = int

// HTTPFailure Explicit escape hatch for fields without observed structure or typed error responses.
type HTTPFailure = JsonValue

// Json Explicit escape hatch for fields without observed structure or typed error responses.
type Json = JsonValue
