// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: device-settings.

package rest

import (
	"encoding/json"
	"fmt"
)

// ChimeSettings defines model for ChimeSettings.
type ChimeSettings struct {
	// Duration Chime duration in seconds.
	Duration *int  `json:"duration,omitempty"`
	Enable   *bool `json:"enable,omitempty"`

	// Type Historical chime type code is 2; other numeric codes remain valid.
	Type                 *int                   `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceOperationSet Operation names are dynamic; historical entries are empty capability descriptors.
type DeviceOperationSet map[string]map[string]interface{}

// DeviceSettings defines model for DeviceSettings.
type DeviceSettings struct {
	ChimeSettings        *ChimeSettings       `json:"chime_settings,omitempty"`
	MotionSettings       *MotionSettings      `json:"motion_settings,omitempty"`
	PtzSettings          *PTZSettings         `json:"ptz_settings,omitempty"`
	VideoSettings        *VideoSettings       `json:"video_settings,omitempty"`
	VolumeSettings       *VolumeSettings      `json:"volume_settings,omitempty"`
	AdditionalProperties map[string]JsonValue `json:"-"`
}

// DeviceSettingsPatch Extensible wire patch. Historical variants include motion_settings, video_settings, general_settings, and volume_settings. Additional settings may be available for other device types.
type DeviceSettingsPatch struct {
	GeneralSettings      *SettingsObject           `json:"general_settings,omitempty"`
	MotionSettings       *MotionSettingsPatch      `json:"motion_settings,omitempty"`
	VideoSettings        *SettingsObject           `json:"video_settings,omitempty"`
	VolumeSettings       *SettingsObject           `json:"volume_settings,omitempty"`
	AdditionalProperties map[string]SettingsObject `json:"-"`
}

// LiveViewSetting defines model for LiveViewSetting.
type LiveViewSetting struct {
	LiveViewEnabled bool `json:"live_view_enabled"`
}

// LiveViewSettingRequest defines model for LiveViewSettingRequest.
type LiveViewSettingRequest struct {
	Entity LiveViewSetting `json:"entity"`
}

// MotionSettings defines model for MotionSettings.
type MotionSettings struct {
	MotionDetectionEnabled *bool                `json:"motion_detection_enabled,omitempty"`
	AdditionalProperties   map[string]JsonValue `json:"-"`
}

// MotionSettingsPatch defines model for MotionSettingsPatch.
type MotionSettingsPatch struct {
	MotionDetectionEnabled *bool                `json:"motion_detection_enabled,omitempty"`
	AdditionalProperties   map[string]JsonValue `json:"-"`
}

// SettingsObject defines model for SettingsObject.
type SettingsObject map[string]JsonValue

// VolumeSettings defines model for VolumeSettings.
type VolumeSettings struct {
	// DoorbellVolume Doorbell volume level.
	DoorbellVolume *int `json:"doorbell_volume,omitempty"`

	// MicVolume Non-negative device-reported microphone volume; upper bound is not established.
	MicVolume *int `json:"mic_volume,omitempty"`

	// VoiceVolume Non-negative device-reported voice volume; upper bound is not established.
	VoiceVolume          *int                   `json:"voice_volume,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PatchDeviceSettingsJSONRequestBody defines body for PatchDeviceSettings for application/json ContentType.
type PatchDeviceSettingsJSONRequestBody = DeviceSettingsPatch

// SetLiveViewEnabledJSONRequestBody defines body for SetLiveViewEnabled for application/json ContentType.
type SetLiveViewEnabledJSONRequestBody = LiveViewSettingRequest

// Getter for additional properties for ChimeSettings. Returns the specified
// element and whether it was found
func (a ChimeSettings) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ChimeSettings
func (a *ChimeSettings) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ChimeSettings to handle AdditionalProperties
func (a *ChimeSettings) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["duration"]; found {
		err = json.Unmarshal(raw, &a.Duration)
		if err != nil {
			return fmt.Errorf("error reading 'duration': %w", err)
		}
		delete(object, "duration")
	}

	if raw, found := object["enable"]; found {
		err = json.Unmarshal(raw, &a.Enable)
		if err != nil {
			return fmt.Errorf("error reading 'enable': %w", err)
		}
		delete(object, "enable")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ChimeSettings to handle AdditionalProperties
func (a ChimeSettings) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Duration != nil {
		object["duration"], err = json.Marshal(a.Duration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'duration': %w", err)
		}
	}

	if a.Enable != nil {
		object["enable"], err = json.Marshal(a.Enable)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enable': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceSettings. Returns the specified
// element and whether it was found
func (a DeviceSettings) Get(fieldName string) (value JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceSettings
func (a *DeviceSettings) Set(fieldName string, value JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceSettings to handle AdditionalProperties
func (a *DeviceSettings) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["chime_settings"]; found {
		err = json.Unmarshal(raw, &a.ChimeSettings)
		if err != nil {
			return fmt.Errorf("error reading 'chime_settings': %w", err)
		}
		delete(object, "chime_settings")
	}

	if raw, found := object["motion_settings"]; found {
		err = json.Unmarshal(raw, &a.MotionSettings)
		if err != nil {
			return fmt.Errorf("error reading 'motion_settings': %w", err)
		}
		delete(object, "motion_settings")
	}

	if raw, found := object["ptz_settings"]; found {
		err = json.Unmarshal(raw, &a.PtzSettings)
		if err != nil {
			return fmt.Errorf("error reading 'ptz_settings': %w", err)
		}
		delete(object, "ptz_settings")
	}

	if raw, found := object["video_settings"]; found {
		err = json.Unmarshal(raw, &a.VideoSettings)
		if err != nil {
			return fmt.Errorf("error reading 'video_settings': %w", err)
		}
		delete(object, "video_settings")
	}

	if raw, found := object["volume_settings"]; found {
		err = json.Unmarshal(raw, &a.VolumeSettings)
		if err != nil {
			return fmt.Errorf("error reading 'volume_settings': %w", err)
		}
		delete(object, "volume_settings")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceSettings to handle AdditionalProperties
func (a DeviceSettings) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ChimeSettings != nil {
		object["chime_settings"], err = json.Marshal(a.ChimeSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'chime_settings': %w", err)
		}
	}

	if a.MotionSettings != nil {
		object["motion_settings"], err = json.Marshal(a.MotionSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'motion_settings': %w", err)
		}
	}

	if a.PtzSettings != nil {
		object["ptz_settings"], err = json.Marshal(a.PtzSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ptz_settings': %w", err)
		}
	}

	if a.VideoSettings != nil {
		object["video_settings"], err = json.Marshal(a.VideoSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'video_settings': %w", err)
		}
	}

	if a.VolumeSettings != nil {
		object["volume_settings"], err = json.Marshal(a.VolumeSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume_settings': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DeviceSettingsPatch. Returns the specified
// element and whether it was found
func (a DeviceSettingsPatch) Get(fieldName string) (value SettingsObject, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceSettingsPatch
func (a *DeviceSettingsPatch) Set(fieldName string, value SettingsObject) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]SettingsObject)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceSettingsPatch to handle AdditionalProperties
func (a *DeviceSettingsPatch) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["general_settings"]; found {
		err = json.Unmarshal(raw, &a.GeneralSettings)
		if err != nil {
			return fmt.Errorf("error reading 'general_settings': %w", err)
		}
		delete(object, "general_settings")
	}

	if raw, found := object["motion_settings"]; found {
		err = json.Unmarshal(raw, &a.MotionSettings)
		if err != nil {
			return fmt.Errorf("error reading 'motion_settings': %w", err)
		}
		delete(object, "motion_settings")
	}

	if raw, found := object["video_settings"]; found {
		err = json.Unmarshal(raw, &a.VideoSettings)
		if err != nil {
			return fmt.Errorf("error reading 'video_settings': %w", err)
		}
		delete(object, "video_settings")
	}

	if raw, found := object["volume_settings"]; found {
		err = json.Unmarshal(raw, &a.VolumeSettings)
		if err != nil {
			return fmt.Errorf("error reading 'volume_settings': %w", err)
		}
		delete(object, "volume_settings")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]SettingsObject)
		for fieldName, fieldBuf := range object {
			var fieldVal SettingsObject
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceSettingsPatch to handle AdditionalProperties
func (a DeviceSettingsPatch) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.GeneralSettings != nil {
		object["general_settings"], err = json.Marshal(a.GeneralSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'general_settings': %w", err)
		}
	}

	if a.MotionSettings != nil {
		object["motion_settings"], err = json.Marshal(a.MotionSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'motion_settings': %w", err)
		}
	}

	if a.VideoSettings != nil {
		object["video_settings"], err = json.Marshal(a.VideoSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'video_settings': %w", err)
		}
	}

	if a.VolumeSettings != nil {
		object["volume_settings"], err = json.Marshal(a.VolumeSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume_settings': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for MotionSettings. Returns the specified
// element and whether it was found
func (a MotionSettings) Get(fieldName string) (value JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MotionSettings
func (a *MotionSettings) Set(fieldName string, value JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MotionSettings to handle AdditionalProperties
func (a *MotionSettings) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["motion_detection_enabled"]; found {
		err = json.Unmarshal(raw, &a.MotionDetectionEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'motion_detection_enabled': %w", err)
		}
		delete(object, "motion_detection_enabled")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MotionSettings to handle AdditionalProperties
func (a MotionSettings) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MotionDetectionEnabled != nil {
		object["motion_detection_enabled"], err = json.Marshal(a.MotionDetectionEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'motion_detection_enabled': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for MotionSettingsPatch. Returns the specified
// element and whether it was found
func (a MotionSettingsPatch) Get(fieldName string) (value JsonValue, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MotionSettingsPatch
func (a *MotionSettingsPatch) Set(fieldName string, value JsonValue) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]JsonValue)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MotionSettingsPatch to handle AdditionalProperties
func (a *MotionSettingsPatch) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["motion_detection_enabled"]; found {
		err = json.Unmarshal(raw, &a.MotionDetectionEnabled)
		if err != nil {
			return fmt.Errorf("error reading 'motion_detection_enabled': %w", err)
		}
		delete(object, "motion_detection_enabled")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]JsonValue)
		for fieldName, fieldBuf := range object {
			var fieldVal JsonValue
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MotionSettingsPatch to handle AdditionalProperties
func (a MotionSettingsPatch) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MotionDetectionEnabled != nil {
		object["motion_detection_enabled"], err = json.Marshal(a.MotionDetectionEnabled)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'motion_detection_enabled': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VolumeSettings. Returns the specified
// element and whether it was found
func (a VolumeSettings) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VolumeSettings
func (a *VolumeSettings) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VolumeSettings to handle AdditionalProperties
func (a *VolumeSettings) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["doorbell_volume"]; found {
		err = json.Unmarshal(raw, &a.DoorbellVolume)
		if err != nil {
			return fmt.Errorf("error reading 'doorbell_volume': %w", err)
		}
		delete(object, "doorbell_volume")
	}

	if raw, found := object["mic_volume"]; found {
		err = json.Unmarshal(raw, &a.MicVolume)
		if err != nil {
			return fmt.Errorf("error reading 'mic_volume': %w", err)
		}
		delete(object, "mic_volume")
	}

	if raw, found := object["voice_volume"]; found {
		err = json.Unmarshal(raw, &a.VoiceVolume)
		if err != nil {
			return fmt.Errorf("error reading 'voice_volume': %w", err)
		}
		delete(object, "voice_volume")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VolumeSettings to handle AdditionalProperties
func (a VolumeSettings) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DoorbellVolume != nil {
		object["doorbell_volume"], err = json.Marshal(a.DoorbellVolume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'doorbell_volume': %w", err)
		}
	}

	if a.MicVolume != nil {
		object["mic_volume"], err = json.Marshal(a.MicVolume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mic_volume': %w", err)
		}
	}

	if a.VoiceVolume != nil {
		object["voice_volume"], err = json.Marshal(a.VoiceVolume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'voice_volume': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
