// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: device-history.

package rest

import (
	"encoding/json"
	"fmt"
	"time"
)

// DeviceTimeline defines model for DeviceTimeline.
type DeviceTimeline struct {
	Items                []TimelineEvent        `json:"items"`
	PaginationKey        *string                `json:"pagination_key,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HistoryDevices defines model for HistoryDevices.
type HistoryDevices struct {
	Events               []TimelineEvent        `json:"events"`
	Feed                 *[]HistoryFeedItem     `json:"feed,omitempty"`
	PaginationKey        *string                `json:"pagination_key,omitempty"`
	Schema               *string                `json:"schema,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// HistoryFeedItem defines model for HistoryFeedItem.
type HistoryFeedItem struct {
	Id *string `json:"id,omitempty"`

	// Type Historical feed item type is EVENT; other types remain valid.
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// TimelineDevice defines model for TimelineDevice.
type TimelineDevice struct {
	Description          *string                `json:"description,omitempty"`
	Id                   *int64                 `json:"id,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// TimelineEvent defines model for TimelineEvent.
type TimelineEvent struct {
	Device *TimelineDevice `json:"device,omitempty"`

	// DurationMs Event duration in milliseconds.
	DurationMs *int       `json:"duration_ms,omitempty"`
	EndTime    *time.Time `json:"end_time,omitempty"`
	EventId    string     `json:"event_id"`

	// EventType Historical type is on_demand; other event kinds remain valid.
	EventType  string `json:"event_type"`
	IsFavorite *bool  `json:"is_favorite,omitempty"`

	// RecordingStatus Historical recording status is ready; other statuses remain valid.
	RecordingStatus *string   `json:"recording_status,omitempty"`
	Schema          *string   `json:"schema,omitempty"`
	SourceId        *string   `json:"source_id,omitempty"`
	StartTime       time.Time `json:"start_time"`

	// State Historical event state is completed; other states remain valid.
	State                *string                `json:"state,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Capabilities defines model for capabilities.
type Capabilities = string

// EndTime defines model for end_time.
type EndTime = time.Time

// Kind defines model for kind.
type Kind = string

// OlderThan defines model for older_than.
type OlderThan = int64

// Order defines model for order.
type Order = string

// SourceIds defines model for source_ids.
type SourceIds = string

// StartTime defines model for start_time.
type StartTime = time.Time

// GetDeviceTimelineParams defines parameters for GetDeviceTimeline.
type GetDeviceTimelineParams struct {
	// StartTime Inclusive timeline start in RFC 3339 format; requiredness is not established.
	StartTime *StartTime `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime Timeline end in RFC 3339 format; requiredness is not established.
	EndTime *EndTime `form:"end_time,omitempty" json:"end_time,omitempty"`

	// Order Descending order was recorded; other values may be accepted.
	Order *Order `form:"order,omitempty" json:"order,omitempty"`

	// Limit Positive maximum number of results; 20 was recorded.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Capabilities Comma-separated capability tokens. Observed tokens are offline_event, vehicle and ringtercom; future tokens are possible.
	Capabilities *Capabilities `form:"capabilities,omitempty" json:"capabilities,omitempty"`
}

// GetHistoryDevicesParams defines parameters for GetHistoryDevices.
type GetHistoryDevicesParams struct {
	// SourceIds Historical query name; values are syntheticized.
	SourceIds *SourceIds `form:"source_ids,omitempty" json:"source_ids,omitempty"`

	// Capabilities Comma-separated capability tokens. Observed tokens are offline_event, vehicle and ringtercom; future tokens are possible.
	Capabilities *Capabilities `form:"capabilities,omitempty" json:"capabilities,omitempty"`
}

// Getter for additional properties for DeviceTimeline. Returns the specified
// element and whether it was found
func (a DeviceTimeline) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DeviceTimeline
func (a *DeviceTimeline) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DeviceTimeline to handle AdditionalProperties
func (a *DeviceTimeline) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["items"]; found {
		err = json.Unmarshal(raw, &a.Items)
		if err != nil {
			return fmt.Errorf("error reading 'items': %w", err)
		}
		delete(object, "items")
	}

	if raw, found := object["pagination_key"]; found {
		err = json.Unmarshal(raw, &a.PaginationKey)
		if err != nil {
			return fmt.Errorf("error reading 'pagination_key': %w", err)
		}
		delete(object, "pagination_key")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DeviceTimeline to handle AdditionalProperties
func (a DeviceTimeline) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Items != nil {
		object["items"], err = json.Marshal(a.Items)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'items': %w", err)
		}
	}

	if a.PaginationKey != nil {
		object["pagination_key"], err = json.Marshal(a.PaginationKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pagination_key': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HistoryDevices. Returns the specified
// element and whether it was found
func (a HistoryDevices) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HistoryDevices
func (a *HistoryDevices) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HistoryDevices to handle AdditionalProperties
func (a *HistoryDevices) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["events"]; found {
		err = json.Unmarshal(raw, &a.Events)
		if err != nil {
			return fmt.Errorf("error reading 'events': %w", err)
		}
		delete(object, "events")
	}

	if raw, found := object["feed"]; found {
		err = json.Unmarshal(raw, &a.Feed)
		if err != nil {
			return fmt.Errorf("error reading 'feed': %w", err)
		}
		delete(object, "feed")
	}

	if raw, found := object["pagination_key"]; found {
		err = json.Unmarshal(raw, &a.PaginationKey)
		if err != nil {
			return fmt.Errorf("error reading 'pagination_key': %w", err)
		}
		delete(object, "pagination_key")
	}

	if raw, found := object["schema"]; found {
		err = json.Unmarshal(raw, &a.Schema)
		if err != nil {
			return fmt.Errorf("error reading 'schema': %w", err)
		}
		delete(object, "schema")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HistoryDevices to handle AdditionalProperties
func (a HistoryDevices) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Events != nil {
		object["events"], err = json.Marshal(a.Events)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'events': %w", err)
		}
	}

	if a.Feed != nil {
		object["feed"], err = json.Marshal(a.Feed)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'feed': %w", err)
		}
	}

	if a.PaginationKey != nil {
		object["pagination_key"], err = json.Marshal(a.PaginationKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'pagination_key': %w", err)
		}
	}

	if a.Schema != nil {
		object["schema"], err = json.Marshal(a.Schema)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'schema': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for HistoryFeedItem. Returns the specified
// element and whether it was found
func (a HistoryFeedItem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for HistoryFeedItem
func (a *HistoryFeedItem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for HistoryFeedItem to handle AdditionalProperties
func (a *HistoryFeedItem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for HistoryFeedItem to handle AdditionalProperties
func (a HistoryFeedItem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for TimelineDevice. Returns the specified
// element and whether it was found
func (a TimelineDevice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for TimelineDevice
func (a *TimelineDevice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for TimelineDevice to handle AdditionalProperties
func (a *TimelineDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &a.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
		delete(object, "description")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for TimelineDevice to handle AdditionalProperties
func (a TimelineDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Description != nil {
		object["description"], err = json.Marshal(a.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for TimelineEvent. Returns the specified
// element and whether it was found
func (a TimelineEvent) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for TimelineEvent
func (a *TimelineEvent) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for TimelineEvent to handle AdditionalProperties
func (a *TimelineEvent) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["device"]; found {
		err = json.Unmarshal(raw, &a.Device)
		if err != nil {
			return fmt.Errorf("error reading 'device': %w", err)
		}
		delete(object, "device")
	}

	if raw, found := object["duration_ms"]; found {
		err = json.Unmarshal(raw, &a.DurationMs)
		if err != nil {
			return fmt.Errorf("error reading 'duration_ms': %w", err)
		}
		delete(object, "duration_ms")
	}

	if raw, found := object["end_time"]; found {
		err = json.Unmarshal(raw, &a.EndTime)
		if err != nil {
			return fmt.Errorf("error reading 'end_time': %w", err)
		}
		delete(object, "end_time")
	}

	if raw, found := object["event_id"]; found {
		err = json.Unmarshal(raw, &a.EventId)
		if err != nil {
			return fmt.Errorf("error reading 'event_id': %w", err)
		}
		delete(object, "event_id")
	}

	if raw, found := object["event_type"]; found {
		err = json.Unmarshal(raw, &a.EventType)
		if err != nil {
			return fmt.Errorf("error reading 'event_type': %w", err)
		}
		delete(object, "event_type")
	}

	if raw, found := object["is_favorite"]; found {
		err = json.Unmarshal(raw, &a.IsFavorite)
		if err != nil {
			return fmt.Errorf("error reading 'is_favorite': %w", err)
		}
		delete(object, "is_favorite")
	}

	if raw, found := object["recording_status"]; found {
		err = json.Unmarshal(raw, &a.RecordingStatus)
		if err != nil {
			return fmt.Errorf("error reading 'recording_status': %w", err)
		}
		delete(object, "recording_status")
	}

	if raw, found := object["schema"]; found {
		err = json.Unmarshal(raw, &a.Schema)
		if err != nil {
			return fmt.Errorf("error reading 'schema': %w", err)
		}
		delete(object, "schema")
	}

	if raw, found := object["source_id"]; found {
		err = json.Unmarshal(raw, &a.SourceId)
		if err != nil {
			return fmt.Errorf("error reading 'source_id': %w", err)
		}
		delete(object, "source_id")
	}

	if raw, found := object["start_time"]; found {
		err = json.Unmarshal(raw, &a.StartTime)
		if err != nil {
			return fmt.Errorf("error reading 'start_time': %w", err)
		}
		delete(object, "start_time")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for TimelineEvent to handle AdditionalProperties
func (a TimelineEvent) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Device != nil {
		object["device"], err = json.Marshal(a.Device)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'device': %w", err)
		}
	}

	if a.DurationMs != nil {
		object["duration_ms"], err = json.Marshal(a.DurationMs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'duration_ms': %w", err)
		}
	}

	if a.EndTime != nil {
		object["end_time"], err = json.Marshal(a.EndTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'end_time': %w", err)
		}
	}

	object["event_id"], err = json.Marshal(a.EventId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event_id': %w", err)
	}

	object["event_type"], err = json.Marshal(a.EventType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'event_type': %w", err)
	}

	if a.IsFavorite != nil {
		object["is_favorite"], err = json.Marshal(a.IsFavorite)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_favorite': %w", err)
		}
	}

	if a.RecordingStatus != nil {
		object["recording_status"], err = json.Marshal(a.RecordingStatus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'recording_status': %w", err)
		}
	}

	if a.Schema != nil {
		object["schema"], err = json.Marshal(a.Schema)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'schema': %w", err)
		}
	}

	if a.SourceId != nil {
		object["source_id"], err = json.Marshal(a.SourceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'source_id': %w", err)
		}
	}

	object["start_time"], err = json.Marshal(a.StartTime)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'start_time': %w", err)
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
