// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: device-controls.

package rest

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for DeviceCommandCommandName.
const (
	Reboot DeviceCommandCommandName = "reboot"
)

// Valid indicates whether the value is a known member of the DeviceCommandCommandName enum.
func (e DeviceCommandCommandName) Valid() bool {
	switch e {
	case Reboot:
		return true
	default:
		return false
	}
}

// Defines values for TestChimeSoundParamsKind.
const (
	Ding   TestChimeSoundParamsKind = "ding"
	Motion TestChimeSoundParamsKind = "motion"
)

// Valid indicates whether the value is a known member of the TestChimeSoundParamsKind enum.
func (e TestChimeSoundParamsKind) Valid() bool {
	switch e {
	case Ding:
		return true
	case Motion:
		return true
	default:
		return false
	}
}

// Defines values for UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable.
const (
	UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnableN0 UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable = 0
	UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnableN1 UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable = 1
)

// Valid indicates whether the value is a known member of the UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable enum.
func (e UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable) Valid() bool {
	switch e {
	case UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnableN0:
		return true
	case UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnableN1:
		return true
	default:
		return false
	}
}

// DeviceCommand defines model for DeviceCommand.
type DeviceCommand struct {
	CommandName DeviceCommandCommandName `json:"command_name"`
}

// DeviceCommandCommandName defines model for DeviceCommand.CommandName.
type DeviceCommandCommandName string

// SirenStatus defines model for SirenStatus.
type SirenStatus struct {
	// Duration Server-reported siren duration in seconds.
	Duration int       `json:"duration"`
	EndsAt   time.Time `json:"ends_at"`

	// SecondsRemaining Server-reported remaining siren time in seconds.
	SecondsRemaining     int                    `json:"seconds_remaining"`
	StartedAt            time.Time              `json:"started_at"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SirenOn defines model for SirenOn.
type SirenOn = SirenStatus

// SetChimeVolumeParams defines parameters for SetChimeVolume.
type SetChimeVolumeParams struct {
	ChimeDescription    string `form:"chime[description]" json:"chime[description]"`
	ChimeSettingsVolume int    `form:"chime[settings][volume]" json:"chime[settings][volume]"`
}

// TestChimeSoundParams defines parameters for TestChimeSound.
type TestChimeSoundParams struct {
	Kind TestChimeSoundParamsKind `form:"kind" json:"kind"`
}

// TestChimeSoundParamsKind defines parameters for TestChimeSound.
type TestChimeSoundParamsKind string

// UpdateLegacyDoorbotControlsParams defines parameters for UpdateLegacyDoorbotControls.
type UpdateLegacyDoorbotControlsParams struct {
	DoorbotDescription                   string                                                               `form:"doorbot[description]" json:"doorbot[description]"`
	DoorbotSettingsDoorbellVolume        *int                                                                 `form:"doorbot[settings][doorbell_volume],omitempty" json:"doorbot[settings][doorbell_volume],omitempty"`
	DoorbotSettingsChimeSettingsType     *int                                                                 `form:"doorbot[settings][chime_settings][type],omitempty" json:"doorbot[settings][chime_settings][type],omitempty"`
	DoorbotSettingsChimeSettingsEnable   *UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable `form:"doorbot[settings][chime_settings][enable],omitempty" json:"doorbot[settings][chime_settings][enable],omitempty"`
	DoorbotSettingsChimeSettingsDuration *int                                                                 `form:"doorbot[settings][chime_settings][duration],omitempty" json:"doorbot[settings][chime_settings][duration],omitempty"`
}

// UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable defines parameters for UpdateLegacyDoorbotControls.
type UpdateLegacyDoorbotControlsParamsDoorbotSettingsChimeSettingsEnable int

// SendDeviceCommandJSONRequestBody defines body for SendDeviceCommand for application/json ContentType.
type SendDeviceCommandJSONRequestBody = DeviceCommand

// UnlockIntercomJSONRequestBody defines body for UnlockIntercom for application/json ContentType.
type UnlockIntercomJSONRequestBody = IntercomUnlockCommand

// Getter for additional properties for SirenStatus. Returns the specified
// element and whether it was found
func (a SirenStatus) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SirenStatus
func (a *SirenStatus) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SirenStatus to handle AdditionalProperties
func (a *SirenStatus) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["duration"]; found {
		err = json.Unmarshal(raw, &a.Duration)
		if err != nil {
			return fmt.Errorf("error reading 'duration': %w", err)
		}
		delete(object, "duration")
	}

	if raw, found := object["ends_at"]; found {
		err = json.Unmarshal(raw, &a.EndsAt)
		if err != nil {
			return fmt.Errorf("error reading 'ends_at': %w", err)
		}
		delete(object, "ends_at")
	}

	if raw, found := object["seconds_remaining"]; found {
		err = json.Unmarshal(raw, &a.SecondsRemaining)
		if err != nil {
			return fmt.Errorf("error reading 'seconds_remaining': %w", err)
		}
		delete(object, "seconds_remaining")
	}

	if raw, found := object["started_at"]; found {
		err = json.Unmarshal(raw, &a.StartedAt)
		if err != nil {
			return fmt.Errorf("error reading 'started_at': %w", err)
		}
		delete(object, "started_at")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SirenStatus to handle AdditionalProperties
func (a SirenStatus) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["duration"], err = json.Marshal(a.Duration)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'duration': %w", err)
	}

	object["ends_at"], err = json.Marshal(a.EndsAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ends_at': %w", err)
	}

	object["seconds_remaining"], err = json.Marshal(a.SecondsRemaining)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'seconds_remaining': %w", err)
	}

	object["started_at"], err = json.Marshal(a.StartedAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'started_at': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
