// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: intercom.

package rest

// Defines values for IntercomUnlockCommandCommandName.
const (
	DeviceRpc IntercomUnlockCommandCommandName = "device_rpc"
)

// Valid indicates whether the value is a known member of the IntercomUnlockCommandCommandName enum.
func (e IntercomUnlockCommandCommandName) Valid() bool {
	switch e {
	case DeviceRpc:
		return true
	default:
		return false
	}
}

// Defines values for IntercomUnlockParamsDoorId.
const (
	IntercomUnlockParamsDoorIdN0 IntercomUnlockParamsDoorId = 0
)

// Valid indicates whether the value is a known member of the IntercomUnlockParamsDoorId enum.
func (e IntercomUnlockParamsDoorId) Valid() bool {
	switch e {
	case IntercomUnlockParamsDoorIdN0:
		return true
	default:
		return false
	}
}

// Defines values for IntercomUnlockParamsUserId.
const (
	IntercomUnlockParamsUserIdN0 IntercomUnlockParamsUserId = 0
)

// Valid indicates whether the value is a known member of the IntercomUnlockParamsUserId enum.
func (e IntercomUnlockParamsUserId) Valid() bool {
	switch e {
	case IntercomUnlockParamsUserIdN0:
		return true
	default:
		return false
	}
}

// Defines values for IntercomUnlockRPCJsonrpc.
const (
	N20 IntercomUnlockRPCJsonrpc = "2.0"
)

// Valid indicates whether the value is a known member of the IntercomUnlockRPCJsonrpc enum.
func (e IntercomUnlockRPCJsonrpc) Valid() bool {
	switch e {
	case N20:
		return true
	default:
		return false
	}
}

// Defines values for IntercomUnlockRPCMethod.
const (
	UnlockDoor IntercomUnlockRPCMethod = "unlock_door"
)

// Valid indicates whether the value is a known member of the IntercomUnlockRPCMethod enum.
func (e IntercomUnlockRPCMethod) Valid() bool {
	switch e {
	case UnlockDoor:
		return true
	default:
		return false
	}
}

// IntercomUnlockCommand defines model for IntercomUnlockCommand.
type IntercomUnlockCommand struct {
	CommandName IntercomUnlockCommandCommandName `json:"command_name"`
	Request     IntercomUnlockRPC                `json:"request"`
}

// IntercomUnlockCommandCommandName defines model for IntercomUnlockCommand.CommandName.
type IntercomUnlockCommandCommandName string

// IntercomUnlockParams defines model for IntercomUnlockParams.
type IntercomUnlockParams struct {
	DoorId IntercomUnlockParamsDoorId `json:"door_id"`
	UserId IntercomUnlockParamsUserId `json:"user_id"`
}

// IntercomUnlockParamsDoorId defines model for IntercomUnlockParams.DoorId.
type IntercomUnlockParamsDoorId int

// IntercomUnlockParamsUserId defines model for IntercomUnlockParams.UserId.
type IntercomUnlockParamsUserId int

// IntercomUnlockRPC defines model for IntercomUnlockRPC.
type IntercomUnlockRPC struct {
	Jsonrpc IntercomUnlockRPCJsonrpc `json:"jsonrpc"`
	Method  IntercomUnlockRPCMethod  `json:"method"`
	Params  IntercomUnlockParams     `json:"params"`
}

// IntercomUnlockRPCJsonrpc defines model for IntercomUnlockRPC.Jsonrpc.
type IntercomUnlockRPCJsonrpc string

// IntercomUnlockRPCMethod defines model for IntercomUnlockRPC.Method.
type IntercomUnlockRPCMethod string
