// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: locations.

package rest

import (
	"encoding/json"
	"fmt"
	"time"
)

// GeoCoordinates defines model for GeoCoordinates.
type GeoCoordinates struct {
	Latitude             *float32               `json:"latitude,omitempty"`
	Longitude            *float32               `json:"longitude,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationAddress defines model for LocationAddress.
type LocationAddress struct {
	Address1             *string                `json:"address1,omitempty"`
	Address2             *string                `json:"address2,omitempty"`
	City                 *string                `json:"city,omitempty"`
	Country              *string                `json:"country,omitempty"`
	State                *string                `json:"state,omitempty"`
	Timezone             *string                `json:"timezone,omitempty"`
	ZipCode              *string                `json:"zip_code,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationAttributes defines model for LocationAttributes.
type LocationAttributes struct {
	City                 *string                `json:"city,omitempty"`
	Country              *string                `json:"country,omitempty"`
	Latitude             *float32               `json:"latitude,omitempty"`
	Longitude            *float32               `json:"longitude,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	State                *string                `json:"state,omitempty"`
	TimeZone             *string                `json:"time_zone,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationDetail defines model for LocationDetail.
type LocationDetail struct {
	Data                 LocationResource       `json:"data"`
	Included             *[]LocationResource    `json:"included,omitempty"`
	Meta                 *LocationMeta          `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationGroup Group entries were empty or null in the historical fixture; identity fields follow the baseline fixtures.
type LocationGroup struct {
	Id                   *string                `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationGroupDevices defines model for LocationGroupDevices.
type LocationGroupDevices struct {
	Groups               []LocationGroup        `json:"groups"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationGroups defines model for LocationGroups.
type LocationGroups struct {
	DeviceGroups         *[]LocationGroup       `json:"device_groups,omitempty"`
	IsOwner              *bool                  `json:"is_owner,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationList defines model for LocationList.
type LocationList struct {
	LocationOperationSets *map[string]DeviceOperationSet `json:"location_operation_sets,omitempty"`
	UserLocations         []LocationSummary              `json:"user_locations"`
	AdditionalProperties  map[string]interface{}         `json:"-"`
}

// LocationMeta defines model for LocationMeta.
type LocationMeta struct {
	Time                 *time.Time             `json:"time,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationResource defines model for LocationResource.
type LocationResource struct {
	Attributes           *LocationAttributes    `json:"attributes,omitempty"`
	Id                   string                 `json:"id"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LocationSummary defines model for LocationSummary.
type LocationSummary struct {
	Address              *LocationAddress       `json:"address,omitempty"`
	GeoCoordinates       *GeoCoordinates        `json:"geo_coordinates,omitempty"`
	IsOwner              *bool                  `json:"is_owner,omitempty"`
	LocationId           string                 `json:"location_id"`
	LocationType         *string                `json:"location_type,omitempty"`
	Name                 string                 `json:"name"`
	OwnerId              *int64                 `json:"owner_id,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Include defines model for include.
type Include = string

// LocationId defines model for location_id.
type LocationId = string

// GetLocationParams defines parameters for GetLocation.
type GetLocationParams struct {
	// Include Comma-separated location expansions. Observed tokens are capabilities, presentation and status; future tokens are possible.
	Include *Include `form:"include,omitempty" json:"include,omitempty"`
}

// Getter for additional properties for GeoCoordinates. Returns the specified
// element and whether it was found
func (a GeoCoordinates) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GeoCoordinates
func (a *GeoCoordinates) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GeoCoordinates to handle AdditionalProperties
func (a *GeoCoordinates) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["latitude"]; found {
		err = json.Unmarshal(raw, &a.Latitude)
		if err != nil {
			return fmt.Errorf("error reading 'latitude': %w", err)
		}
		delete(object, "latitude")
	}

	if raw, found := object["longitude"]; found {
		err = json.Unmarshal(raw, &a.Longitude)
		if err != nil {
			return fmt.Errorf("error reading 'longitude': %w", err)
		}
		delete(object, "longitude")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GeoCoordinates to handle AdditionalProperties
func (a GeoCoordinates) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Latitude != nil {
		object["latitude"], err = json.Marshal(a.Latitude)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'latitude': %w", err)
		}
	}

	if a.Longitude != nil {
		object["longitude"], err = json.Marshal(a.Longitude)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'longitude': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationAddress. Returns the specified
// element and whether it was found
func (a LocationAddress) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationAddress
func (a *LocationAddress) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationAddress to handle AdditionalProperties
func (a *LocationAddress) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["address1"]; found {
		err = json.Unmarshal(raw, &a.Address1)
		if err != nil {
			return fmt.Errorf("error reading 'address1': %w", err)
		}
		delete(object, "address1")
	}

	if raw, found := object["address2"]; found {
		err = json.Unmarshal(raw, &a.Address2)
		if err != nil {
			return fmt.Errorf("error reading 'address2': %w", err)
		}
		delete(object, "address2")
	}

	if raw, found := object["city"]; found {
		err = json.Unmarshal(raw, &a.City)
		if err != nil {
			return fmt.Errorf("error reading 'city': %w", err)
		}
		delete(object, "city")
	}

	if raw, found := object["country"]; found {
		err = json.Unmarshal(raw, &a.Country)
		if err != nil {
			return fmt.Errorf("error reading 'country': %w", err)
		}
		delete(object, "country")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["timezone"]; found {
		err = json.Unmarshal(raw, &a.Timezone)
		if err != nil {
			return fmt.Errorf("error reading 'timezone': %w", err)
		}
		delete(object, "timezone")
	}

	if raw, found := object["zip_code"]; found {
		err = json.Unmarshal(raw, &a.ZipCode)
		if err != nil {
			return fmt.Errorf("error reading 'zip_code': %w", err)
		}
		delete(object, "zip_code")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationAddress to handle AdditionalProperties
func (a LocationAddress) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Address1 != nil {
		object["address1"], err = json.Marshal(a.Address1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'address1': %w", err)
		}
	}

	if a.Address2 != nil {
		object["address2"], err = json.Marshal(a.Address2)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'address2': %w", err)
		}
	}

	if a.City != nil {
		object["city"], err = json.Marshal(a.City)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'city': %w", err)
		}
	}

	if a.Country != nil {
		object["country"], err = json.Marshal(a.Country)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'country': %w", err)
		}
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	if a.Timezone != nil {
		object["timezone"], err = json.Marshal(a.Timezone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timezone': %w", err)
		}
	}

	if a.ZipCode != nil {
		object["zip_code"], err = json.Marshal(a.ZipCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'zip_code': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationAttributes. Returns the specified
// element and whether it was found
func (a LocationAttributes) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationAttributes
func (a *LocationAttributes) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationAttributes to handle AdditionalProperties
func (a *LocationAttributes) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["city"]; found {
		err = json.Unmarshal(raw, &a.City)
		if err != nil {
			return fmt.Errorf("error reading 'city': %w", err)
		}
		delete(object, "city")
	}

	if raw, found := object["country"]; found {
		err = json.Unmarshal(raw, &a.Country)
		if err != nil {
			return fmt.Errorf("error reading 'country': %w", err)
		}
		delete(object, "country")
	}

	if raw, found := object["latitude"]; found {
		err = json.Unmarshal(raw, &a.Latitude)
		if err != nil {
			return fmt.Errorf("error reading 'latitude': %w", err)
		}
		delete(object, "latitude")
	}

	if raw, found := object["longitude"]; found {
		err = json.Unmarshal(raw, &a.Longitude)
		if err != nil {
			return fmt.Errorf("error reading 'longitude': %w", err)
		}
		delete(object, "longitude")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["time_zone"]; found {
		err = json.Unmarshal(raw, &a.TimeZone)
		if err != nil {
			return fmt.Errorf("error reading 'time_zone': %w", err)
		}
		delete(object, "time_zone")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationAttributes to handle AdditionalProperties
func (a LocationAttributes) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.City != nil {
		object["city"], err = json.Marshal(a.City)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'city': %w", err)
		}
	}

	if a.Country != nil {
		object["country"], err = json.Marshal(a.Country)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'country': %w", err)
		}
	}

	if a.Latitude != nil {
		object["latitude"], err = json.Marshal(a.Latitude)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'latitude': %w", err)
		}
	}

	if a.Longitude != nil {
		object["longitude"], err = json.Marshal(a.Longitude)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'longitude': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	if a.TimeZone != nil {
		object["time_zone"], err = json.Marshal(a.TimeZone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'time_zone': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationDetail. Returns the specified
// element and whether it was found
func (a LocationDetail) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationDetail
func (a *LocationDetail) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationDetail to handle AdditionalProperties
func (a *LocationDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["included"]; found {
		err = json.Unmarshal(raw, &a.Included)
		if err != nil {
			return fmt.Errorf("error reading 'included': %w", err)
		}
		delete(object, "included")
	}

	if raw, found := object["meta"]; found {
		err = json.Unmarshal(raw, &a.Meta)
		if err != nil {
			return fmt.Errorf("error reading 'meta': %w", err)
		}
		delete(object, "meta")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationDetail to handle AdditionalProperties
func (a LocationDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["data"], err = json.Marshal(a.Data)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'data': %w", err)
	}

	if a.Included != nil {
		object["included"], err = json.Marshal(a.Included)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'included': %w", err)
		}
	}

	if a.Meta != nil {
		object["meta"], err = json.Marshal(a.Meta)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'meta': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationGroup. Returns the specified
// element and whether it was found
func (a LocationGroup) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationGroup
func (a *LocationGroup) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationGroup to handle AdditionalProperties
func (a *LocationGroup) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationGroup to handle AdditionalProperties
func (a LocationGroup) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationGroupDevices. Returns the specified
// element and whether it was found
func (a LocationGroupDevices) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationGroupDevices
func (a *LocationGroupDevices) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationGroupDevices to handle AdditionalProperties
func (a *LocationGroupDevices) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["groups"]; found {
		err = json.Unmarshal(raw, &a.Groups)
		if err != nil {
			return fmt.Errorf("error reading 'groups': %w", err)
		}
		delete(object, "groups")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationGroupDevices to handle AdditionalProperties
func (a LocationGroupDevices) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Groups != nil {
		object["groups"], err = json.Marshal(a.Groups)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'groups': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationGroups. Returns the specified
// element and whether it was found
func (a LocationGroups) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationGroups
func (a *LocationGroups) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationGroups to handle AdditionalProperties
func (a *LocationGroups) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["device_groups"]; found {
		err = json.Unmarshal(raw, &a.DeviceGroups)
		if err != nil {
			return fmt.Errorf("error reading 'device_groups': %w", err)
		}
		delete(object, "device_groups")
	}

	if raw, found := object["is_owner"]; found {
		err = json.Unmarshal(raw, &a.IsOwner)
		if err != nil {
			return fmt.Errorf("error reading 'is_owner': %w", err)
		}
		delete(object, "is_owner")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationGroups to handle AdditionalProperties
func (a LocationGroups) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DeviceGroups != nil {
		object["device_groups"], err = json.Marshal(a.DeviceGroups)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'device_groups': %w", err)
		}
	}

	if a.IsOwner != nil {
		object["is_owner"], err = json.Marshal(a.IsOwner)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_owner': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationList. Returns the specified
// element and whether it was found
func (a LocationList) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationList
func (a *LocationList) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationList to handle AdditionalProperties
func (a *LocationList) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["location_operation_sets"]; found {
		err = json.Unmarshal(raw, &a.LocationOperationSets)
		if err != nil {
			return fmt.Errorf("error reading 'location_operation_sets': %w", err)
		}
		delete(object, "location_operation_sets")
	}

	if raw, found := object["user_locations"]; found {
		err = json.Unmarshal(raw, &a.UserLocations)
		if err != nil {
			return fmt.Errorf("error reading 'user_locations': %w", err)
		}
		delete(object, "user_locations")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationList to handle AdditionalProperties
func (a LocationList) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.LocationOperationSets != nil {
		object["location_operation_sets"], err = json.Marshal(a.LocationOperationSets)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location_operation_sets': %w", err)
		}
	}

	if a.UserLocations != nil {
		object["user_locations"], err = json.Marshal(a.UserLocations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'user_locations': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationMeta. Returns the specified
// element and whether it was found
func (a LocationMeta) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationMeta
func (a *LocationMeta) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationMeta to handle AdditionalProperties
func (a *LocationMeta) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["time"]; found {
		err = json.Unmarshal(raw, &a.Time)
		if err != nil {
			return fmt.Errorf("error reading 'time': %w", err)
		}
		delete(object, "time")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationMeta to handle AdditionalProperties
func (a LocationMeta) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Time != nil {
		object["time"], err = json.Marshal(a.Time)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'time': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationResource. Returns the specified
// element and whether it was found
func (a LocationResource) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationResource
func (a *LocationResource) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationResource to handle AdditionalProperties
func (a *LocationResource) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attributes"]; found {
		err = json.Unmarshal(raw, &a.Attributes)
		if err != nil {
			return fmt.Errorf("error reading 'attributes': %w", err)
		}
		delete(object, "attributes")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationResource to handle AdditionalProperties
func (a LocationResource) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Attributes != nil {
		object["attributes"], err = json.Marshal(a.Attributes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attributes': %w", err)
		}
	}

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LocationSummary. Returns the specified
// element and whether it was found
func (a LocationSummary) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LocationSummary
func (a *LocationSummary) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LocationSummary to handle AdditionalProperties
func (a *LocationSummary) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["address"]; found {
		err = json.Unmarshal(raw, &a.Address)
		if err != nil {
			return fmt.Errorf("error reading 'address': %w", err)
		}
		delete(object, "address")
	}

	if raw, found := object["geo_coordinates"]; found {
		err = json.Unmarshal(raw, &a.GeoCoordinates)
		if err != nil {
			return fmt.Errorf("error reading 'geo_coordinates': %w", err)
		}
		delete(object, "geo_coordinates")
	}

	if raw, found := object["is_owner"]; found {
		err = json.Unmarshal(raw, &a.IsOwner)
		if err != nil {
			return fmt.Errorf("error reading 'is_owner': %w", err)
		}
		delete(object, "is_owner")
	}

	if raw, found := object["location_id"]; found {
		err = json.Unmarshal(raw, &a.LocationId)
		if err != nil {
			return fmt.Errorf("error reading 'location_id': %w", err)
		}
		delete(object, "location_id")
	}

	if raw, found := object["location_type"]; found {
		err = json.Unmarshal(raw, &a.LocationType)
		if err != nil {
			return fmt.Errorf("error reading 'location_type': %w", err)
		}
		delete(object, "location_type")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["owner_id"]; found {
		err = json.Unmarshal(raw, &a.OwnerId)
		if err != nil {
			return fmt.Errorf("error reading 'owner_id': %w", err)
		}
		delete(object, "owner_id")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LocationSummary to handle AdditionalProperties
func (a LocationSummary) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Address != nil {
		object["address"], err = json.Marshal(a.Address)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'address': %w", err)
		}
	}

	if a.GeoCoordinates != nil {
		object["geo_coordinates"], err = json.Marshal(a.GeoCoordinates)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'geo_coordinates': %w", err)
		}
	}

	if a.IsOwner != nil {
		object["is_owner"], err = json.Marshal(a.IsOwner)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'is_owner': %w", err)
		}
	}

	object["location_id"], err = json.Marshal(a.LocationId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'location_id': %w", err)
	}

	if a.LocationType != nil {
		object["location_type"], err = json.Marshal(a.LocationType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location_type': %w", err)
		}
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.OwnerId != nil {
		object["owner_id"], err = json.Marshal(a.OwnerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'owner_id': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
