// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: notifications.

package rest

// Defines values for PushDeviceMetadataPnDictVersion.
const (
	N200 PushDeviceMetadataPnDictVersion = "2.0.0"
)

// Valid indicates whether the value is a known member of the PushDeviceMetadataPnDictVersion enum.
func (e PushDeviceMetadataPnDictVersion) Valid() bool {
	switch e {
	case N200:
		return true
	default:
		return false
	}
}

// Defines values for PushDeviceMetadataPnService.
const (
	Fcm PushDeviceMetadataPnService = "fcm"
)

// Valid indicates whether the value is a known member of the PushDeviceMetadataPnService enum.
func (e PushDeviceMetadataPnService) Valid() bool {
	switch e {
	case Fcm:
		return true
	default:
		return false
	}
}

// Defines values for PushDeviceRegistrationDeviceOs.
const (
	PushDeviceRegistrationDeviceOsAndroid PushDeviceRegistrationDeviceOs = "android"
)

// Valid indicates whether the value is a known member of the PushDeviceRegistrationDeviceOs enum.
func (e PushDeviceRegistrationDeviceOs) Valid() bool {
	switch e {
	case PushDeviceRegistrationDeviceOsAndroid:
		return true
	default:
		return false
	}
}

// PushDeviceMetadata defines model for PushDeviceMetadata.
type PushDeviceMetadata struct {
	ApiVersion    *int                            `json:"api_version,omitempty"`
	DeviceModel   *ClientDeviceModel              `json:"device_model,omitempty"`
	PnDictVersion PushDeviceMetadataPnDictVersion `json:"pn_dict_version"`
	PnService     PushDeviceMetadataPnService     `json:"pn_service"`
}

// PushDeviceMetadataPnDictVersion defines model for PushDeviceMetadata.PnDictVersion.
type PushDeviceMetadataPnDictVersion string

// PushDeviceMetadataPnService defines model for PushDeviceMetadata.PnService.
type PushDeviceMetadataPnService string

// PushDeviceRegistration defines model for PushDeviceRegistration.
type PushDeviceRegistration struct {
	Device PushDeviceRegistrationDevice `json:"device"`
}

// PushDeviceRegistrationDevice defines model for PushDeviceRegistrationDevice.
type PushDeviceRegistrationDevice struct {
	Metadata              PushDeviceMetadata             `json:"metadata"`
	Os                    PushDeviceRegistrationDeviceOs `json:"os"`
	PushNotificationToken string                         `json:"push_notification_token"`
}

// PushDeviceRegistrationDeviceOs defines model for PushDeviceRegistrationDevice.Os.
type PushDeviceRegistrationDeviceOs string

// RegisterPushDeviceJSONRequestBody defines body for RegisterPushDevice for application/json ContentType.
type RegisterPushDeviceJSONRequestBody = PushDeviceRegistration
