// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: sessions.

package rest

import (
	"encoding/json"
	"fmt"
)

// Defines values for ClientSessionRegistrationDeviceMetadataApiVersion.
const (
	N11 ClientSessionRegistrationDeviceMetadataApiVersion = 11
)

// Valid indicates whether the value is a known member of the ClientSessionRegistrationDeviceMetadataApiVersion enum.
func (e ClientSessionRegistrationDeviceMetadataApiVersion) Valid() bool {
	switch e {
	case N11:
		return true
	default:
		return false
	}
}

// Defines values for ClientSessionRegistrationDeviceOs.
const (
	ClientSessionRegistrationDeviceOsAndroid ClientSessionRegistrationDeviceOs = "android"
)

// Valid indicates whether the value is a known member of the ClientSessionRegistrationDeviceOs enum.
func (e ClientSessionRegistrationDeviceOs) Valid() bool {
	switch e {
	case ClientSessionRegistrationDeviceOsAndroid:
		return true
	default:
		return false
	}
}

// ClientSessionRegistration defines model for ClientSessionRegistration.
type ClientSessionRegistration struct {
	Device               ClientSessionRegistration_Device `json:"device"`
	AdditionalProperties map[string]interface{}           `json:"-"`
}

// ClientSessionRegistrationDeviceMetadataApiVersion defines model for ClientSessionRegistration.Device.Metadata.ApiVersion.
type ClientSessionRegistrationDeviceMetadataApiVersion int

// ClientSessionRegistration_Device_Metadata defines model for ClientSessionRegistration.Device.Metadata.
type ClientSessionRegistration_Device_Metadata struct {
	ApiVersion           ClientSessionRegistrationDeviceMetadataApiVersion `json:"api_version"`
	DeviceModel          ClientDeviceModel                                 `json:"device_model"`
	AdditionalProperties map[string]interface{}                            `json:"-"`
}

// ClientSessionRegistrationDeviceOs defines model for ClientSessionRegistration.Device.Os.
type ClientSessionRegistrationDeviceOs string

// ClientSessionRegistration_Device defines model for ClientSessionRegistration.Device.
type ClientSessionRegistration_Device struct {
	HardwareId           string                                    `json:"hardware_id"`
	Metadata             ClientSessionRegistration_Device_Metadata `json:"metadata"`
	Os                   ClientSessionRegistrationDeviceOs         `json:"os"`
	AdditionalProperties map[string]interface{}                    `json:"-"`
}

// RegisterClientSessionJSONRequestBody defines body for RegisterClientSession for application/json ContentType.
type RegisterClientSessionJSONRequestBody = ClientSessionRegistration

// Getter for additional properties for ClientSessionRegistration. Returns the specified
// element and whether it was found
func (a ClientSessionRegistration) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ClientSessionRegistration
func (a *ClientSessionRegistration) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClientSessionRegistration to handle AdditionalProperties
func (a *ClientSessionRegistration) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["device"]; found {
		err = json.Unmarshal(raw, &a.Device)
		if err != nil {
			return fmt.Errorf("error reading 'device': %w", err)
		}
		delete(object, "device")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClientSessionRegistration to handle AdditionalProperties
func (a ClientSessionRegistration) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["device"], err = json.Marshal(a.Device)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'device': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ClientSessionRegistration_Device_Metadata. Returns the specified
// element and whether it was found
func (a ClientSessionRegistration_Device_Metadata) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ClientSessionRegistration_Device_Metadata
func (a *ClientSessionRegistration_Device_Metadata) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClientSessionRegistration_Device_Metadata to handle AdditionalProperties
func (a *ClientSessionRegistration_Device_Metadata) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["device_model"]; found {
		err = json.Unmarshal(raw, &a.DeviceModel)
		if err != nil {
			return fmt.Errorf("error reading 'device_model': %w", err)
		}
		delete(object, "device_model")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClientSessionRegistration_Device_Metadata to handle AdditionalProperties
func (a ClientSessionRegistration_Device_Metadata) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	object["device_model"], err = json.Marshal(a.DeviceModel)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'device_model': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ClientSessionRegistration_Device. Returns the specified
// element and whether it was found
func (a ClientSessionRegistration_Device) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ClientSessionRegistration_Device
func (a *ClientSessionRegistration_Device) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClientSessionRegistration_Device to handle AdditionalProperties
func (a *ClientSessionRegistration_Device) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["hardware_id"]; found {
		err = json.Unmarshal(raw, &a.HardwareId)
		if err != nil {
			return fmt.Errorf("error reading 'hardware_id': %w", err)
		}
		delete(object, "hardware_id")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["os"]; found {
		err = json.Unmarshal(raw, &a.Os)
		if err != nil {
			return fmt.Errorf("error reading 'os': %w", err)
		}
		delete(object, "os")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClientSessionRegistration_Device to handle AdditionalProperties
func (a ClientSessionRegistration_Device) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["hardware_id"], err = json.Marshal(a.HardwareId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'hardware_id': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	object["os"], err = json.Marshal(a.Os)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'os': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
