// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: signaling.

package rest

import (
	"encoding/json"
	"fmt"
)

// CapturedTickets defines model for CapturedTickets.
type CapturedTickets struct {
	Assets               *[]JsonValue           `json:"assets,omitempty"`
	Host                 string                 `json:"host"`
	SubscriptionTopics   *[]string              `json:"subscriptionTopics,omitempty"`
	Ticket               string                 `json:"ticket"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// LegacySignalingTicket defines model for LegacySignalingTicket.
type LegacySignalingTicket struct {
	Ticket               string                 `json:"ticket"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AllowUserOnly defines model for allowUserOnly.
type AllowUserOnly = bool

// EnableExtendedEmergencyCellUsage defines model for enableExtendedEmergencyCellUsage.
type EnableExtendedEmergencyCellUsage = bool

// LocationID defines model for locationID.
type LocationID = string

// LocationSubscription defines model for locationSubscription.
type LocationSubscription = string

// RequestedTransport defines model for requestedTransport.
type RequestedTransport = string

// GetCapturedLocationTicketsParams defines parameters for GetCapturedLocationTickets.
type GetCapturedLocationTicketsParams struct {
	// AllowUserOnly Boolean encoded as a query string; false was recorded.
	AllowUserOnly        *AllowUserOnly        `form:"allowUserOnly,omitempty" json:"allowUserOnly,omitempty"`
	LocationID           *LocationID           `form:"locationID,omitempty" json:"locationID,omitempty"`
	LocationSubscription *LocationSubscription `form:"locationSubscription,omitempty" json:"locationSubscription,omitempty"`

	// EnableExtendedEmergencyCellUsage Boolean encoded as a query string; true was recorded.
	EnableExtendedEmergencyCellUsage *EnableExtendedEmergencyCellUsage `form:"enableExtendedEmergencyCellUsage,omitempty" json:"enableExtendedEmergencyCellUsage,omitempty"`

	// RequestedTransport WebSocket transport ws was recorded; other transports remain possible.
	RequestedTransport *RequestedTransport `form:"requestedTransport,omitempty" json:"requestedTransport,omitempty"`
}

// Getter for additional properties for CapturedTickets. Returns the specified
// element and whether it was found
func (a CapturedTickets) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CapturedTickets
func (a *CapturedTickets) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CapturedTickets to handle AdditionalProperties
func (a *CapturedTickets) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["assets"]; found {
		err = json.Unmarshal(raw, &a.Assets)
		if err != nil {
			return fmt.Errorf("error reading 'assets': %w", err)
		}
		delete(object, "assets")
	}

	if raw, found := object["host"]; found {
		err = json.Unmarshal(raw, &a.Host)
		if err != nil {
			return fmt.Errorf("error reading 'host': %w", err)
		}
		delete(object, "host")
	}

	if raw, found := object["subscriptionTopics"]; found {
		err = json.Unmarshal(raw, &a.SubscriptionTopics)
		if err != nil {
			return fmt.Errorf("error reading 'subscriptionTopics': %w", err)
		}
		delete(object, "subscriptionTopics")
	}

	if raw, found := object["ticket"]; found {
		err = json.Unmarshal(raw, &a.Ticket)
		if err != nil {
			return fmt.Errorf("error reading 'ticket': %w", err)
		}
		delete(object, "ticket")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CapturedTickets to handle AdditionalProperties
func (a CapturedTickets) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Assets != nil {
		object["assets"], err = json.Marshal(a.Assets)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'assets': %w", err)
		}
	}

	object["host"], err = json.Marshal(a.Host)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'host': %w", err)
	}

	if a.SubscriptionTopics != nil {
		object["subscriptionTopics"], err = json.Marshal(a.SubscriptionTopics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subscriptionTopics': %w", err)
		}
	}

	object["ticket"], err = json.Marshal(a.Ticket)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ticket': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for LegacySignalingTicket. Returns the specified
// element and whether it was found
func (a LegacySignalingTicket) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for LegacySignalingTicket
func (a *LegacySignalingTicket) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for LegacySignalingTicket to handle AdditionalProperties
func (a *LegacySignalingTicket) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ticket"]; found {
		err = json.Unmarshal(raw, &a.Ticket)
		if err != nil {
			return fmt.Errorf("error reading 'ticket': %w", err)
		}
		delete(object, "ticket")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for LegacySignalingTicket to handle AdditionalProperties
func (a LegacySignalingTicket) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["ticket"], err = json.Marshal(a.Ticket)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ticket': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
