// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
// Responsibility group: snapshots.

package rest

// SnapshotTimestamp defines model for SnapshotTimestamp.
type SnapshotTimestamp struct {
	Timestamp int64 `json:"timestamp"`
}

// SnapshotTimestampRequest defines model for SnapshotTimestampRequest.
type SnapshotTimestampRequest struct {
	DoorbotIds []int `json:"doorbot_ids"`
}

// SnapshotTimestampResponse defines model for SnapshotTimestampResponse.
type SnapshotTimestampResponse struct {
	Timestamps *[]SnapshotTimestamp `json:"timestamps,omitempty"`
}

// RefreshLegacySnapshotTimestampJSONRequestBody defines body for RefreshLegacySnapshotTimestamp for application/json ContentType.
type RefreshLegacySnapshotTimestampJSONRequestBody = SnapshotTimestampRequest
